// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/domains/EndpointPoliciesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockEndpointPoliciesClient is a mock of EndpointPoliciesClient interface.
type MockEndpointPoliciesClient struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointPoliciesClientMockRecorder
}

// MockEndpointPoliciesClientMockRecorder is the mock recorder for MockEndpointPoliciesClient.
type MockEndpointPoliciesClientMockRecorder struct {
	mock *MockEndpointPoliciesClient
}

// NewMockEndpointPoliciesClient creates a new mock instance.
func NewMockEndpointPoliciesClient(ctrl *gomock.Controller) *MockEndpointPoliciesClient {
	mock := &MockEndpointPoliciesClient{ctrl: ctrl}
	mock.recorder = &MockEndpointPoliciesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointPoliciesClient) EXPECT() *MockEndpointPoliciesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockEndpointPoliciesClient) Delete(domainIdParam, endpointPolicyIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", domainIdParam, endpointPolicyIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEndpointPoliciesClientMockRecorder) Delete(domainIdParam, endpointPolicyIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEndpointPoliciesClient)(nil).Delete), domainIdParam, endpointPolicyIdParam)
}

// Get mocks base method.
func (m *MockEndpointPoliciesClient) Get(domainIdParam, endpointPolicyIdParam string) (model.EndpointPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", domainIdParam, endpointPolicyIdParam)
	ret0, _ := ret[0].(model.EndpointPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEndpointPoliciesClientMockRecorder) Get(domainIdParam, endpointPolicyIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEndpointPoliciesClient)(nil).Get), domainIdParam, endpointPolicyIdParam)
}

// List mocks base method.
func (m *MockEndpointPoliciesClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.EndpointPolicyListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.EndpointPolicyListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEndpointPoliciesClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEndpointPoliciesClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockEndpointPoliciesClient) Patch(domainIdParam, endpointPolicyIdParam string, endpointPolicyParam model.EndpointPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", domainIdParam, endpointPolicyIdParam, endpointPolicyParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockEndpointPoliciesClientMockRecorder) Patch(domainIdParam, endpointPolicyIdParam, endpointPolicyParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockEndpointPoliciesClient)(nil).Patch), domainIdParam, endpointPolicyIdParam, endpointPolicyParam)
}

// Update mocks base method.
func (m *MockEndpointPoliciesClient) Update(domainIdParam, endpointPolicyIdParam string, endpointPolicyParam model.EndpointPolicy) (model.EndpointPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", domainIdParam, endpointPolicyIdParam, endpointPolicyParam)
	ret0, _ := ret[0].(model.EndpointPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEndpointPoliciesClientMockRecorder) Update(domainIdParam, endpointPolicyIdParam, endpointPolicyParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEndpointPoliciesClient)(nil).Update), domainIdParam, endpointPolicyIdParam, endpointPolicyParam)
}
