// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/services/ServiceEntriesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/vmware/vsphere-automation-sdk-go/runtime/data"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockServiceEntriesClient is a mock of ServiceEntriesClient interface.
type MockServiceEntriesClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceEntriesClientMockRecorder
}

// MockServiceEntriesClientMockRecorder is the mock recorder for MockServiceEntriesClient.
type MockServiceEntriesClientMockRecorder struct {
	mock *MockServiceEntriesClient
}

// NewMockServiceEntriesClient creates a new mock instance.
func NewMockServiceEntriesClient(ctrl *gomock.Controller) *MockServiceEntriesClient {
	mock := &MockServiceEntriesClient{ctrl: ctrl}
	mock.recorder = &MockServiceEntriesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceEntriesClient) EXPECT() *MockServiceEntriesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockServiceEntriesClient) Delete(serviceIdParam, serviceEntryIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", serviceIdParam, serviceEntryIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceEntriesClientMockRecorder) Delete(serviceIdParam, serviceEntryIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceEntriesClient)(nil).Delete), serviceIdParam, serviceEntryIdParam)
}

// Get mocks base method.
func (m *MockServiceEntriesClient) Get(serviceIdParam, serviceEntryIdParam string) (*data.StructValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", serviceIdParam, serviceEntryIdParam)
	ret0, _ := ret[0].(*data.StructValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceEntriesClientMockRecorder) Get(serviceIdParam, serviceEntryIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceEntriesClient)(nil).Get), serviceIdParam, serviceEntryIdParam)
}

// List mocks base method.
func (m *MockServiceEntriesClient) List(serviceIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.ServiceEntryListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", serviceIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.ServiceEntryListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceEntriesClientMockRecorder) List(serviceIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceEntriesClient)(nil).List), serviceIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockServiceEntriesClient) Patch(serviceIdParam, serviceEntryIdParam string, serviceEntryParam *data.StructValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", serviceIdParam, serviceEntryIdParam, serviceEntryParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockServiceEntriesClientMockRecorder) Patch(serviceIdParam, serviceEntryIdParam, serviceEntryParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockServiceEntriesClient)(nil).Patch), serviceIdParam, serviceEntryIdParam, serviceEntryParam)
}

// Update mocks base method.
func (m *MockServiceEntriesClient) Update(serviceIdParam, serviceEntryIdParam string, serviceEntryParam *data.StructValue) (*data.StructValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", serviceIdParam, serviceEntryIdParam, serviceEntryParam)
	ret0, _ := ret[0].(*data.StructValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceEntriesClientMockRecorder) Update(serviceIdParam, serviceEntryIdParam, serviceEntryParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceEntriesClient)(nil).Update), serviceIdParam, serviceEntryIdParam, serviceEntryParam)
}
