//nolint:revive
package aaa

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/aaa"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type RoleBindingClientContext utl.ClientContext

func NewRoleBindingsClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *RoleBindingClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewRoleBindingsClient(connector)

	default:
		return nil
	}
	return &RoleBindingClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c RoleBindingClientContext) Create(roleBindingParam model0.RoleBinding) (model0.RoleBinding, error) {
	var err error
	var obj model0.RoleBinding

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.RoleBindingsClient)
		obj, err = client.Create(roleBindingParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c RoleBindingClientContext) Delete(bindingIdParam string, cursorParam *string, identitySourceIdParam *string, identitySourceTypeParam *string, includedFieldsParam *string, nameParam *string, pageSizeParam *int64, pathParam *string, roleParam *string, rootPathParam *string, sortAscendingParam *bool, sortByParam *string, type_Param *string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.RoleBindingsClient)
		err = client.Delete(bindingIdParam, cursorParam, identitySourceIdParam, identitySourceTypeParam, includedFieldsParam, nameParam, pageSizeParam, pathParam, roleParam, rootPathParam, sortAscendingParam, sortByParam, type_Param)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c RoleBindingClientContext) Deletestalebindings(cursorParam *string, identitySourceIdParam *string, identitySourceTypeParam *string, includedFieldsParam *string, nameParam *string, pageSizeParam *int64, pathParam *string, roleParam *string, rootPathParam *string, sortAscendingParam *bool, sortByParam *string, type_Param *string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.RoleBindingsClient)
		err = client.Deletestalebindings(cursorParam, identitySourceIdParam, identitySourceTypeParam, includedFieldsParam, nameParam, pageSizeParam, pathParam, roleParam, rootPathParam, sortAscendingParam, sortByParam, type_Param)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c RoleBindingClientContext) Get(bindingIdParam string, cursorParam *string, identitySourceIdParam *string, identitySourceTypeParam *string, includedFieldsParam *string, nameParam *string, pageSizeParam *int64, pathParam *string, roleParam *string, rootPathParam *string, sortAscendingParam *bool, sortByParam *string, type_Param *string) (model0.RoleBinding, error) {
	var obj model0.RoleBinding
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.RoleBindingsClient)
		obj, err = client.Get(bindingIdParam, cursorParam, identitySourceIdParam, identitySourceTypeParam, includedFieldsParam, nameParam, pageSizeParam, pathParam, roleParam, rootPathParam, sortAscendingParam, sortByParam, type_Param)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c RoleBindingClientContext) List(cursorParam *string, identitySourceIdParam *string, identitySourceTypeParam *string, includedFieldsParam *string, nameParam *string, pageSizeParam *int64, pathParam *string, roleParam *string, rootPathParam *string, sortAscendingParam *bool, sortByParam *string, type_Param *string) (model0.RoleBindingListResult, error) {
	var err error
	var obj model0.RoleBindingListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.RoleBindingsClient)
		obj, err = client.List(cursorParam, identitySourceIdParam, identitySourceTypeParam, includedFieldsParam, nameParam, pageSizeParam, pathParam, roleParam, rootPathParam, sortAscendingParam, sortByParam, type_Param)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c RoleBindingClientContext) Update(bindingIdParam string, roleBindingParam model0.RoleBinding) (model0.RoleBinding, error) {
	var err error
	var obj model0.RoleBinding

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.RoleBindingsClient)
		obj, err = client.Update(bindingIdParam, roleBindingParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
