// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/shares/ResourcesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/shares/ResourcesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/shares/ResourcesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockResourcesClient is a mock of ResourcesClient interface.
type MockResourcesClient struct {
	ctrl     *gomock.Controller
	recorder *MockResourcesClientMockRecorder
	isgomock struct{}
}

// MockResourcesClientMockRecorder is the mock recorder for MockResourcesClient.
type MockResourcesClientMockRecorder struct {
	mock *MockResourcesClient
}

// NewMockResourcesClient creates a new mock instance.
func NewMockResourcesClient(ctrl *gomock.Controller) *MockResourcesClient {
	mock := &MockResourcesClient{ctrl: ctrl}
	mock.recorder = &MockResourcesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourcesClient) EXPECT() *MockResourcesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockResourcesClient) Delete(shareIdParam, sharedResourceIdParam string, forceParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", shareIdParam, sharedResourceIdParam, forceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockResourcesClientMockRecorder) Delete(shareIdParam, sharedResourceIdParam, forceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockResourcesClient)(nil).Delete), shareIdParam, sharedResourceIdParam, forceParam)
}

// Get mocks base method.
func (m *MockResourcesClient) Get(shareIdParam, sharedResourceIdParam string) (model.SharedResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", shareIdParam, sharedResourceIdParam)
	ret0, _ := ret[0].(model.SharedResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockResourcesClientMockRecorder) Get(shareIdParam, sharedResourceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResourcesClient)(nil).Get), shareIdParam, sharedResourceIdParam)
}

// List mocks base method.
func (m *MockResourcesClient) List(shareIdParam string, resourceTypeParam *string) (model.SharedResourceListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", shareIdParam, resourceTypeParam)
	ret0, _ := ret[0].(model.SharedResourceListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockResourcesClientMockRecorder) List(shareIdParam, resourceTypeParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourcesClient)(nil).List), shareIdParam, resourceTypeParam)
}

// Patch mocks base method.
func (m *MockResourcesClient) Patch(shareIdParam, sharedResourceIdParam string, sharedResourceParam model.SharedResource, forceParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", shareIdParam, sharedResourceIdParam, sharedResourceParam, forceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockResourcesClientMockRecorder) Patch(shareIdParam, sharedResourceIdParam, sharedResourceParam, forceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockResourcesClient)(nil).Patch), shareIdParam, sharedResourceIdParam, sharedResourceParam, forceParam)
}

// Update mocks base method.
func (m *MockResourcesClient) Update(shareIdParam, sharedResourceIdParam string, sharedResourceParam model.SharedResource, forceParam *bool) (model.SharedResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", shareIdParam, sharedResourceIdParam, sharedResourceParam, forceParam)
	ret0, _ := ret[0].(model.SharedResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockResourcesClientMockRecorder) Update(shareIdParam, sharedResourceIdParam, sharedResourceParam, forceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockResourcesClient)(nil).Update), shareIdParam, sharedResourceIdParam, sharedResourceParam, forceParam)
}
