// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/settings/firewall/security/intrusion_services/profiles/EffectiveSignaturesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockEffectiveSignaturesClient is a mock of EffectiveSignaturesClient interface.
type MockEffectiveSignaturesClient struct {
	ctrl     *gomock.Controller
	recorder *MockEffectiveSignaturesClientMockRecorder
}

// MockEffectiveSignaturesClientMockRecorder is the mock recorder for MockEffectiveSignaturesClient.
type MockEffectiveSignaturesClientMockRecorder struct {
	mock *MockEffectiveSignaturesClient
}

// NewMockEffectiveSignaturesClient creates a new mock instance.
func NewMockEffectiveSignaturesClient(ctrl *gomock.Controller) *MockEffectiveSignaturesClient {
	mock := &MockEffectiveSignaturesClient{ctrl: ctrl}
	mock.recorder = &MockEffectiveSignaturesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEffectiveSignaturesClient) EXPECT() *MockEffectiveSignaturesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockEffectiveSignaturesClient) Get(profileIdParam string, enforcementPointPathParam *string) (model.IdsProfileSignatures, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", profileIdParam, enforcementPointPathParam)
	ret0, _ := ret[0].(model.IdsProfileSignatures)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEffectiveSignaturesClientMockRecorder) Get(profileIdParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEffectiveSignaturesClient)(nil).Get), profileIdParam, enforcementPointPathParam)
}
