// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/sha/PreDefinedPluginsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockPreDefinedPluginsClient is a mock of PreDefinedPluginsClient interface.
type MockPreDefinedPluginsClient struct {
	ctrl     *gomock.Controller
	recorder *MockPreDefinedPluginsClientMockRecorder
}

// MockPreDefinedPluginsClientMockRecorder is the mock recorder for MockPreDefinedPluginsClient.
type MockPreDefinedPluginsClientMockRecorder struct {
	mock *MockPreDefinedPluginsClient
}

// NewMockPreDefinedPluginsClient creates a new mock instance.
func NewMockPreDefinedPluginsClient(ctrl *gomock.Controller) *MockPreDefinedPluginsClient {
	mock := &MockPreDefinedPluginsClient{ctrl: ctrl}
	mock.recorder = &MockPreDefinedPluginsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreDefinedPluginsClient) EXPECT() *MockPreDefinedPluginsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPreDefinedPluginsClient) Get(pluginIdParam string) (model.ShaPredefinedPlugin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", pluginIdParam)
	ret0, _ := ret[0].(model.ShaPredefinedPlugin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPreDefinedPluginsClientMockRecorder) Get(pluginIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPreDefinedPluginsClient)(nil).Get), pluginIdParam)
}

// List mocks base method.
func (m *MockPreDefinedPluginsClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.ShaPreDefinedPluginListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.ShaPreDefinedPluginListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPreDefinedPluginsClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPreDefinedPluginsClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
