issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude:
     - SA4004
     - SA1019
     - G402
     - G404
     - G115
     - GetOkExists

run:
  deadline: 30m

linters:
  disable-all: true
  enable:
    - misspell
    - gofmt
    - unused
    - staticcheck
    - gosec
    - goimports
    - govet
    - misspell
    - gosimple
    - staticcheck
    - ineffassign
    - unused

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
  revive:
    rules:
      - name: unreachable-code
      - name: errorf
      - name: range
      - name: superfluous-else
      - name: var-declaration
      - name: duplicated-imports
