issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude:
     - SA4004
     - SA1019
     - GetOkExists

run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    # - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    - nakedret
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - varcheck
    - vet
    - vetshadow

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
