// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/pktcap/SessionsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockSessionsClient is a mock of SessionsClient interface.
type MockSessionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsClientMockRecorder
}

// MockSessionsClientMockRecorder is the mock recorder for MockSessionsClient.
type MockSessionsClientMockRecorder struct {
	mock *MockSessionsClient
}

// NewMockSessionsClient creates a new mock instance.
func NewMockSessionsClient(ctrl *gomock.Controller) *MockSessionsClient {
	mock := &MockSessionsClient{ctrl: ctrl}
	mock.recorder = &MockSessionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionsClient) EXPECT() *MockSessionsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionsClient) Delete() (model.PktCaptureSessionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete")
	ret0, _ := ret[0].(model.PktCaptureSessionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionsClientMockRecorder) Delete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionsClient)(nil).Delete))
}

// List mocks base method.
func (m *MockSessionsClient) List() (model.PktCaptureSessionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(model.PktCaptureSessionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSessionsClientMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionsClient)(nil).List))
}
