// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/realized_state/SystemVirtualMachinesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockSystemVirtualMachinesClient is a mock of SystemVirtualMachinesClient interface.
type MockSystemVirtualMachinesClient struct {
	ctrl     *gomock.Controller
	recorder *MockSystemVirtualMachinesClientMockRecorder
}

// MockSystemVirtualMachinesClientMockRecorder is the mock recorder for MockSystemVirtualMachinesClient.
type MockSystemVirtualMachinesClientMockRecorder struct {
	mock *MockSystemVirtualMachinesClient
}

// NewMockSystemVirtualMachinesClient creates a new mock instance.
func NewMockSystemVirtualMachinesClient(ctrl *gomock.Controller) *MockSystemVirtualMachinesClient {
	mock := &MockSystemVirtualMachinesClient{ctrl: ctrl}
	mock.recorder = &MockSystemVirtualMachinesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemVirtualMachinesClient) EXPECT() *MockSystemVirtualMachinesClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSystemVirtualMachinesClient) List(cursorParam, includedFieldsParam *string, pageSizeParam *int64, queryParam *string, sortAscendingParam *bool, sortByParam *string) (model.VirtualMachineListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includedFieldsParam, pageSizeParam, queryParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.VirtualMachineListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSystemVirtualMachinesClientMockRecorder) List(cursorParam, includedFieldsParam, pageSizeParam, queryParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSystemVirtualMachinesClient)(nil).List), cursorParam, includedFieldsParam, pageSizeParam, queryParam, sortAscendingParam, sortByParam)
}
