//nolint:revive
package principalidentities

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/model"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/trust_management/principal_identities"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type CertPrincipalIdentityClientContext utl.ClientContext

func NewWithCertificateClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *CertPrincipalIdentityClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewWithCertificateClient(connector)

	default:
		return nil
	}
	return &CertPrincipalIdentityClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c CertPrincipalIdentityClientContext) Create(principalIdentityWithCertificateParam model0.PrincipalIdentityWithCertificate) (model0.PrincipalIdentity, error) {
	var err error
	var obj model0.PrincipalIdentity

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.WithCertificateClient)
		obj, err = client.Create(principalIdentityWithCertificateParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
