// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/third_party_ipam_providers/ConnectionStatusClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockConnectionStatusClient is a mock of ConnectionStatusClient interface.
type MockConnectionStatusClient struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionStatusClientMockRecorder
}

// MockConnectionStatusClientMockRecorder is the mock recorder for MockConnectionStatusClient.
type MockConnectionStatusClientMockRecorder struct {
	mock *MockConnectionStatusClient
}

// NewMockConnectionStatusClient creates a new mock instance.
func NewMockConnectionStatusClient(ctrl *gomock.Controller) *MockConnectionStatusClient {
	mock := &MockConnectionStatusClient{ctrl: ctrl}
	mock.recorder = &MockConnectionStatusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionStatusClient) EXPECT() *MockConnectionStatusClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConnectionStatusClient) Get(providerInstanceIdParam string) (model.IpamThirdPartyProviderConnectionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", providerInstanceIdParam)
	ret0, _ := ret[0].(model.IpamThirdPartyProviderConnectionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConnectionStatusClientMockRecorder) Get(providerInstanceIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConnectionStatusClient)(nil).Get), providerInstanceIdParam)
}
