// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/ip_pools/IpSubnetsClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/ip_pools/IpSubnetsClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/ip_pools/IpSubnetsClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	data "github.com/vmware/vsphere-automation-sdk-go/runtime/data"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIpSubnetsClient is a mock of IpSubnetsClient interface.
type MockIpSubnetsClient struct {
	ctrl     *gomock.Controller
	recorder *MockIpSubnetsClientMockRecorder
	isgomock struct{}
}

// MockIpSubnetsClientMockRecorder is the mock recorder for MockIpSubnetsClient.
type MockIpSubnetsClientMockRecorder struct {
	mock *MockIpSubnetsClient
}

// NewMockIpSubnetsClient creates a new mock instance.
func NewMockIpSubnetsClient(ctrl *gomock.Controller) *MockIpSubnetsClient {
	mock := &MockIpSubnetsClient{ctrl: ctrl}
	mock.recorder = &MockIpSubnetsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpSubnetsClient) EXPECT() *MockIpSubnetsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIpSubnetsClient) Delete(ipPoolIdParam, ipSubnetIdParam string, ignoreIpAllocationsParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ipPoolIdParam, ipSubnetIdParam, ignoreIpAllocationsParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIpSubnetsClientMockRecorder) Delete(ipPoolIdParam, ipSubnetIdParam, ignoreIpAllocationsParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIpSubnetsClient)(nil).Delete), ipPoolIdParam, ipSubnetIdParam, ignoreIpAllocationsParam)
}

// Get mocks base method.
func (m *MockIpSubnetsClient) Get(ipPoolIdParam, ipSubnetIdParam string) (*data.StructValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ipPoolIdParam, ipSubnetIdParam)
	ret0, _ := ret[0].(*data.StructValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIpSubnetsClientMockRecorder) Get(ipPoolIdParam, ipSubnetIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIpSubnetsClient)(nil).Get), ipPoolIdParam, ipSubnetIdParam)
}

// List mocks base method.
func (m *MockIpSubnetsClient) List(ipPoolIdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.IpAddressPoolSubnetListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ipPoolIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.IpAddressPoolSubnetListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIpSubnetsClientMockRecorder) List(ipPoolIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIpSubnetsClient)(nil).List), ipPoolIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockIpSubnetsClient) Patch(ipPoolIdParam, ipSubnetIdParam string, ipAddressPoolSubnetParam *data.StructValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ipPoolIdParam, ipSubnetIdParam, ipAddressPoolSubnetParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockIpSubnetsClientMockRecorder) Patch(ipPoolIdParam, ipSubnetIdParam, ipAddressPoolSubnetParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockIpSubnetsClient)(nil).Patch), ipPoolIdParam, ipSubnetIdParam, ipAddressPoolSubnetParam)
}

// Update mocks base method.
func (m *MockIpSubnetsClient) Update(ipPoolIdParam, ipSubnetIdParam string, ipAddressPoolSubnetParam *data.StructValue) (*data.StructValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ipPoolIdParam, ipSubnetIdParam, ipAddressPoolSubnetParam)
	ret0, _ := ret[0].(*data.StructValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIpSubnetsClientMockRecorder) Update(ipPoolIdParam, ipSubnetIdParam, ipAddressPoolSubnetParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIpSubnetsClient)(nil).Update), ipPoolIdParam, ipSubnetIdParam, ipAddressPoolSubnetParam)
}
