// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points/transport_zones/TransportNodeStatusClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockTransportNodeStatusClient is a mock of TransportNodeStatusClient interface.
type MockTransportNodeStatusClient struct {
	ctrl     *gomock.Controller
	recorder *MockTransportNodeStatusClientMockRecorder
}

// MockTransportNodeStatusClientMockRecorder is the mock recorder for MockTransportNodeStatusClient.
type MockTransportNodeStatusClientMockRecorder struct {
	mock *MockTransportNodeStatusClient
}

// NewMockTransportNodeStatusClient creates a new mock instance.
func NewMockTransportNodeStatusClient(ctrl *gomock.Controller) *MockTransportNodeStatusClient {
	mock := &MockTransportNodeStatusClient{ctrl: ctrl}
	mock.recorder = &MockTransportNodeStatusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransportNodeStatusClient) EXPECT() *MockTransportNodeStatusClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockTransportNodeStatusClient) List(siteIdParam, enforcementPointIdParam, zoneIdParam string, cursorParam *string, includeDfwHeapStatsParam *bool, includedFieldsParam, nodeTypeParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam, sourceParam, statusParam *string) (model.TransportNodeStatusListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", siteIdParam, enforcementPointIdParam, zoneIdParam, cursorParam, includeDfwHeapStatsParam, includedFieldsParam, nodeTypeParam, pageSizeParam, sortAscendingParam, sortByParam, sourceParam, statusParam)
	ret0, _ := ret[0].(model.TransportNodeStatusListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTransportNodeStatusClientMockRecorder) List(siteIdParam, enforcementPointIdParam, zoneIdParam, cursorParam, includeDfwHeapStatsParam, includedFieldsParam, nodeTypeParam, pageSizeParam, sortAscendingParam, sortByParam, sourceParam, statusParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTransportNodeStatusClient)(nil).List), siteIdParam, enforcementPointIdParam, zoneIdParam, cursorParam, includeDfwHeapStatsParam, includedFieldsParam, nodeTypeParam, pageSizeParam, sortAscendingParam, sortByParam, sourceParam, statusParam)
}
