//nolint:revive
package infra

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client1 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra"
	model1 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/model"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	client2 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects/infra"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type DhcpServerConfigClientContext utl.ClientContext

func NewDhcpServerConfigsClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *DhcpServerConfigClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewDhcpServerConfigsClient(connector)

	case utl.Global:
		client = client1.NewDhcpServerConfigsClient(connector)

	case utl.Multitenancy:
		client = client2.NewDhcpServerConfigsClient(connector)

	default:
		return nil
	}
	return &DhcpServerConfigClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c DhcpServerConfigClientContext) Get(dhcpServerConfigIdParam string) (model0.DhcpServerConfig, error) {
	var obj model0.DhcpServerConfig
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DhcpServerConfigsClient)
		obj, err = client.Get(dhcpServerConfigIdParam)
		if err != nil {
			return obj, err
		}

	case utl.Global:
		client := c.Client.(client1.DhcpServerConfigsClient)
		gmObj, err1 := client.Get(dhcpServerConfigIdParam)
		if err1 != nil {
			return obj, err1
		}
		var rawObj interface{}
		rawObj, err = utl.ConvertModelBindingType(gmObj, model1.DhcpServerConfigBindingType(), model0.DhcpServerConfigBindingType())
		obj = rawObj.(model0.DhcpServerConfig)

	case utl.Multitenancy:
		client := c.Client.(client2.DhcpServerConfigsClient)
		obj, err = client.Get(utl.DefaultOrgID, c.ProjectID, dhcpServerConfigIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c DhcpServerConfigClientContext) Patch(dhcpServerConfigIdParam string, dhcpServerConfigParam model0.DhcpServerConfig) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DhcpServerConfigsClient)
		err = client.Patch(dhcpServerConfigIdParam, dhcpServerConfigParam)

	case utl.Global:
		client := c.Client.(client1.DhcpServerConfigsClient)
		gmObj, err1 := utl.ConvertModelBindingType(dhcpServerConfigParam, model0.DhcpServerConfigBindingType(), model1.DhcpServerConfigBindingType())
		if err1 != nil {
			return err1
		}
		err = client.Patch(dhcpServerConfigIdParam, gmObj.(model1.DhcpServerConfig))

	case utl.Multitenancy:
		client := c.Client.(client2.DhcpServerConfigsClient)
		err = client.Patch(utl.DefaultOrgID, c.ProjectID, dhcpServerConfigIdParam, dhcpServerConfigParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c DhcpServerConfigClientContext) Update(dhcpServerConfigIdParam string, dhcpServerConfigParam model0.DhcpServerConfig) (model0.DhcpServerConfig, error) {
	var err error
	var obj model0.DhcpServerConfig

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DhcpServerConfigsClient)
		obj, err = client.Update(dhcpServerConfigIdParam, dhcpServerConfigParam)

	case utl.Global:
		client := c.Client.(client1.DhcpServerConfigsClient)
		gmObj, err := utl.ConvertModelBindingType(dhcpServerConfigParam, model0.DhcpServerConfigBindingType(), model1.DhcpServerConfigBindingType())
		if err != nil {
			return obj, err
		}
		gmObj, err = client.Update(dhcpServerConfigIdParam, gmObj.(model1.DhcpServerConfig))
		if err != nil {
			return obj, err
		}
		obj1, err1 := utl.ConvertModelBindingType(gmObj, model1.DhcpServerConfigBindingType(), model0.DhcpServerConfigBindingType())
		if err1 != nil {
			return obj, err1
		}
		obj = obj1.(model0.DhcpServerConfig)

	case utl.Multitenancy:
		client := c.Client.(client2.DhcpServerConfigsClient)
		obj, err = client.Update(utl.DefaultOrgID, c.ProjectID, dhcpServerConfigIdParam, dhcpServerConfigParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c DhcpServerConfigClientContext) Delete(dhcpServerConfigIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DhcpServerConfigsClient)
		err = client.Delete(dhcpServerConfigIdParam)

	case utl.Global:
		client := c.Client.(client1.DhcpServerConfigsClient)
		err = client.Delete(dhcpServerConfigIdParam)

	case utl.Multitenancy:
		client := c.Client.(client2.DhcpServerConfigsClient)
		err = client.Delete(utl.DefaultOrgID, c.ProjectID, dhcpServerConfigIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c DhcpServerConfigClientContext) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.DhcpServerConfigListResult, error) {
	var err error
	var obj model0.DhcpServerConfigListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DhcpServerConfigsClient)
		obj, err = client.List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	case utl.Global:
		client := c.Client.(client1.DhcpServerConfigsClient)
		gmObj, err := client.List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
		if err != nil {
			return obj, err
		}
		obj1, err1 := utl.ConvertModelBindingType(gmObj, model1.DhcpServerConfigListResultBindingType(), model0.DhcpServerConfigListResultBindingType())
		if err1 != nil {
			return obj, err1
		}
		obj = obj1.(model0.DhcpServerConfigListResult)

	case utl.Multitenancy:
		client := c.Client.(client2.DhcpServerConfigsClient)
		obj, err = client.List(utl.DefaultOrgID, c.ProjectID, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
