//nolint:revive
package infra

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiData_ "github.com/vmware/vsphere-automation-sdk-go/runtime/data"
	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type LBMonitorProfileClientContext utl.ClientContext

func NewLbMonitorProfilesClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *LBMonitorProfileClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewLbMonitorProfilesClient(connector)

	default:
		return nil
	}
	return &LBMonitorProfileClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c LBMonitorProfileClientContext) Delete(lbMonitorProfileIdParam string, forceParam *bool) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbMonitorProfilesClient)
		err = client.Delete(lbMonitorProfileIdParam, forceParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c LBMonitorProfileClientContext) Get(lbMonitorProfileIdParam string) (*vapiData_.StructValue, error) {
	var obj *vapiData_.StructValue
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbMonitorProfilesClient)
		obj, err = client.Get(lbMonitorProfileIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c LBMonitorProfileClientContext) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.LBMonitorProfileListResult, error) {
	var err error
	var obj model0.LBMonitorProfileListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbMonitorProfilesClient)
		obj, err = client.List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c LBMonitorProfileClientContext) Patch(lbMonitorProfileIdParam string, lbMonitorProfileParam *vapiData_.StructValue) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbMonitorProfilesClient)
		err = client.Patch(lbMonitorProfileIdParam, lbMonitorProfileParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c LBMonitorProfileClientContext) Update(lbMonitorProfileIdParam string, lbMonitorProfileParam *vapiData_.StructValue) (*vapiData_.StructValue, error) {
	var err error
	var obj *vapiData_.StructValue

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbMonitorProfilesClient)
		obj, err = client.Update(lbMonitorProfileIdParam, lbMonitorProfileParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
