//nolint:revive
package infra

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type LBServerSslProfileClientContext utl.ClientContext

func NewLbServerSslProfilesClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *LBServerSslProfileClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewLbServerSslProfilesClient(connector)

	default:
		return nil
	}
	return &LBServerSslProfileClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c LBServerSslProfileClientContext) Delete(lbServerSslProfileIdParam string, forceParam *bool) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbServerSslProfilesClient)
		err = client.Delete(lbServerSslProfileIdParam, forceParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c LBServerSslProfileClientContext) Get(lbServerSslProfileIdParam string) (model0.LBServerSslProfile, error) {
	var obj model0.LBServerSslProfile
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbServerSslProfilesClient)
		obj, err = client.Get(lbServerSslProfileIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c LBServerSslProfileClientContext) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.LBServerSslProfileListResult, error) {
	var err error
	var obj model0.LBServerSslProfileListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbServerSslProfilesClient)
		obj, err = client.List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c LBServerSslProfileClientContext) Patch(lbServerSslProfileIdParam string, lbServerSslProfileParam model0.LBServerSslProfile) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbServerSslProfilesClient)
		err = client.Patch(lbServerSslProfileIdParam, lbServerSslProfileParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c LBServerSslProfileClientContext) Update(lbServerSslProfileIdParam string, lbServerSslProfileParam model0.LBServerSslProfile) (model0.LBServerSslProfile, error) {
	var err error
	var obj model0.LBServerSslProfile

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.LbServerSslProfilesClient)
		obj, err = client.Update(lbServerSslProfileIdParam, lbServerSslProfileParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
