//nolint:revive
package infra

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client1 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra"
	model1 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/model"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	client2 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects/infra"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type PolicyDnsForwarderZoneClientContext utl.ClientContext

func NewDnsForwarderZonesClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *PolicyDnsForwarderZoneClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewDnsForwarderZonesClient(connector)

	case utl.Global:
		client = client1.NewDnsForwarderZonesClient(connector)

	case utl.Multitenancy:
		client = client2.NewDnsForwarderZonesClient(connector)

	default:
		return nil
	}
	return &PolicyDnsForwarderZoneClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c PolicyDnsForwarderZoneClientContext) Get(dnsForwarderZoneIdParam string) (model0.PolicyDnsForwarderZone, error) {
	var obj model0.PolicyDnsForwarderZone
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DnsForwarderZonesClient)
		obj, err = client.Get(dnsForwarderZoneIdParam)
		if err != nil {
			return obj, err
		}

	case utl.Global:
		client := c.Client.(client1.DnsForwarderZonesClient)
		gmObj, err1 := client.Get(dnsForwarderZoneIdParam)
		if err1 != nil {
			return obj, err1
		}
		var rawObj interface{}
		rawObj, err = utl.ConvertModelBindingType(gmObj, model1.PolicyDnsForwarderZoneBindingType(), model0.PolicyDnsForwarderZoneBindingType())
		obj = rawObj.(model0.PolicyDnsForwarderZone)

	case utl.Multitenancy:
		client := c.Client.(client2.DnsForwarderZonesClient)
		obj, err = client.Get(utl.DefaultOrgID, c.ProjectID, dnsForwarderZoneIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c PolicyDnsForwarderZoneClientContext) Patch(dnsForwarderZoneIdParam string, policyDnsForwarderZoneParam model0.PolicyDnsForwarderZone) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DnsForwarderZonesClient)
		err = client.Patch(dnsForwarderZoneIdParam, policyDnsForwarderZoneParam)

	case utl.Global:
		client := c.Client.(client1.DnsForwarderZonesClient)
		gmObj, err1 := utl.ConvertModelBindingType(policyDnsForwarderZoneParam, model0.PolicyDnsForwarderZoneBindingType(), model1.PolicyDnsForwarderZoneBindingType())
		if err1 != nil {
			return err1
		}
		err = client.Patch(dnsForwarderZoneIdParam, gmObj.(model1.PolicyDnsForwarderZone))

	case utl.Multitenancy:
		client := c.Client.(client2.DnsForwarderZonesClient)
		err = client.Patch(utl.DefaultOrgID, c.ProjectID, dnsForwarderZoneIdParam, policyDnsForwarderZoneParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c PolicyDnsForwarderZoneClientContext) Update(dnsForwarderZoneIdParam string, policyDnsForwarderZoneParam model0.PolicyDnsForwarderZone) (model0.PolicyDnsForwarderZone, error) {
	var err error
	var obj model0.PolicyDnsForwarderZone

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DnsForwarderZonesClient)
		obj, err = client.Update(dnsForwarderZoneIdParam, policyDnsForwarderZoneParam)

	case utl.Global:
		client := c.Client.(client1.DnsForwarderZonesClient)
		gmObj, err := utl.ConvertModelBindingType(policyDnsForwarderZoneParam, model0.PolicyDnsForwarderZoneBindingType(), model1.PolicyDnsForwarderZoneBindingType())
		if err != nil {
			return obj, err
		}
		gmObj, err = client.Update(dnsForwarderZoneIdParam, gmObj.(model1.PolicyDnsForwarderZone))
		if err != nil {
			return obj, err
		}
		obj1, err1 := utl.ConvertModelBindingType(gmObj, model1.PolicyDnsForwarderZoneBindingType(), model0.PolicyDnsForwarderZoneBindingType())
		if err1 != nil {
			return obj, err1
		}
		obj = obj1.(model0.PolicyDnsForwarderZone)

	case utl.Multitenancy:
		client := c.Client.(client2.DnsForwarderZonesClient)
		obj, err = client.Update(utl.DefaultOrgID, c.ProjectID, dnsForwarderZoneIdParam, policyDnsForwarderZoneParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c PolicyDnsForwarderZoneClientContext) Delete(dnsForwarderZoneIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DnsForwarderZonesClient)
		err = client.Delete(dnsForwarderZoneIdParam)

	case utl.Global:
		client := c.Client.(client1.DnsForwarderZonesClient)
		err = client.Delete(dnsForwarderZoneIdParam)

	case utl.Multitenancy:
		client := c.Client.(client2.DnsForwarderZonesClient)
		err = client.Delete(utl.DefaultOrgID, c.ProjectID, dnsForwarderZoneIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c PolicyDnsForwarderZoneClientContext) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.PolicyDnsForwarderZoneListResult, error) {
	var err error
	var obj model0.PolicyDnsForwarderZoneListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.DnsForwarderZonesClient)
		obj, err = client.List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	case utl.Global:
		client := c.Client.(client1.DnsForwarderZonesClient)
		gmObj, err := client.List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
		if err != nil {
			return obj, err
		}
		obj1, err1 := utl.ConvertModelBindingType(gmObj, model1.PolicyDnsForwarderZoneListResultBindingType(), model0.PolicyDnsForwarderZoneListResultBindingType())
		if err1 != nil {
			return obj, err1
		}
		obj = obj1.(model0.PolicyDnsForwarderZoneListResult)

	case utl.Multitenancy:
		client := c.Client.(client2.DnsForwarderZonesClient)
		obj, err = client.List(utl.DefaultOrgID, c.ProjectID, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
