// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/settings/firewall/security/intrusion_services/AffectedIpsClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/settings/firewall/security/intrusion_services/AffectedIpsClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/settings/firewall/security/intrusion_services/AffectedIpsClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAffectedIpsClient is a mock of AffectedIpsClient interface.
type MockAffectedIpsClient struct {
	ctrl     *gomock.Controller
	recorder *MockAffectedIpsClientMockRecorder
	isgomock struct{}
}

// MockAffectedIpsClientMockRecorder is the mock recorder for MockAffectedIpsClient.
type MockAffectedIpsClientMockRecorder struct {
	mock *MockAffectedIpsClient
}

// NewMockAffectedIpsClient creates a new mock instance.
func NewMockAffectedIpsClient(ctrl *gomock.Controller) *MockAffectedIpsClient {
	mock := &MockAffectedIpsClient{ctrl: ctrl}
	mock.recorder = &MockAffectedIpsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAffectedIpsClient) EXPECT() *MockAffectedIpsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAffectedIpsClient) Create(policyIdsEventDataRequestParam model.PolicyIdsEventDataRequest, contextParam, cursorParam, enforcementPointPathParam, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyIdsIpList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", policyIdsEventDataRequestParam, contextParam, cursorParam, enforcementPointPathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyIdsIpList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAffectedIpsClientMockRecorder) Create(policyIdsEventDataRequestParam, contextParam, cursorParam, enforcementPointPathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAffectedIpsClient)(nil).Create), policyIdsEventDataRequestParam, contextParam, cursorParam, enforcementPointPathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
