// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/fabric (interfaces: ComputeManagersClient)

// To generate the mock for this file, run:
// mockgen -destination=mocks/fabric/ComputeManagersClient.go -package=mocks -source=<local path>/vsphere-automation-sdk-go/services/nsxt-mp/nsx/fabric/ComputeManagersClient.go ComputeManagersClient

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/model"
)

// MockComputeManagersClient is a mock of ComputeManagersClient interface.
type MockComputeManagersClient struct {
	ctrl     *gomock.Controller
	recorder *MockComputeManagersClientMockRecorder
}

// MockComputeManagersClientMockRecorder is the mock recorder for MockComputeManagersClient.
type MockComputeManagersClientMockRecorder struct {
	mock *MockComputeManagersClient
}

// NewMockComputeManagersClient creates a new mock instance.
func NewMockComputeManagersClient(ctrl *gomock.Controller) *MockComputeManagersClient {
	mock := &MockComputeManagersClient{ctrl: ctrl}
	mock.recorder = &MockComputeManagersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComputeManagersClient) EXPECT() *MockComputeManagersClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockComputeManagersClient) Create(computeManagerParam model.ComputeManager) (model.ComputeManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", computeManagerParam)
	ret0, _ := ret[0].(model.ComputeManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockComputeManagersClientMockRecorder) Create(computeManagerParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockComputeManagersClient)(nil).Create), computeManagerParam)
}

// Delete mocks base method.
func (m *MockComputeManagersClient) Delete(computeManagerIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", computeManagerIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockComputeManagersClientMockRecorder) Delete(computeManagerIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockComputeManagersClient)(nil).Delete), computeManagerIdParam)
}

// Get mocks base method.
func (m *MockComputeManagersClient) Get(computeManagerIdParam string) (model.ComputeManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", computeManagerIdParam)
	ret0, _ := ret[0].(model.ComputeManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockComputeManagersClientMockRecorder) Get(computeManagerIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockComputeManagersClient)(nil).Get), computeManagerIdParam)
}

// List mocks base method.
func (m *MockComputeManagersClient) List(cursorParam *string, includedFieldsParam *string, originTypeParam *string, pageSizeParam *int64, serverParam *string, sortAscendingParam *bool, sortByParam *string) (model.ComputeManagerListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includedFieldsParam, originTypeParam, pageSizeParam, serverParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.ComputeManagerListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockComputeManagersClientMockRecorder) List(cursorParam, includedFieldsParam, originTypeParam, pageSizeParam, serverParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockComputeManagersClient)(nil).List), cursorParam, includedFieldsParam, originTypeParam, pageSizeParam, serverParam, sortAscendingParam, sortByParam)
}

// Update mocks base method.
func (m *MockComputeManagersClient) Update(computeManagerIdParam string, computeManagerParam model.ComputeManager) (model.ComputeManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", computeManagerIdParam, computeManagerParam)
	ret0, _ := ret[0].(model.ComputeManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockComputeManagersClientMockRecorder) Update(computeManagerIdParam, computeManagerParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockComputeManagersClient)(nil).Update), computeManagerIdParam, computeManagerParam)
}
