//go:build unittest

// © Broadcom. All Rights Reserved.
// The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

package nsxt

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

func TestMockResourceNsxtPolicyParentSecurityPolicyBMSSchema(t *testing.T) {
	resource := resourceNsxtPolicyParentSecurityPolicy()

	// Test schema structure
	assert.NotNil(t, resource.Schema)

	// The parent policy uses the general security policy schema
	// which should include scope field for BMS groups
	// Note: Schema is obtained via getPolicySecurityPolicySchema(false, true, false, false)
	// We can't test the exact schema here as it's generated by a function
	// But we can test that the resource exists and has basic structure
	assert.NotNil(t, resource.Create)
	assert.NotNil(t, resource.Read)
	assert.NotNil(t, resource.Update)
	assert.NotNil(t, resource.Delete)
}

func TestMockResourceNsxtPolicyParentSecurityPolicyBMSScopeValidation(t *testing.T) {
	testCases := []struct {
		name        string
		scope       []string
		expectValid bool
		groupTypes  map[string]int
	}{
		{
			name: "BMS only scope",
			scope: []string{
				"/infra/domains/default/groups/bms-production",
				"/infra/domains/default/groups/bms-interfaces",
			},
			expectValid: true,
			groupTypes: map[string]int{
				"bms": 2,
				"vm":  0,
			},
		},
		{
			name: "mixed BMS and VM scope",
			scope: []string{
				"/infra/domains/default/groups/bms-production",
				"/infra/domains/default/groups/vm-production",
				"/infra/domains/default/groups/bms-interfaces",
			},
			expectValid: true,
			groupTypes: map[string]int{
				"bms": 2,
				"vm":  1,
			},
		},
		{
			name: "VM only scope",
			scope: []string{
				"/infra/domains/default/groups/vm-production",
				"/infra/domains/default/groups/vm-development",
			},
			expectValid: true,
			groupTypes: map[string]int{
				"bms": 0,
				"vm":  2,
			},
		},
		{
			name:        "empty scope",
			scope:       []string{},
			expectValid: true, // Empty scope is valid (means "Any")
			groupTypes: map[string]int{
				"bms": 0,
				"vm":  0,
			},
		},
		{
			name: "invalid group path",
			scope: []string{
				"invalid-group-path",
			},
			expectValid: false,
			groupTypes: map[string]int{
				"unknown": 1,
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			isValid := validateParentPolicyScope(tc.scope)
			groupAnalysis := analyzeParentPolicyScopeGroups(tc.scope)

			assert.Equal(t, tc.expectValid, isValid)

			for groupType, expectedCount := range tc.groupTypes {
				actualCount, exists := groupAnalysis[groupType]
				if expectedCount > 0 {
					assert.True(t, exists, "Group type %s should exist", groupType)
					assert.Equal(t, expectedCount, actualCount, "Count for group type %s", groupType)
				}
			}
		})
	}
}

func TestMockResourceNsxtPolicyParentSecurityPolicyBMSModelCreation(t *testing.T) {
	testCases := []struct {
		name           string
		displayName    string
		description    string
		category       string
		scope          []string
		stateful       bool
		sequenceNumber int64
		expectedModel  model.SecurityPolicy
	}{
		{
			name:        "BMS parent policy",
			displayName: "BMS-Parent-Policy",
			description: "Parent policy for BMS servers",
			category:    "Application",
			scope: []string{
				"/infra/domains/default/groups/bms-production",
			},
			stateful:       true,
			sequenceNumber: 100,
			expectedModel: model.SecurityPolicy{
				DisplayName: &[]string{"BMS-Parent-Policy"}[0],
				Description: &[]string{"Parent policy for BMS servers"}[0],
				Category:    &[]string{"Application"}[0],
				Scope: []string{
					"/infra/domains/default/groups/bms-production",
				},
				Stateful:       &[]bool{true}[0],
				SequenceNumber: &[]int64{100}[0],
			},
		},
		{
			name:        "mixed scope parent policy",
			displayName: "Mixed-Environment-Policy",
			description: "Parent policy for mixed environment",
			category:    "Application",
			scope: []string{
				"/infra/domains/default/groups/bms-servers",
				"/infra/domains/default/groups/vm-servers",
			},
			stateful:       true,
			sequenceNumber: 200,
			expectedModel: model.SecurityPolicy{
				DisplayName: &[]string{"Mixed-Environment-Policy"}[0],
				Description: &[]string{"Parent policy for mixed environment"}[0],
				Category:    &[]string{"Application"}[0],
				Scope: []string{
					"/infra/domains/default/groups/bms-servers",
					"/infra/domains/default/groups/vm-servers",
				},
				Stateful:       &[]bool{true}[0],
				SequenceNumber: &[]int64{200}[0],
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			model := createParentSecurityPolicyModel(
				tc.displayName, tc.description, tc.category,
				tc.scope, tc.stateful, tc.sequenceNumber,
			)

			assert.Equal(t, *tc.expectedModel.DisplayName, *model.DisplayName)
			assert.Equal(t, *tc.expectedModel.Description, *model.Description)
			assert.Equal(t, *tc.expectedModel.Category, *model.Category)
			assert.Equal(t, len(tc.expectedModel.Scope), len(model.Scope))
			assert.Equal(t, *tc.expectedModel.Stateful, *model.Stateful)
			assert.Equal(t, *tc.expectedModel.SequenceNumber, *model.SequenceNumber)

			for i, expectedScopePath := range tc.expectedModel.Scope {
				assert.Equal(t, expectedScopePath, model.Scope[i])
			}
		})
	}
}

func TestMockResourceNsxtPolicyParentSecurityPolicyBMSCategoryValidation(t *testing.T) {
	testCases := []struct {
		name        string
		category    string
		expectValid bool
	}{
		{
			name:        "Application category",
			category:    "Application",
			expectValid: true,
		},
		{
			name:        "Infrastructure category",
			category:    "Infrastructure",
			expectValid: true,
		},
		{
			name:        "Environment category",
			category:    "Environment",
			expectValid: true,
		},
		{
			name:        "Emergency category",
			category:    "Emergency",
			expectValid: true,
		},
		{
			name:        "invalid category",
			category:    "InvalidCategory",
			expectValid: false,
		},
		{
			name:        "empty category",
			category:    "",
			expectValid: true, // Empty category is allowed
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := validateParentPolicyCategory(tc.category)
			assert.Equal(t, tc.expectValid, result)
		})
	}
}

func TestMockResourceNsxtPolicyParentSecurityPolicyBMSScopeGroupTypes(t *testing.T) {
	testCases := []struct {
		name           string
		scope          []string
		expectedResult map[string]interface{}
	}{
		{
			name: "BMS only scope analysis",
			scope: []string{
				"/infra/domains/default/groups/bms-production",
				"/infra/domains/default/groups/bms-interfaces",
			},
			expectedResult: map[string]interface{}{
				"bms_count":       2,
				"vm_count":        0,
				"interface_count": 1,
				"server_count":    1,
				"mixed_scope":     false,
			},
		},
		{
			name: "mixed scope analysis",
			scope: []string{
				"/infra/domains/default/groups/bms-servers",
				"/infra/domains/default/groups/vm-servers",
				"/infra/domains/default/groups/bms-interfaces",
			},
			expectedResult: map[string]interface{}{
				"bms_count":       2,
				"vm_count":        1,
				"interface_count": 1,
				"server_count":    2,
				"mixed_scope":     true,
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := analyzeScopeGroupComposition(tc.scope)

			for key, expectedValue := range tc.expectedResult {
				actualValue, exists := result[key]
				assert.True(t, exists, "Key %s should exist", key)
				assert.Equal(t, expectedValue, actualValue, "Value for key %s", key)
			}
		})
	}
}

// Helper functions to simulate actual implementation logic
func validateParentPolicyScope(scope []string) bool {
	for _, groupPath := range scope {
		if !validateGroupPath(groupPath) {
			return false
		}
	}
	return true
}

func analyzeParentPolicyScopeGroups(scope []string) map[string]int {
	result := make(map[string]int)

	for _, groupPath := range scope {
		groupType := detectGroupType(groupPath)
		if count, exists := result[groupType]; exists {
			result[groupType] = count + 1
		} else {
			result[groupType] = 1
		}
	}

	return result
}

func createParentSecurityPolicyModel(displayName, description, category string, scope []string, stateful bool, sequenceNumber int64) model.SecurityPolicy {
	objType := "SecurityPolicy"

	policy := model.SecurityPolicy{
		DisplayName:    &displayName,
		Description:    &description,
		Scope:          scope,
		Stateful:       &stateful,
		SequenceNumber: &sequenceNumber,
		ResourceType:   &objType,
	}

	if category != "" {
		policy.Category = &category
	}

	return policy
}

func validateParentPolicyCategory(category string) bool {
	if category == "" {
		return true // Empty category is allowed
	}

	validCategories := []string{
		"Application",
		"Infrastructure",
		"Environment",
		"Emergency",
	}

	for _, valid := range validCategories {
		if category == valid {
			return true
		}
	}

	return false
}

func analyzeScopeGroupComposition(scope []string) map[string]interface{} {
	result := make(map[string]interface{})

	bmsCount := 0
	vmCount := 0
	interfaceCount := 0
	serverCount := 0

	for _, groupPath := range scope {
		groupType := detectGroupType(groupPath)

		switch groupType {
		case "bms":
			bmsCount++
			if contains(groupPath, "interface") {
				interfaceCount++
			} else {
				serverCount++
			}
		case "vm":
			vmCount++
			serverCount++
		}
	}

	result["bms_count"] = bmsCount
	result["vm_count"] = vmCount
	result["interface_count"] = interfaceCount
	result["server_count"] = serverCount
	result["mixed_scope"] = bmsCount > 0 && vmCount > 0

	return result
}
