// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/segments/ports/PortDiscoveryProfileBindingMapsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockPortDiscoveryProfileBindingMapsClient is a mock of PortDiscoveryProfileBindingMapsClient interface.
type MockPortDiscoveryProfileBindingMapsClient struct {
	ctrl     *gomock.Controller
	recorder *MockPortDiscoveryProfileBindingMapsClientMockRecorder
}

// MockPortDiscoveryProfileBindingMapsClientMockRecorder is the mock recorder for MockPortDiscoveryProfileBindingMapsClient.
type MockPortDiscoveryProfileBindingMapsClientMockRecorder struct {
	mock *MockPortDiscoveryProfileBindingMapsClient
}

// NewMockPortDiscoveryProfileBindingMapsClient creates a new mock instance.
func NewMockPortDiscoveryProfileBindingMapsClient(ctrl *gomock.Controller) *MockPortDiscoveryProfileBindingMapsClient {
	mock := &MockPortDiscoveryProfileBindingMapsClient{ctrl: ctrl}
	mock.recorder = &MockPortDiscoveryProfileBindingMapsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortDiscoveryProfileBindingMapsClient) EXPECT() *MockPortDiscoveryProfileBindingMapsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPortDiscoveryProfileBindingMapsClient) Delete(tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPortDiscoveryProfileBindingMapsClientMockRecorder) Delete(tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPortDiscoveryProfileBindingMapsClient)(nil).Delete), tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam)
}

// Get mocks base method.
func (m *MockPortDiscoveryProfileBindingMapsClient) Get(tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam string) (model.PortDiscoveryProfileBindingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam)
	ret0, _ := ret[0].(model.PortDiscoveryProfileBindingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPortDiscoveryProfileBindingMapsClientMockRecorder) Get(tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPortDiscoveryProfileBindingMapsClient)(nil).Get), tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam)
}

// List mocks base method.
func (m *MockPortDiscoveryProfileBindingMapsClient) List(tier1IdParam, segmentIdParam, portIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PortDiscoveryProfileBindingMapListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier1IdParam, segmentIdParam, portIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PortDiscoveryProfileBindingMapListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPortDiscoveryProfileBindingMapsClientMockRecorder) List(tier1IdParam, segmentIdParam, portIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPortDiscoveryProfileBindingMapsClient)(nil).List), tier1IdParam, segmentIdParam, portIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockPortDiscoveryProfileBindingMapsClient) Patch(tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam string, portDiscoveryProfileBindingMapParam model.PortDiscoveryProfileBindingMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam, portDiscoveryProfileBindingMapParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockPortDiscoveryProfileBindingMapsClientMockRecorder) Patch(tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam, portDiscoveryProfileBindingMapParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockPortDiscoveryProfileBindingMapsClient)(nil).Patch), tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam, portDiscoveryProfileBindingMapParam)
}

// Update mocks base method.
func (m *MockPortDiscoveryProfileBindingMapsClient) Update(tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam string, portDiscoveryProfileBindingMapParam model.PortDiscoveryProfileBindingMap) (model.PortDiscoveryProfileBindingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam, portDiscoveryProfileBindingMapParam)
	ret0, _ := ret[0].(model.PortDiscoveryProfileBindingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPortDiscoveryProfileBindingMapsClientMockRecorder) Update(tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam, portDiscoveryProfileBindingMapParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPortDiscoveryProfileBindingMapsClient)(nil).Update), tier1IdParam, segmentIdParam, portIdParam, portDiscoveryProfileBindingMapIdParam, portDiscoveryProfileBindingMapParam)
}
