//nolint:revive
package globalinfra

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/upgrade"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type PreUpgradeChecksClientContext utl.ClientContext

func NewPreUpgradeChecksClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *PreUpgradeChecksClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Global:
		client = client0.NewPreUpgradeChecksClient(connector)

	default:
		return nil
	}
	return &PreUpgradeChecksClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c PreUpgradeChecksClientContext) Acknowledge(preUpgradeCheckIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Global:
		client := c.Client.(client0.PreUpgradeChecksClient)
		err = client.Acknowledge(preUpgradeCheckIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c PreUpgradeChecksClientContext) Resolve(preUpgradeCheckIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Global:
		client := c.Client.(client0.PreUpgradeChecksClient)
		err = client.Resolve(preUpgradeCheckIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}
