// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/domains/groups/members/IdentityGroupsClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/domains/groups/members/IdentityGroupsClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/domains/groups/members/IdentityGroupsClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityGroupsClient is a mock of IdentityGroupsClient interface.
type MockIdentityGroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityGroupsClientMockRecorder
	isgomock struct{}
}

// MockIdentityGroupsClientMockRecorder is the mock recorder for MockIdentityGroupsClient.
type MockIdentityGroupsClientMockRecorder struct {
	mock *MockIdentityGroupsClient
}

// NewMockIdentityGroupsClient creates a new mock instance.
func NewMockIdentityGroupsClient(ctrl *gomock.Controller) *MockIdentityGroupsClient {
	mock := &MockIdentityGroupsClient{ctrl: ctrl}
	mock.recorder = &MockIdentityGroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityGroupsClient) EXPECT() *MockIdentityGroupsClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockIdentityGroupsClient) List(domainIdParam, groupIdParam string, cursorParam, enforcementPointPathParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyGroupMembersListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", domainIdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyGroupMembersListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIdentityGroupsClientMockRecorder) List(domainIdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIdentityGroupsClient)(nil).List), domainIdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
