// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/domains/groups/members/IpGroupsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockIpGroupsClient is a mock of IpGroupsClient interface.
type MockIpGroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockIpGroupsClientMockRecorder
}

// MockIpGroupsClientMockRecorder is the mock recorder for MockIpGroupsClient.
type MockIpGroupsClientMockRecorder struct {
	mock *MockIpGroupsClient
}

// NewMockIpGroupsClient creates a new mock instance.
func NewMockIpGroupsClient(ctrl *gomock.Controller) *MockIpGroupsClient {
	mock := &MockIpGroupsClient{ctrl: ctrl}
	mock.recorder = &MockIpGroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpGroupsClient) EXPECT() *MockIpGroupsClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockIpGroupsClient) List(domainIdParam, groupIdParam string, cursorParam, enforcementPointPathParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyGroupMembersListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", domainIdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyGroupMembersListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIpGroupsClientMockRecorder) List(domainIdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIpGroupsClient)(nil).List), domainIdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
