// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/domains/groups/members/KubernetesServicesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/domains/groups/members/KubernetesServicesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/domains/groups/members/KubernetesServicesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockKubernetesServicesClient is a mock of KubernetesServicesClient interface.
type MockKubernetesServicesClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubernetesServicesClientMockRecorder
	isgomock struct{}
}

// MockKubernetesServicesClientMockRecorder is the mock recorder for MockKubernetesServicesClient.
type MockKubernetesServicesClientMockRecorder struct {
	mock *MockKubernetesServicesClient
}

// NewMockKubernetesServicesClient creates a new mock instance.
func NewMockKubernetesServicesClient(ctrl *gomock.Controller) *MockKubernetesServicesClient {
	mock := &MockKubernetesServicesClient{ctrl: ctrl}
	mock.recorder = &MockKubernetesServicesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubernetesServicesClient) EXPECT() *MockKubernetesServicesClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockKubernetesServicesClient) List(domainIdParam, groupIdParam string, clusterIdParam, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyGroupKubernetesServiceListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", domainIdParam, groupIdParam, clusterIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyGroupKubernetesServiceListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockKubernetesServicesClientMockRecorder) List(domainIdParam, groupIdParam, clusterIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockKubernetesServicesClient)(nil).List), domainIdParam, groupIdParam, clusterIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
