//nolint:revive
package ospf

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/locale_services/ospf"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type OspfAreaConfigClientContext utl.ClientContext

func NewAreasClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *OspfAreaConfigClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewAreasClient(connector)

	default:
		return nil
	}
	return &OspfAreaConfigClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c OspfAreaConfigClientContext) Get(tier0IdParam string, localeServiceIdParam string, areaIdParam string) (model0.OspfAreaConfig, error) {
	var obj model0.OspfAreaConfig
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.AreasClient)
		obj, err = client.Get(tier0IdParam, localeServiceIdParam, areaIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c OspfAreaConfigClientContext) List(tier0IdParam string, localeServiceIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.OspfAreaConfigListResult, error) {
	var err error
	var obj model0.OspfAreaConfigListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.AreasClient)
		obj, err = client.List(tier0IdParam, localeServiceIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c OspfAreaConfigClientContext) Patch(tier0IdParam string, localeServiceIdParam string, areaIdParam string, ospfAreaConfigParam model0.OspfAreaConfig) (model0.OspfAreaConfig, error) {
	var err error
	var obj model0.OspfAreaConfig

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.AreasClient)
		obj, err = client.Patch(tier0IdParam, localeServiceIdParam, areaIdParam, ospfAreaConfigParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c OspfAreaConfigClientContext) Update(tier0IdParam string, localeServiceIdParam string, areaIdParam string, ospfAreaConfigParam model0.OspfAreaConfig) (model0.OspfAreaConfig, error) {
	var err error
	var obj model0.OspfAreaConfig

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.AreasClient)
		obj, err = client.Update(tier0IdParam, localeServiceIdParam, areaIdParam, ospfAreaConfigParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c OspfAreaConfigClientContext) Delete(tier0IdParam string, localeServiceIdParam string, areaIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.AreasClient)
		err = client.Delete(tier0IdParam, localeServiceIdParam, areaIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}
