// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/upgrade (interfaces: StatusSummaryClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/model"
)

// MockStatusSummaryClient is a mock of StatusSummaryClient interface.
type MockStatusSummaryClient struct {
	ctrl     *gomock.Controller
	recorder *MockStatusSummaryClientMockRecorder
}

// MockStatusSummaryClientMockRecorder is the mock recorder for MockStatusSummaryClient.
type MockStatusSummaryClientMockRecorder struct {
	mock *MockStatusSummaryClient
}

// NewMockStatusSummaryClient creates a new mock instance.
func NewMockStatusSummaryClient(ctrl *gomock.Controller) *MockStatusSummaryClient {
	mock := &MockStatusSummaryClient{ctrl: ctrl}
	mock.recorder = &MockStatusSummaryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusSummaryClient) EXPECT() *MockStatusSummaryClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStatusSummaryClient) Get(componentTypeParam *string, selectionStatusParam *string, showHistoryParam *bool) (model.UpgradeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", componentTypeParam, selectionStatusParam, showHistoryParam)
	ret0, _ := ret[0].(model.UpgradeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStatusSummaryClientMockRecorder) Get(componentTypeParam, selectionStatusParam, showHistoryParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStatusSummaryClient)(nil).Get), componentTypeParam, selectionStatusParam, showHistoryParam)
}
