//nolint:revive
package tier0s

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type EvpnConfigClientContext utl.ClientContext

func NewEvpnClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *EvpnConfigClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewEvpnClient(connector)

	default:
		return nil
	}
	return &EvpnConfigClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c EvpnConfigClientContext) Get(tier0IdParam string) (model0.EvpnConfig, error) {
	var obj model0.EvpnConfig
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.EvpnClient)
		obj, err = client.Get(tier0IdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c EvpnConfigClientContext) Patch(tier0IdParam string, evpnConfigParam model0.EvpnConfig) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.EvpnClient)
		err = client.Patch(tier0IdParam, evpnConfigParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c EvpnConfigClientContext) Update(tier0IdParam string, evpnConfigParam model0.EvpnConfig) (model0.EvpnConfig, error) {
	var err error
	var obj model0.EvpnConfig

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.EvpnClient)
		obj, err = client.Update(tier0IdParam, evpnConfigParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
