//nolint:revive
package tier0s

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type PolicyInterVrfRoutingConfigClientContext utl.ClientContext

func NewInterVrfRoutingClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *PolicyInterVrfRoutingConfigClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewInterVrfRoutingClient(connector)

	default:
		return nil
	}
	return &PolicyInterVrfRoutingConfigClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c PolicyInterVrfRoutingConfigClientContext) Delete(tier0IdParam string, interVrfRoutingIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.InterVrfRoutingClient)
		err = client.Delete(tier0IdParam, interVrfRoutingIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c PolicyInterVrfRoutingConfigClientContext) Get(tier0IdParam string, interVrfRoutingIdParam string) (model0.PolicyInterVrfRoutingConfig, error) {
	var obj model0.PolicyInterVrfRoutingConfig
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.InterVrfRoutingClient)
		obj, err = client.Get(tier0IdParam, interVrfRoutingIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c PolicyInterVrfRoutingConfigClientContext) List(tier0IdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.PolicyInterVrfRoutingConfigListResult, error) {
	var err error
	var obj model0.PolicyInterVrfRoutingConfigListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.InterVrfRoutingClient)
		obj, err = client.List(tier0IdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c PolicyInterVrfRoutingConfigClientContext) Patch(tier0IdParam string, interVrfRoutingIdParam string, policyInterVrfRoutingConfigParam model0.PolicyInterVrfRoutingConfig) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.InterVrfRoutingClient)
		err = client.Patch(tier0IdParam, interVrfRoutingIdParam, policyInterVrfRoutingConfigParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c PolicyInterVrfRoutingConfigClientContext) Update(tier0IdParam string, interVrfRoutingIdParam string, policyInterVrfRoutingConfigParam model0.PolicyInterVrfRoutingConfig) (model0.PolicyInterVrfRoutingConfig, error) {
	var err error
	var obj model0.PolicyInterVrfRoutingConfig

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.InterVrfRoutingClient)
		obj, err = client.Update(tier0IdParam, interVrfRoutingIdParam, policyInterVrfRoutingConfigParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
