// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/settings/scrx/ClusterConfigsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockClusterConfigsClient is a mock of ClusterConfigsClient interface.
type MockClusterConfigsClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterConfigsClientMockRecorder
}

// MockClusterConfigsClientMockRecorder is the mock recorder for MockClusterConfigsClient.
type MockClusterConfigsClientMockRecorder struct {
	mock *MockClusterConfigsClient
}

// NewMockClusterConfigsClient creates a new mock instance.
func NewMockClusterConfigsClient(ctrl *gomock.Controller) *MockClusterConfigsClient {
	mock := &MockClusterConfigsClient{ctrl: ctrl}
	mock.recorder = &MockClusterConfigsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterConfigsClient) EXPECT() *MockClusterConfigsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockClusterConfigsClient) Get(clusterIdParam string) (model.ScrxClusterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", clusterIdParam)
	ret0, _ := ret[0].(model.ScrxClusterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterConfigsClientMockRecorder) Get(clusterIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterConfigsClient)(nil).Get), clusterIdParam)
}

// List mocks base method.
func (m *MockClusterConfigsClient) List() (model.ScrxClusterConfigListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(model.ScrxClusterConfigListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterConfigsClientMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterConfigsClient)(nil).List))
}

// Patch mocks base method.
func (m *MockClusterConfigsClient) Patch(clusterIdParam string, scrxClusterConfigParam model.ScrxClusterConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", clusterIdParam, scrxClusterConfigParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockClusterConfigsClientMockRecorder) Patch(clusterIdParam, scrxClusterConfigParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockClusterConfigsClient)(nil).Patch), clusterIdParam, scrxClusterConfigParam)
}

// Update mocks base method.
func (m *MockClusterConfigsClient) Update(clusterIdParam string, scrxClusterConfigParam model.ScrxClusterConfig) (model.ScrxClusterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", clusterIdParam, scrxClusterConfigParam)
	ret0, _ := ret[0].(model.ScrxClusterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClusterConfigsClientMockRecorder) Update(clusterIdParam, scrxClusterConfigParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClusterConfigsClient)(nil).Update), clusterIdParam, scrxClusterConfigParam)
}
