// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects/transit_gateways/nat (interfaces: NatRulesClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockNatRulesClient is a mock of NatRulesClient interface.
type MockNatRulesClient struct {
	ctrl     *gomock.Controller
	recorder *MockNatRulesClientMockRecorder
}

// MockNatRulesClientMockRecorder is the mock recorder for MockNatRulesClient.
type MockNatRulesClientMockRecorder struct {
	mock *MockNatRulesClient
}

// NewMockNatRulesClient creates a new mock instance.
func NewMockNatRulesClient(ctrl *gomock.Controller) *MockNatRulesClient {
	mock := &MockNatRulesClient{ctrl: ctrl}
	mock.recorder = &MockNatRulesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatRulesClient) EXPECT() *MockNatRulesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockNatRulesClient) Delete(orgIdParam string, projectIdParam string, tgwIdParam string, natIdParam string, natRuleIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNatRulesClientMockRecorder) Delete(orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNatRulesClient)(nil).Delete), orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam)
}

// Get mocks base method.
func (m *MockNatRulesClient) Get(orgIdParam string, projectIdParam string, tgwIdParam string, natIdParam string, natRuleIdParam string) (model.TransitGatewayNatRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam)
	ret0, _ := ret[0].(model.TransitGatewayNatRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNatRulesClientMockRecorder) Get(orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNatRulesClient)(nil).Get), orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam)
}

// List mocks base method.
func (m *MockNatRulesClient) List(orgIdParam string, projectIdParam string, tgwIdParam string, natIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.TransitGatewayNatRuleListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", orgIdParam, projectIdParam, tgwIdParam, natIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.TransitGatewayNatRuleListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNatRulesClientMockRecorder) List(orgIdParam, projectIdParam, tgwIdParam, natIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNatRulesClient)(nil).List), orgIdParam, projectIdParam, tgwIdParam, natIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockNatRulesClient) Patch(orgIdParam string, projectIdParam string, tgwIdParam string, natIdParam string, natRuleIdParam string, transitGatewayNatRuleParam model.TransitGatewayNatRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam, transitGatewayNatRuleParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockNatRulesClientMockRecorder) Patch(orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam, transitGatewayNatRuleParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockNatRulesClient)(nil).Patch), orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam, transitGatewayNatRuleParam)
}

// Update mocks base method.
func (m *MockNatRulesClient) Update(orgIdParam string, projectIdParam string, tgwIdParam string, natIdParam string, natRuleIdParam string, transitGatewayNatRuleParam model.TransitGatewayNatRule) (model.TransitGatewayNatRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam, transitGatewayNatRuleParam)
	ret0, _ := ret[0].(model.TransitGatewayNatRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNatRulesClientMockRecorder) Update(orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam, transitGatewayNatRuleParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNatRulesClient)(nil).Update), orgIdParam, projectIdParam, tgwIdParam, natIdParam, natRuleIdParam, transitGatewayNatRuleParam)
}
