// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/settings/firewall/idfw/GroupVmDetailsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockGroupVmDetailsClient is a mock of GroupVmDetailsClient interface.
type MockGroupVmDetailsClient struct {
	ctrl     *gomock.Controller
	recorder *MockGroupVmDetailsClientMockRecorder
}

// MockGroupVmDetailsClientMockRecorder is the mock recorder for MockGroupVmDetailsClient.
type MockGroupVmDetailsClientMockRecorder struct {
	mock *MockGroupVmDetailsClient
}

// NewMockGroupVmDetailsClient creates a new mock instance.
func NewMockGroupVmDetailsClient(ctrl *gomock.Controller) *MockGroupVmDetailsClient {
	mock := &MockGroupVmDetailsClient{ctrl: ctrl}
	mock.recorder = &MockGroupVmDetailsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupVmDetailsClient) EXPECT() *MockGroupVmDetailsClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockGroupVmDetailsClient) List(groupPathParam string, enforcementPointPathParam *string) (model.PolicyIdfwGroupVmDetailListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", groupPathParam, enforcementPointPathParam)
	ret0, _ := ret[0].(model.PolicyIdfwGroupVmDetailListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGroupVmDetailsClientMockRecorder) List(groupPathParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupVmDetailsClient)(nil).List), groupPathParam, enforcementPointPathParam)
}
