// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/settings/firewall/idfw/StandaloneHostSwitchSettingClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockStandaloneHostSwitchSettingClient is a mock of StandaloneHostSwitchSettingClient interface.
type MockStandaloneHostSwitchSettingClient struct {
	ctrl     *gomock.Controller
	recorder *MockStandaloneHostSwitchSettingClientMockRecorder
}

// MockStandaloneHostSwitchSettingClientMockRecorder is the mock recorder for MockStandaloneHostSwitchSettingClient.
type MockStandaloneHostSwitchSettingClientMockRecorder struct {
	mock *MockStandaloneHostSwitchSettingClient
}

// NewMockStandaloneHostSwitchSettingClient creates a new mock instance.
func NewMockStandaloneHostSwitchSettingClient(ctrl *gomock.Controller) *MockStandaloneHostSwitchSettingClient {
	mock := &MockStandaloneHostSwitchSettingClient{ctrl: ctrl}
	mock.recorder = &MockStandaloneHostSwitchSettingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStandaloneHostSwitchSettingClient) EXPECT() *MockStandaloneHostSwitchSettingClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStandaloneHostSwitchSettingClient) Get() (model.StandaloneHostIdfwConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(model.StandaloneHostIdfwConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStandaloneHostSwitchSettingClientMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStandaloneHostSwitchSettingClient)(nil).Get))
}

// Patch mocks base method.
func (m *MockStandaloneHostSwitchSettingClient) Patch(standaloneHostIdfwConfigurationParam model.StandaloneHostIdfwConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", standaloneHostIdfwConfigurationParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockStandaloneHostSwitchSettingClientMockRecorder) Patch(standaloneHostIdfwConfigurationParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockStandaloneHostSwitchSettingClient)(nil).Patch), standaloneHostIdfwConfigurationParam)
}

// Update mocks base method.
func (m *MockStandaloneHostSwitchSettingClient) Update(standaloneHostIdfwConfigurationParam model.StandaloneHostIdfwConfiguration) (model.StandaloneHostIdfwConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", standaloneHostIdfwConfigurationParam)
	ret0, _ := ret[0].(model.StandaloneHostIdfwConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStandaloneHostSwitchSettingClientMockRecorder) Update(standaloneHostIdfwConfigurationParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStandaloneHostSwitchSettingClient)(nil).Update), standaloneHostIdfwConfigurationParam)
}
