// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/settings/firewall/idfw/UserSessionDataClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockUserSessionDataClient is a mock of UserSessionDataClient interface.
type MockUserSessionDataClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserSessionDataClientMockRecorder
}

// MockUserSessionDataClientMockRecorder is the mock recorder for MockUserSessionDataClient.
type MockUserSessionDataClientMockRecorder struct {
	mock *MockUserSessionDataClient
}

// NewMockUserSessionDataClient creates a new mock instance.
func NewMockUserSessionDataClient(ctrl *gomock.Controller) *MockUserSessionDataClient {
	mock := &MockUserSessionDataClient{ctrl: ctrl}
	mock.recorder = &MockUserSessionDataClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSessionDataClient) EXPECT() *MockUserSessionDataClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserSessionDataClient) Get(enforcementPointPathParam *string) (model.IdfwUserSessionDataAndMappings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", enforcementPointPathParam)
	ret0, _ := ret[0].(model.IdfwUserSessionDataAndMappings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserSessionDataClientMockRecorder) Get(enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserSessionDataClient)(nil).Get), enforcementPointPathParam)
}
