// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx (interfaces: EdgeClustersClient)

// To generate the mock for this file, run:
// mockgen -destination=mocks/nsx/EdgeClustersClient.go -package=mocks -source=<local path>/vsphere-automation-sdk-go/services/nsxt-mp/nsx/EdgeClustersClient.go EdgeClustersClient

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/model"
)

// MockEdgeClustersClient is a mock of EdgeClustersClient interface.
type MockEdgeClustersClient struct {
	ctrl     *gomock.Controller
	recorder *MockEdgeClustersClientMockRecorder
}

// MockEdgeClustersClientMockRecorder is the mock recorder for MockEdgeClustersClient.
type MockEdgeClustersClientMockRecorder struct {
	mock *MockEdgeClustersClient
}

// NewMockEdgeClustersClient creates a new mock instance.
func NewMockEdgeClustersClient(ctrl *gomock.Controller) *MockEdgeClustersClient {
	mock := &MockEdgeClustersClient{ctrl: ctrl}
	mock.recorder = &MockEdgeClustersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEdgeClustersClient) EXPECT() *MockEdgeClustersClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEdgeClustersClient) Create(edgeClusterParam model.EdgeCluster) (model.EdgeCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", edgeClusterParam)
	ret0, _ := ret[0].(model.EdgeCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEdgeClustersClientMockRecorder) Create(edgeClusterParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEdgeClustersClient)(nil).Create), edgeClusterParam)
}

// Delete mocks base method.
func (m *MockEdgeClustersClient) Delete(edgeClusterIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", edgeClusterIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEdgeClustersClientMockRecorder) Delete(edgeClusterIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEdgeClustersClient)(nil).Delete), edgeClusterIdParam)
}

// Get mocks base method.
func (m *MockEdgeClustersClient) Get(edgeClusterIdParam string) (model.EdgeCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", edgeClusterIdParam)
	ret0, _ := ret[0].(model.EdgeCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEdgeClustersClientMockRecorder) Get(edgeClusterIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEdgeClustersClient)(nil).Get), edgeClusterIdParam)
}

// List mocks base method.
func (m *MockEdgeClustersClient) List(cursorParam *string, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.EdgeClusterListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.EdgeClusterListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEdgeClustersClientMockRecorder) List(cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEdgeClustersClient)(nil).List), cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Relocateandremove mocks base method.
func (m *MockEdgeClustersClient) Relocateandremove(edgeClusterIdParam string, edgeClusterMemberIndexParam model.EdgeClusterMemberIndex) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Relocateandremove", edgeClusterIdParam, edgeClusterMemberIndexParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Relocateandremove indicates an expected call of Relocateandremove.
func (mr *MockEdgeClustersClientMockRecorder) Relocateandremove(edgeClusterIdParam, edgeClusterMemberIndexParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Relocateandremove", reflect.TypeOf((*MockEdgeClustersClient)(nil).Relocateandremove), edgeClusterIdParam, edgeClusterMemberIndexParam)
}

// Replacetransportnode mocks base method.
func (m *MockEdgeClustersClient) Replacetransportnode(edgeClusterIdParam string, edgeClusterMemberTransportNodeParam model.EdgeClusterMemberTransportNode) (model.EdgeCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replacetransportnode", edgeClusterIdParam, edgeClusterMemberTransportNodeParam)
	ret0, _ := ret[0].(model.EdgeCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replacetransportnode indicates an expected call of Replacetransportnode.
func (mr *MockEdgeClustersClientMockRecorder) Replacetransportnode(edgeClusterIdParam, edgeClusterMemberTransportNodeParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replacetransportnode", reflect.TypeOf((*MockEdgeClustersClient)(nil).Replacetransportnode), edgeClusterIdParam, edgeClusterMemberTransportNodeParam)
}

// Update mocks base method.
func (m *MockEdgeClustersClient) Update(edgeClusterIdParam string, edgeClusterParam model.EdgeCluster) (model.EdgeCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", edgeClusterIdParam, edgeClusterParam)
	ret0, _ := ret[0].(model.EdgeCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEdgeClustersClientMockRecorder) Update(edgeClusterIdParam, edgeClusterParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEdgeClustersClient)(nil).Update), edgeClusterIdParam, edgeClusterParam)
}
