// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points/edge_transport_nodes/troubleshoot/DatapathClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockDatapathClient is a mock of DatapathClient interface.
type MockDatapathClient struct {
	ctrl     *gomock.Controller
	recorder *MockDatapathClientMockRecorder
}

// MockDatapathClientMockRecorder is the mock recorder for MockDatapathClient.
type MockDatapathClientMockRecorder struct {
	mock *MockDatapathClient
}

// NewMockDatapathClient creates a new mock instance.
func NewMockDatapathClient(ctrl *gomock.Controller) *MockDatapathClient {
	mock := &MockDatapathClient{ctrl: ctrl}
	mock.recorder = &MockDatapathClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatapathClient) EXPECT() *MockDatapathClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDatapathClient) Get(siteIdParam, enforcementPointIdParam string) (model.PolicyEdgeTransportNodeDatapathTroubleshooting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", siteIdParam, enforcementPointIdParam)
	ret0, _ := ret[0].(model.PolicyEdgeTransportNodeDatapathTroubleshooting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDatapathClientMockRecorder) Get(siteIdParam, enforcementPointIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDatapathClient)(nil).Get), siteIdParam, enforcementPointIdParam)
}

// Patch mocks base method.
func (m *MockDatapathClient) Patch(siteIdParam, enforcementPointIdParam string, policyEdgeTransportNodeDatapathTroubleshootingParam model.PolicyEdgeTransportNodeDatapathTroubleshooting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", siteIdParam, enforcementPointIdParam, policyEdgeTransportNodeDatapathTroubleshootingParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockDatapathClientMockRecorder) Patch(siteIdParam, enforcementPointIdParam, policyEdgeTransportNodeDatapathTroubleshootingParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockDatapathClient)(nil).Patch), siteIdParam, enforcementPointIdParam, policyEdgeTransportNodeDatapathTroubleshootingParam)
}
