// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/tier_0s/RouteMapsClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/tier_0s/RouteMapsClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/tier_0s/RouteMapsClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRouteMapsClient is a mock of RouteMapsClient interface.
type MockRouteMapsClient struct {
	ctrl     *gomock.Controller
	recorder *MockRouteMapsClientMockRecorder
	isgomock struct{}
}

// MockRouteMapsClientMockRecorder is the mock recorder for MockRouteMapsClient.
type MockRouteMapsClientMockRecorder struct {
	mock *MockRouteMapsClient
}

// NewMockRouteMapsClient creates a new mock instance.
func NewMockRouteMapsClient(ctrl *gomock.Controller) *MockRouteMapsClient {
	mock := &MockRouteMapsClient{ctrl: ctrl}
	mock.recorder = &MockRouteMapsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteMapsClient) EXPECT() *MockRouteMapsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRouteMapsClient) Delete(tier0IdParam, routeMapIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tier0IdParam, routeMapIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRouteMapsClientMockRecorder) Delete(tier0IdParam, routeMapIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRouteMapsClient)(nil).Delete), tier0IdParam, routeMapIdParam)
}

// Get mocks base method.
func (m *MockRouteMapsClient) Get(tier0IdParam, routeMapIdParam string) (model.Tier0RouteMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier0IdParam, routeMapIdParam)
	ret0, _ := ret[0].(model.Tier0RouteMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRouteMapsClientMockRecorder) Get(tier0IdParam, routeMapIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRouteMapsClient)(nil).Get), tier0IdParam, routeMapIdParam)
}

// List mocks base method.
func (m *MockRouteMapsClient) List(tier0IdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.Tier0RouteMapListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier0IdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.Tier0RouteMapListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRouteMapsClientMockRecorder) List(tier0IdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRouteMapsClient)(nil).List), tier0IdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockRouteMapsClient) Patch(tier0IdParam, routeMapIdParam string, tier0RouteMapParam model.Tier0RouteMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier0IdParam, routeMapIdParam, tier0RouteMapParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockRouteMapsClientMockRecorder) Patch(tier0IdParam, routeMapIdParam, tier0RouteMapParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockRouteMapsClient)(nil).Patch), tier0IdParam, routeMapIdParam, tier0RouteMapParam)
}

// Update mocks base method.
func (m *MockRouteMapsClient) Update(tier0IdParam, routeMapIdParam string, tier0RouteMapParam model.Tier0RouteMap) (model.Tier0RouteMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier0IdParam, routeMapIdParam, tier0RouteMapParam)
	ret0, _ := ret[0].(model.Tier0RouteMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRouteMapsClientMockRecorder) Update(tier0IdParam, routeMapIdParam, tier0RouteMapParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRouteMapsClient)(nil).Update), tier0IdParam, routeMapIdParam, tier0RouteMapParam)
}
