// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp@v0.6.1-0.20241118070726-666c7cd6e466/nsx/fabric/DiscoveredNodesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscoveredNodesClient is a mock of DiscoveredNodesClient interface.
type MockDiscoveredNodesClient struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveredNodesClientMockRecorder
}

// MockDiscoveredNodesClientMockRecorder is the mock recorder for MockDiscoveredNodesClient.
type MockDiscoveredNodesClientMockRecorder struct {
	mock *MockDiscoveredNodesClient
}

// NewMockDiscoveredNodesClient creates a new mock instance.
func NewMockDiscoveredNodesClient(ctrl *gomock.Controller) *MockDiscoveredNodesClient {
	mock := &MockDiscoveredNodesClient{ctrl: ctrl}
	mock.recorder = &MockDiscoveredNodesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoveredNodesClient) EXPECT() *MockDiscoveredNodesClientMockRecorder {
	return m.recorder
}

// Createtransportnode mocks base method.
func (m *MockDiscoveredNodesClient) Createtransportnode(nodeExtIdParam string, transportNodeParam model.TransportNode, overrideNsxOwnershipParam *bool) (model.TransportNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Createtransportnode", nodeExtIdParam, transportNodeParam, overrideNsxOwnershipParam)
	ret0, _ := ret[0].(model.TransportNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Createtransportnode indicates an expected call of Createtransportnode.
func (mr *MockDiscoveredNodesClientMockRecorder) Createtransportnode(nodeExtIdParam, transportNodeParam, overrideNsxOwnershipParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Createtransportnode", reflect.TypeOf((*MockDiscoveredNodesClient)(nil).Createtransportnode), nodeExtIdParam, transportNodeParam, overrideNsxOwnershipParam)
}

// Get mocks base method.
func (m *MockDiscoveredNodesClient) Get(nodeExtIdParam string) (model.DiscoveredNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", nodeExtIdParam)
	ret0, _ := ret[0].(model.DiscoveredNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDiscoveredNodesClientMockRecorder) Get(nodeExtIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDiscoveredNodesClient)(nil).Get), nodeExtIdParam)
}

// List mocks base method.
func (m *MockDiscoveredNodesClient) List(cmLocalIdParam, cursorParam, displayNameParam, externalIdParam, hasParentParam, includedFieldsParam, ipAddressParam, nodeIdParam, nodeTypeParam, originIdParam *string, pageSizeParam *int64, parentComputeCollectionParam *string, sortAscendingParam *bool, sortByParam *string) (model.DiscoveredNodeListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cmLocalIdParam, cursorParam, displayNameParam, externalIdParam, hasParentParam, includedFieldsParam, ipAddressParam, nodeIdParam, nodeTypeParam, originIdParam, pageSizeParam, parentComputeCollectionParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.DiscoveredNodeListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDiscoveredNodesClientMockRecorder) List(cmLocalIdParam, cursorParam, displayNameParam, externalIdParam, hasParentParam, includedFieldsParam, ipAddressParam, nodeIdParam, nodeTypeParam, originIdParam, pageSizeParam, parentComputeCollectionParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiscoveredNodesClient)(nil).List), cmLocalIdParam, cursorParam, displayNameParam, externalIdParam, hasParentParam, includedFieldsParam, ipAddressParam, nodeIdParam, nodeTypeParam, originIdParam, pageSizeParam, parentComputeCollectionParam, sortAscendingParam, sortByParam)
}

// Reapplyclusterconfig mocks base method.
func (m *MockDiscoveredNodesClient) Reapplyclusterconfig(nodeExtIdParam string, overrideNsxOwnershipParam *bool) (model.TransportNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reapplyclusterconfig", nodeExtIdParam, overrideNsxOwnershipParam)
	ret0, _ := ret[0].(model.TransportNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reapplyclusterconfig indicates an expected call of Reapplyclusterconfig.
func (mr *MockDiscoveredNodesClientMockRecorder) Reapplyclusterconfig(nodeExtIdParam, overrideNsxOwnershipParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reapplyclusterconfig", reflect.TypeOf((*MockDiscoveredNodesClient)(nil).Reapplyclusterconfig), nodeExtIdParam, overrideNsxOwnershipParam)
}
