// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/locale_services/MulticastClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockMulticastClient is a mock of MulticastClient interface.
type MockMulticastClient struct {
	ctrl     *gomock.Controller
	recorder *MockMulticastClientMockRecorder
}

// MockMulticastClientMockRecorder is the mock recorder for MockMulticastClient.
type MockMulticastClientMockRecorder struct {
	mock *MockMulticastClient
}

// NewMockMulticastClient creates a new mock instance.
func NewMockMulticastClient(ctrl *gomock.Controller) *MockMulticastClient {
	mock := &MockMulticastClient{ctrl: ctrl}
	mock.recorder = &MockMulticastClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMulticastClient) EXPECT() *MockMulticastClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMulticastClient) Get(tier0IdParam, localeServicesIdParam string) (model.PolicyMulticastConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier0IdParam, localeServicesIdParam)
	ret0, _ := ret[0].(model.PolicyMulticastConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMulticastClientMockRecorder) Get(tier0IdParam, localeServicesIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMulticastClient)(nil).Get), tier0IdParam, localeServicesIdParam)
}

// Patch mocks base method.
func (m *MockMulticastClient) Patch(tier0IdParam, localeServicesIdParam string, policyMulticastConfigParam model.PolicyMulticastConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier0IdParam, localeServicesIdParam, policyMulticastConfigParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockMulticastClientMockRecorder) Patch(tier0IdParam, localeServicesIdParam, policyMulticastConfigParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockMulticastClient)(nil).Patch), tier0IdParam, localeServicesIdParam, policyMulticastConfigParam)
}

// Update mocks base method.
func (m *MockMulticastClient) Update(tier0IdParam, localeServicesIdParam string, policyMulticastConfigParam model.PolicyMulticastConfig) (model.PolicyMulticastConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier0IdParam, localeServicesIdParam, policyMulticastConfigParam)
	ret0, _ := ret[0].(model.PolicyMulticastConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMulticastClientMockRecorder) Update(tier0IdParam, localeServicesIdParam, policyMulticastConfigParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMulticastClient)(nil).Update), tier0IdParam, localeServicesIdParam, policyMulticastConfigParam)
}
