// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/settings/firewall/security/intrusion_services/signature_versions/SignaturesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/settings/firewall/security/intrusion_services/signature_versions/SignaturesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/settings/firewall/security/intrusion_services/signature_versions/SignaturesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSignaturesClient is a mock of SignaturesClient interface.
type MockSignaturesClient struct {
	ctrl     *gomock.Controller
	recorder *MockSignaturesClientMockRecorder
	isgomock struct{}
}

// MockSignaturesClientMockRecorder is the mock recorder for MockSignaturesClient.
type MockSignaturesClientMockRecorder struct {
	mock *MockSignaturesClient
}

// NewMockSignaturesClient creates a new mock instance.
func NewMockSignaturesClient(ctrl *gomock.Controller) *MockSignaturesClient {
	mock := &MockSignaturesClient{ctrl: ctrl}
	mock.recorder = &MockSignaturesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignaturesClient) EXPECT() *MockSignaturesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSignaturesClient) Get(versionIdParam, sigIdParam string) (model.IdsSignature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", versionIdParam, sigIdParam)
	ret0, _ := ret[0].(model.IdsSignature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSignaturesClientMockRecorder) Get(versionIdParam, sigIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSignaturesClient)(nil).Get), versionIdParam, sigIdParam)
}

// List mocks base method.
func (m *MockSignaturesClient) List(versionIdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.IdsSignatureListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", versionIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.IdsSignatureListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSignaturesClientMockRecorder) List(versionIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSignaturesClient)(nil).List), versionIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
