//nolint:revive
package transitgateways

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects/transit_gateways"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type TransitGatewayNatClientContext utl.ClientContext

func NewNatClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *TransitGatewayNatClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Multitenancy:
		client = client0.NewNatClient(connector)

	case utl.VPC:
		client = client0.NewNatClient(connector)

	default:
		return nil
	}
	return &TransitGatewayNatClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c TransitGatewayNatClientContext) Get(orgIdParam string, projectIdParam string, tgwIdParam string, natIdParam string) (model0.TransitGatewayNat, error) {
	var obj model0.TransitGatewayNat
	var err error

	switch c.ClientType {

	case utl.Multitenancy:
		client := c.Client.(client0.NatClient)
		obj, err = client.Get(orgIdParam, projectIdParam, tgwIdParam, natIdParam)
		if err != nil {
			return obj, err
		}

	case utl.VPC:
		client := c.Client.(client0.NatClient)
		obj, err = client.Get(orgIdParam, projectIdParam, tgwIdParam, natIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c TransitGatewayNatClientContext) List(orgIdParam string, projectIdParam string, tgwIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.TransitGatewayNatListResult, error) {
	var err error
	var obj model0.TransitGatewayNatListResult

	switch c.ClientType {

	case utl.Multitenancy:
		client := c.Client.(client0.NatClient)
		obj, err = client.List(orgIdParam, projectIdParam, tgwIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	case utl.VPC:
		client := c.Client.(client0.NatClient)
		obj, err = client.List(orgIdParam, projectIdParam, tgwIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
