//nolint:revive
package projects

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type CentralizedNetworkAttachmentClientContext utl.ClientContext

func NewCentralizedNetworkAttachmentsClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *CentralizedNetworkAttachmentClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Multitenancy, utl.VPC:
		client = client0.NewCentralizedNetworkAttachmentsClient(connector)

	default:
		return nil
	}
	return &CentralizedNetworkAttachmentClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c CentralizedNetworkAttachmentClientContext) Delete(orgIdParam string, projectIdParam string, cnaIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Multitenancy, utl.VPC:
		client := c.Client.(client0.CentralizedNetworkAttachmentsClient)
		err = client.Delete(orgIdParam, projectIdParam, cnaIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c CentralizedNetworkAttachmentClientContext) Get(orgIdParam string, projectIdParam string, cnaIdParam string) (model0.CentralizedNetworkAttachment, error) {
	var obj model0.CentralizedNetworkAttachment
	var err error

	switch c.ClientType {

	case utl.Multitenancy, utl.VPC:
		client := c.Client.(client0.CentralizedNetworkAttachmentsClient)
		obj, err = client.Get(orgIdParam, projectIdParam, cnaIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c CentralizedNetworkAttachmentClientContext) Patch(orgIdParam string, projectIdParam string, cnaIdParam string, cnaParam model0.CentralizedNetworkAttachment) error {
	var err error

	switch c.ClientType {

	case utl.Multitenancy, utl.VPC:
		client := c.Client.(client0.CentralizedNetworkAttachmentsClient)
		err = client.Patch(orgIdParam, projectIdParam, cnaIdParam, cnaParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c CentralizedNetworkAttachmentClientContext) Update(orgIdParam string, projectIdParam string, cnaIdParam string, cnaParam model0.CentralizedNetworkAttachment) (model0.CentralizedNetworkAttachment, error) {
	var obj model0.CentralizedNetworkAttachment
	var err error

	switch c.ClientType {

	case utl.Multitenancy, utl.VPC:
		client := c.Client.(client0.CentralizedNetworkAttachmentsClient)
		obj, err = client.Update(orgIdParam, projectIdParam, cnaIdParam, cnaParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}
