// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/domains/bridge_policies/RulesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockRulesClient is a mock of RulesClient interface.
type MockRulesClient struct {
	ctrl     *gomock.Controller
	recorder *MockRulesClientMockRecorder
}

// MockRulesClientMockRecorder is the mock recorder for MockRulesClient.
type MockRulesClientMockRecorder struct {
	mock *MockRulesClient
}

// NewMockRulesClient creates a new mock instance.
func NewMockRulesClient(ctrl *gomock.Controller) *MockRulesClient {
	mock := &MockRulesClient{ctrl: ctrl}
	mock.recorder = &MockRulesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRulesClient) EXPECT() *MockRulesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRulesClient) Create(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam string, ruleParam model.Rule) (model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam)
	ret0, _ := ret[0].(model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRulesClientMockRecorder) Create(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRulesClient)(nil).Create), domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam)
}

// Delete mocks base method.
func (m *MockRulesClient) Delete(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRulesClientMockRecorder) Delete(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRulesClient)(nil).Delete), domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam)
}

// Get mocks base method.
func (m *MockRulesClient) Get(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam string) (model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam)
	ret0, _ := ret[0].(model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRulesClientMockRecorder) Get(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRulesClient)(nil).Get), domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam)
}

// List mocks base method.
func (m *MockRulesClient) List(domainIdParam, bridgeFirewallPolicyIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.RuleListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", domainIdParam, bridgeFirewallPolicyIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.RuleListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRulesClientMockRecorder) List(domainIdParam, bridgeFirewallPolicyIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRulesClient)(nil).List), domainIdParam, bridgeFirewallPolicyIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockRulesClient) Patch(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam string, ruleParam model.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockRulesClientMockRecorder) Patch(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockRulesClient)(nil).Patch), domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam)
}

// Update mocks base method.
func (m *MockRulesClient) Update(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam string, ruleParam model.Rule) (model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam)
	ret0, _ := ret[0].(model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRulesClientMockRecorder) Update(domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRulesClient)(nil).Update), domainIdParam, bridgeFirewallPolicyIdParam, ruleIdParam, ruleParam)
}
