//nolint:revive
package localeservices

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_0s/locale_services"
	model1 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/model"
	client1 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/locale_services"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type BgpRoutingConfigClientContext utl.ClientContext

func NewBgpClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *BgpRoutingConfigClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Global:
		client = client0.NewBgpClient(connector)

	case utl.Local:
		client = client1.NewBgpClient(connector)

	default:
		return nil
	}
	return &BgpRoutingConfigClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c BgpRoutingConfigClientContext) Get(tier0IdParam string, localeServiceIdParam string) (model0.BgpRoutingConfig, error) {
	var obj model0.BgpRoutingConfig
	var err error

	switch c.ClientType {

	case utl.Global:
		client := c.Client.(client0.BgpClient)
		gmObj, err1 := client.Get(tier0IdParam, localeServiceIdParam)
		if err1 != nil {
			return obj, err1
		}
		var rawObj interface{}
		rawObj, err = utl.ConvertModelBindingType(gmObj, model1.BgpRoutingConfigBindingType(), model0.BgpRoutingConfigBindingType())
		obj = rawObj.(model0.BgpRoutingConfig)

	case utl.Local:
		client := c.Client.(client1.BgpClient)
		obj, err = client.Get(tier0IdParam, localeServiceIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c BgpRoutingConfigClientContext) Patch(tier0IdParam string, localeServiceIdParam string, bgpRoutingConfigParam model0.BgpRoutingConfig, overrideParam *bool) error {
	var err error

	switch c.ClientType {

	case utl.Global:
		client := c.Client.(client0.BgpClient)
		gmObj, err1 := utl.ConvertModelBindingType(bgpRoutingConfigParam, model0.BgpRoutingConfigBindingType(), model1.BgpRoutingConfigBindingType())
		if err1 != nil {
			return err1
		}
		err = client.Patch(tier0IdParam, localeServiceIdParam, gmObj.(model1.BgpRoutingConfig), overrideParam)

	case utl.Local:
		client := c.Client.(client1.BgpClient)
		err = client.Patch(tier0IdParam, localeServiceIdParam, bgpRoutingConfigParam, overrideParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c BgpRoutingConfigClientContext) Update(tier0IdParam string, localeServiceIdParam string, bgpRoutingConfigParam model0.BgpRoutingConfig, overrideParam *bool) (model0.BgpRoutingConfig, error) {
	var err error
	var obj model0.BgpRoutingConfig

	switch c.ClientType {

	case utl.Global:
		client := c.Client.(client0.BgpClient)
		gmObj, err := utl.ConvertModelBindingType(bgpRoutingConfigParam, model0.BgpRoutingConfigBindingType(), model1.BgpRoutingConfigBindingType())
		if err != nil {
			return obj, err
		}
		gmObj, err = client.Update(tier0IdParam, localeServiceIdParam, gmObj.(model1.BgpRoutingConfig), overrideParam)
		if err != nil {
			return obj, err
		}
		obj1, err1 := utl.ConvertModelBindingType(gmObj, model1.BgpRoutingConfigBindingType(), model0.BgpRoutingConfigBindingType())
		if err1 != nil {
			return obj, err1
		}
		obj = obj1.(model0.BgpRoutingConfig)

	case utl.Local:
		client := c.Client.(client1.BgpClient)
		obj, err = client.Update(tier0IdParam, localeServiceIdParam, bgpRoutingConfigParam, overrideParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c BgpRoutingConfigClientContext) Delete(bfdProfileIdParam string, localeServiceIdParam string, overrideParam *bool) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client1.BgpClient)
		err = client.Delete(bfdProfileIdParam, localeServiceIdParam, overrideParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}
