//nolint:revive
package l2vpnservices

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/l2vpn_services"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type L2VPNSessionClientContext utl.ClientContext

func NewSessionsClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *L2VPNSessionClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewSessionsClient(connector)

	default:
		return nil
	}
	return &L2VPNSessionClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c L2VPNSessionClientContext) Createwithpeercode(tier1IdParam string, serviceIdParam string, sessionIdParam string, l2VPNSessionDataParam model0.L2VPNSessionData) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.SessionsClient)
		err = client.Createwithpeercode(tier1IdParam, serviceIdParam, sessionIdParam, l2VPNSessionDataParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c L2VPNSessionClientContext) Delete(tier1IdParam string, serviceIdParam string, sessionIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.SessionsClient)
		err = client.Delete(tier1IdParam, serviceIdParam, sessionIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c L2VPNSessionClientContext) Get(tier1IdParam string, serviceIdParam string, sessionIdParam string) (model0.L2VPNSession, error) {
	var obj model0.L2VPNSession
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.SessionsClient)
		obj, err = client.Get(tier1IdParam, serviceIdParam, sessionIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c L2VPNSessionClientContext) List(tier1IdParam string, serviceIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.L2VPNSessionListResult, error) {
	var err error
	var obj model0.L2VPNSessionListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.SessionsClient)
		obj, err = client.List(tier1IdParam, serviceIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c L2VPNSessionClientContext) Patch(tier1IdParam string, serviceIdParam string, sessionIdParam string, l2VPNSessionParam model0.L2VPNSession) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.SessionsClient)
		err = client.Patch(tier1IdParam, serviceIdParam, sessionIdParam, l2VPNSessionParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c L2VPNSessionClientContext) Update(tier1IdParam string, serviceIdParam string, sessionIdParam string, l2VPNSessionParam model0.L2VPNSession) (model0.L2VPNSession, error) {
	var err error
	var obj model0.L2VPNSession

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.SessionsClient)
		obj, err = client.Update(tier1IdParam, serviceIdParam, sessionIdParam, l2VPNSessionParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
