// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/domains/groups/FirewallFloodProtectionProfileBindingMapsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockFirewallFloodProtectionProfileBindingMapsClient is a mock of FirewallFloodProtectionProfileBindingMapsClient interface.
type MockFirewallFloodProtectionProfileBindingMapsClient struct {
	ctrl     *gomock.Controller
	recorder *MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder
}

// MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder is the mock recorder for MockFirewallFloodProtectionProfileBindingMapsClient.
type MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder struct {
	mock *MockFirewallFloodProtectionProfileBindingMapsClient
}

// NewMockFirewallFloodProtectionProfileBindingMapsClient creates a new mock instance.
func NewMockFirewallFloodProtectionProfileBindingMapsClient(ctrl *gomock.Controller) *MockFirewallFloodProtectionProfileBindingMapsClient {
	mock := &MockFirewallFloodProtectionProfileBindingMapsClient{ctrl: ctrl}
	mock.recorder = &MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirewallFloodProtectionProfileBindingMapsClient) EXPECT() *MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFirewallFloodProtectionProfileBindingMapsClient) Delete(domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder) Delete(domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFirewallFloodProtectionProfileBindingMapsClient)(nil).Delete), domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam)
}

// Get mocks base method.
func (m *MockFirewallFloodProtectionProfileBindingMapsClient) Get(domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam string) (model.PolicyFirewallFloodProtectionProfileBindingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam)
	ret0, _ := ret[0].(model.PolicyFirewallFloodProtectionProfileBindingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder) Get(domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFirewallFloodProtectionProfileBindingMapsClient)(nil).Get), domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam)
}

// List mocks base method.
func (m *MockFirewallFloodProtectionProfileBindingMapsClient) List(domainIdParam, groupIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyFirewallFloodProtectionProfileBindingMapListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", domainIdParam, groupIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyFirewallFloodProtectionProfileBindingMapListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder) List(domainIdParam, groupIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFirewallFloodProtectionProfileBindingMapsClient)(nil).List), domainIdParam, groupIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockFirewallFloodProtectionProfileBindingMapsClient) Patch(domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam string, policyFirewallFloodProtectionProfileBindingMapParam model.PolicyFirewallFloodProtectionProfileBindingMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam, policyFirewallFloodProtectionProfileBindingMapParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder) Patch(domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam, policyFirewallFloodProtectionProfileBindingMapParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockFirewallFloodProtectionProfileBindingMapsClient)(nil).Patch), domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam, policyFirewallFloodProtectionProfileBindingMapParam)
}

// Update mocks base method.
func (m *MockFirewallFloodProtectionProfileBindingMapsClient) Update(domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam string, policyFirewallFloodProtectionProfileBindingMapParam model.PolicyFirewallFloodProtectionProfileBindingMap) (model.PolicyFirewallFloodProtectionProfileBindingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam, policyFirewallFloodProtectionProfileBindingMapParam)
	ret0, _ := ret[0].(model.PolicyFirewallFloodProtectionProfileBindingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFirewallFloodProtectionProfileBindingMapsClientMockRecorder) Update(domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam, policyFirewallFloodProtectionProfileBindingMapParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFirewallFloodProtectionProfileBindingMapsClient)(nil).Update), domainIdParam, groupIdParam, firewallFloodProtectionProfileBindingMapIdParam, policyFirewallFloodProtectionProfileBindingMapParam)
}
