// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/domains/groups/GroupMonitoringProfileBindingMapsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockGroupMonitoringProfileBindingMapsClient is a mock of GroupMonitoringProfileBindingMapsClient interface.
type MockGroupMonitoringProfileBindingMapsClient struct {
	ctrl     *gomock.Controller
	recorder *MockGroupMonitoringProfileBindingMapsClientMockRecorder
}

// MockGroupMonitoringProfileBindingMapsClientMockRecorder is the mock recorder for MockGroupMonitoringProfileBindingMapsClient.
type MockGroupMonitoringProfileBindingMapsClientMockRecorder struct {
	mock *MockGroupMonitoringProfileBindingMapsClient
}

// NewMockGroupMonitoringProfileBindingMapsClient creates a new mock instance.
func NewMockGroupMonitoringProfileBindingMapsClient(ctrl *gomock.Controller) *MockGroupMonitoringProfileBindingMapsClient {
	mock := &MockGroupMonitoringProfileBindingMapsClient{ctrl: ctrl}
	mock.recorder = &MockGroupMonitoringProfileBindingMapsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupMonitoringProfileBindingMapsClient) EXPECT() *MockGroupMonitoringProfileBindingMapsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockGroupMonitoringProfileBindingMapsClient) Delete(domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupMonitoringProfileBindingMapsClientMockRecorder) Delete(domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupMonitoringProfileBindingMapsClient)(nil).Delete), domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam)
}

// Get mocks base method.
func (m *MockGroupMonitoringProfileBindingMapsClient) Get(domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam string) (model.GroupMonitoringProfileBindingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam)
	ret0, _ := ret[0].(model.GroupMonitoringProfileBindingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGroupMonitoringProfileBindingMapsClientMockRecorder) Get(domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupMonitoringProfileBindingMapsClient)(nil).Get), domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam)
}

// List mocks base method.
func (m *MockGroupMonitoringProfileBindingMapsClient) List(domainIdParam, groupIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.GroupMonitoringProfileBindingMapListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", domainIdParam, groupIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.GroupMonitoringProfileBindingMapListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGroupMonitoringProfileBindingMapsClientMockRecorder) List(domainIdParam, groupIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupMonitoringProfileBindingMapsClient)(nil).List), domainIdParam, groupIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockGroupMonitoringProfileBindingMapsClient) Patch(domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam string, groupMonitoringProfileBindingMapParam model.GroupMonitoringProfileBindingMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam, groupMonitoringProfileBindingMapParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockGroupMonitoringProfileBindingMapsClientMockRecorder) Patch(domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam, groupMonitoringProfileBindingMapParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockGroupMonitoringProfileBindingMapsClient)(nil).Patch), domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam, groupMonitoringProfileBindingMapParam)
}

// Update mocks base method.
func (m *MockGroupMonitoringProfileBindingMapsClient) Update(domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam string, groupMonitoringProfileBindingMapParam model.GroupMonitoringProfileBindingMap) (model.GroupMonitoringProfileBindingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam, groupMonitoringProfileBindingMapParam)
	ret0, _ := ret[0].(model.GroupMonitoringProfileBindingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGroupMonitoringProfileBindingMapsClientMockRecorder) Update(domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam, groupMonitoringProfileBindingMapParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupMonitoringProfileBindingMapsClient)(nil).Update), domainIdParam, groupIdParam, groupMonitoringProfileBindingMapIdParam, groupMonitoringProfileBindingMapParam)
}
