// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/domains/groups/MacAddressExpressionsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockMacAddressExpressionsClient is a mock of MacAddressExpressionsClient interface.
type MockMacAddressExpressionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockMacAddressExpressionsClientMockRecorder
}

// MockMacAddressExpressionsClientMockRecorder is the mock recorder for MockMacAddressExpressionsClient.
type MockMacAddressExpressionsClientMockRecorder struct {
	mock *MockMacAddressExpressionsClient
}

// NewMockMacAddressExpressionsClient creates a new mock instance.
func NewMockMacAddressExpressionsClient(ctrl *gomock.Controller) *MockMacAddressExpressionsClient {
	mock := &MockMacAddressExpressionsClient{ctrl: ctrl}
	mock.recorder = &MockMacAddressExpressionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMacAddressExpressionsClient) EXPECT() *MockMacAddressExpressionsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMacAddressExpressionsClient) Create(domainIdParam, groupIdParam, expressionIdParam string, mACAddressListParam model.MACAddressList, actionParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", domainIdParam, groupIdParam, expressionIdParam, mACAddressListParam, actionParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMacAddressExpressionsClientMockRecorder) Create(domainIdParam, groupIdParam, expressionIdParam, mACAddressListParam, actionParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMacAddressExpressionsClient)(nil).Create), domainIdParam, groupIdParam, expressionIdParam, mACAddressListParam, actionParam)
}

// Delete mocks base method.
func (m *MockMacAddressExpressionsClient) Delete(domainIdParam, groupIdParam, expressionIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", domainIdParam, groupIdParam, expressionIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMacAddressExpressionsClientMockRecorder) Delete(domainIdParam, groupIdParam, expressionIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMacAddressExpressionsClient)(nil).Delete), domainIdParam, groupIdParam, expressionIdParam)
}

// Patch mocks base method.
func (m *MockMacAddressExpressionsClient) Patch(domainIdParam, groupIdParam, expressionIdParam string, mACAddressExpressionParam model.MACAddressExpression) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", domainIdParam, groupIdParam, expressionIdParam, mACAddressExpressionParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockMacAddressExpressionsClientMockRecorder) Patch(domainIdParam, groupIdParam, expressionIdParam, mACAddressExpressionParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockMacAddressExpressionsClient)(nil).Patch), domainIdParam, groupIdParam, expressionIdParam, mACAddressExpressionParam)
}
