// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/segments/ArpTableClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockArpTableClient is a mock of ArpTableClient interface.
type MockArpTableClient struct {
	ctrl     *gomock.Controller
	recorder *MockArpTableClientMockRecorder
}

// MockArpTableClientMockRecorder is the mock recorder for MockArpTableClient.
type MockArpTableClientMockRecorder struct {
	mock *MockArpTableClient
}

// NewMockArpTableClient creates a new mock instance.
func NewMockArpTableClient(ctrl *gomock.Controller) *MockArpTableClient {
	mock := &MockArpTableClient{ctrl: ctrl}
	mock.recorder = &MockArpTableClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArpTableClient) EXPECT() *MockArpTableClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockArpTableClient) List(segmentIdParam string, cursorParam, edgePathParam, enforcementPointPathParam, hostTransportNodePathParam, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.InterfaceArpTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", segmentIdParam, cursorParam, edgePathParam, enforcementPointPathParam, hostTransportNodePathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.InterfaceArpTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockArpTableClientMockRecorder) List(segmentIdParam, cursorParam, edgePathParam, enforcementPointPathParam, hostTransportNodePathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockArpTableClient)(nil).List), segmentIdParam, cursorParam, edgePathParam, enforcementPointPathParam, hostTransportNodePathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
