// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/segments/SegmentDiscoveryProfileBindingMapsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockSegmentDiscoveryProfileBindingMapsClient is a mock of SegmentDiscoveryProfileBindingMapsClient interface.
type MockSegmentDiscoveryProfileBindingMapsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentDiscoveryProfileBindingMapsClientMockRecorder
}

// MockSegmentDiscoveryProfileBindingMapsClientMockRecorder is the mock recorder for MockSegmentDiscoveryProfileBindingMapsClient.
type MockSegmentDiscoveryProfileBindingMapsClientMockRecorder struct {
	mock *MockSegmentDiscoveryProfileBindingMapsClient
}

// NewMockSegmentDiscoveryProfileBindingMapsClient creates a new mock instance.
func NewMockSegmentDiscoveryProfileBindingMapsClient(ctrl *gomock.Controller) *MockSegmentDiscoveryProfileBindingMapsClient {
	mock := &MockSegmentDiscoveryProfileBindingMapsClient{ctrl: ctrl}
	mock.recorder = &MockSegmentDiscoveryProfileBindingMapsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentDiscoveryProfileBindingMapsClient) EXPECT() *MockSegmentDiscoveryProfileBindingMapsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSegmentDiscoveryProfileBindingMapsClient) Delete(infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSegmentDiscoveryProfileBindingMapsClientMockRecorder) Delete(infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSegmentDiscoveryProfileBindingMapsClient)(nil).Delete), infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam)
}

// Get mocks base method.
func (m *MockSegmentDiscoveryProfileBindingMapsClient) Get(infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam string) (model.SegmentDiscoveryProfileBindingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam)
	ret0, _ := ret[0].(model.SegmentDiscoveryProfileBindingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSegmentDiscoveryProfileBindingMapsClientMockRecorder) Get(infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSegmentDiscoveryProfileBindingMapsClient)(nil).Get), infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam)
}

// List mocks base method.
func (m *MockSegmentDiscoveryProfileBindingMapsClient) List(infraSegmentIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.SegmentDiscoveryProfileBindingMapListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", infraSegmentIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.SegmentDiscoveryProfileBindingMapListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSegmentDiscoveryProfileBindingMapsClientMockRecorder) List(infraSegmentIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSegmentDiscoveryProfileBindingMapsClient)(nil).List), infraSegmentIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockSegmentDiscoveryProfileBindingMapsClient) Patch(infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam string, segmentDiscoveryProfileBindingMapParam model.SegmentDiscoveryProfileBindingMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam, segmentDiscoveryProfileBindingMapParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockSegmentDiscoveryProfileBindingMapsClientMockRecorder) Patch(infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam, segmentDiscoveryProfileBindingMapParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockSegmentDiscoveryProfileBindingMapsClient)(nil).Patch), infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam, segmentDiscoveryProfileBindingMapParam)
}

// Update mocks base method.
func (m *MockSegmentDiscoveryProfileBindingMapsClient) Update(infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam string, segmentDiscoveryProfileBindingMapParam model.SegmentDiscoveryProfileBindingMap) (model.SegmentDiscoveryProfileBindingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam, segmentDiscoveryProfileBindingMapParam)
	ret0, _ := ret[0].(model.SegmentDiscoveryProfileBindingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSegmentDiscoveryProfileBindingMapsClientMockRecorder) Update(infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam, segmentDiscoveryProfileBindingMapParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSegmentDiscoveryProfileBindingMapsClient)(nil).Update), infraSegmentIdParam, segmentDiscoveryProfileBindingMapIdParam, segmentDiscoveryProfileBindingMapParam)
}
