// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/segments/ServiceSegmentsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockServiceSegmentsClient is a mock of ServiceSegmentsClient interface.
type MockServiceSegmentsClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceSegmentsClientMockRecorder
}

// MockServiceSegmentsClientMockRecorder is the mock recorder for MockServiceSegmentsClient.
type MockServiceSegmentsClientMockRecorder struct {
	mock *MockServiceSegmentsClient
}

// NewMockServiceSegmentsClient creates a new mock instance.
func NewMockServiceSegmentsClient(ctrl *gomock.Controller) *MockServiceSegmentsClient {
	mock := &MockServiceSegmentsClient{ctrl: ctrl}
	mock.recorder = &MockServiceSegmentsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceSegmentsClient) EXPECT() *MockServiceSegmentsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockServiceSegmentsClient) Delete(serviceSegmentIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", serviceSegmentIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceSegmentsClientMockRecorder) Delete(serviceSegmentIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceSegmentsClient)(nil).Delete), serviceSegmentIdParam)
}

// Get mocks base method.
func (m *MockServiceSegmentsClient) Get(serviceSegmentIdParam string) (model.ServiceSegment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", serviceSegmentIdParam)
	ret0, _ := ret[0].(model.ServiceSegment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceSegmentsClientMockRecorder) Get(serviceSegmentIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceSegmentsClient)(nil).Get), serviceSegmentIdParam)
}

// List mocks base method.
func (m *MockServiceSegmentsClient) List(cursorParam, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.ServiceSegmentListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.ServiceSegmentListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceSegmentsClientMockRecorder) List(cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceSegmentsClient)(nil).List), cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockServiceSegmentsClient) Patch(serviceSegmentIdParam string, serviceSegmentParam model.ServiceSegment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", serviceSegmentIdParam, serviceSegmentParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockServiceSegmentsClientMockRecorder) Patch(serviceSegmentIdParam, serviceSegmentParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockServiceSegmentsClient)(nil).Patch), serviceSegmentIdParam, serviceSegmentParam)
}

// Update mocks base method.
func (m *MockServiceSegmentsClient) Update(serviceSegmentIdParam string, serviceSegmentParam model.ServiceSegment) (model.ServiceSegment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", serviceSegmentIdParam, serviceSegmentParam)
	ret0, _ := ret[0].(model.ServiceSegment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceSegmentsClientMockRecorder) Update(serviceSegmentIdParam, serviceSegmentParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceSegmentsClient)(nil).Update), serviceSegmentIdParam, serviceSegmentParam)
}
