// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/locale_services/multicast/ForwardingClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockForwardingClient is a mock of ForwardingClient interface.
type MockForwardingClient struct {
	ctrl     *gomock.Controller
	recorder *MockForwardingClientMockRecorder
}

// MockForwardingClientMockRecorder is the mock recorder for MockForwardingClient.
type MockForwardingClientMockRecorder struct {
	mock *MockForwardingClient
}

// NewMockForwardingClient creates a new mock instance.
func NewMockForwardingClient(ctrl *gomock.Controller) *MockForwardingClient {
	mock := &MockForwardingClient{ctrl: ctrl}
	mock.recorder = &MockForwardingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForwardingClient) EXPECT() *MockForwardingClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockForwardingClient) List(tier1IdParam, localeServicesIdParam string, cursorParam, edgePathParam, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyMulticastForwarding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier1IdParam, localeServicesIdParam, cursorParam, edgePathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyMulticastForwarding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockForwardingClientMockRecorder) List(tier1IdParam, localeServicesIdParam, cursorParam, edgePathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockForwardingClient)(nil).List), tier1IdParam, localeServicesIdParam, cursorParam, edgePathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
