// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/domains/endpoint_policies/EndpointRulesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockEndpointRulesClient is a mock of EndpointRulesClient interface.
type MockEndpointRulesClient struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointRulesClientMockRecorder
}

// MockEndpointRulesClientMockRecorder is the mock recorder for MockEndpointRulesClient.
type MockEndpointRulesClientMockRecorder struct {
	mock *MockEndpointRulesClient
}

// NewMockEndpointRulesClient creates a new mock instance.
func NewMockEndpointRulesClient(ctrl *gomock.Controller) *MockEndpointRulesClient {
	mock := &MockEndpointRulesClient{ctrl: ctrl}
	mock.recorder = &MockEndpointRulesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointRulesClient) EXPECT() *MockEndpointRulesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockEndpointRulesClient) Delete(domainIdParam, endpointPolicyIdParam, endpointRuleIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", domainIdParam, endpointPolicyIdParam, endpointRuleIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEndpointRulesClientMockRecorder) Delete(domainIdParam, endpointPolicyIdParam, endpointRuleIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEndpointRulesClient)(nil).Delete), domainIdParam, endpointPolicyIdParam, endpointRuleIdParam)
}

// Get mocks base method.
func (m *MockEndpointRulesClient) Get(domainIdParam, endpointPolicyIdParam, endpointRuleIdParam string) (model.EndpointRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", domainIdParam, endpointPolicyIdParam, endpointRuleIdParam)
	ret0, _ := ret[0].(model.EndpointRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEndpointRulesClientMockRecorder) Get(domainIdParam, endpointPolicyIdParam, endpointRuleIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEndpointRulesClient)(nil).Get), domainIdParam, endpointPolicyIdParam, endpointRuleIdParam)
}

// List mocks base method.
func (m *MockEndpointRulesClient) List(domainIdParam, endpointPolicyIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.EndpointRuleListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", domainIdParam, endpointPolicyIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.EndpointRuleListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEndpointRulesClientMockRecorder) List(domainIdParam, endpointPolicyIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEndpointRulesClient)(nil).List), domainIdParam, endpointPolicyIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockEndpointRulesClient) Patch(domainIdParam, endpointPolicyIdParam, endpointRuleIdParam string, endpointRuleParam model.EndpointRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", domainIdParam, endpointPolicyIdParam, endpointRuleIdParam, endpointRuleParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockEndpointRulesClientMockRecorder) Patch(domainIdParam, endpointPolicyIdParam, endpointRuleIdParam, endpointRuleParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockEndpointRulesClient)(nil).Patch), domainIdParam, endpointPolicyIdParam, endpointRuleIdParam, endpointRuleParam)
}

// Update mocks base method.
func (m *MockEndpointRulesClient) Update(domainIdParam, endpointPolicyIdParam, endpointRuleIdParam string, endpointRuleParam model.EndpointRule) (model.EndpointRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", domainIdParam, endpointPolicyIdParam, endpointRuleIdParam, endpointRuleParam)
	ret0, _ := ret[0].(model.EndpointRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEndpointRulesClientMockRecorder) Update(domainIdParam, endpointPolicyIdParam, endpointRuleIdParam, endpointRuleParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEndpointRulesClient)(nil).Update), domainIdParam, endpointPolicyIdParam, endpointRuleIdParam, endpointRuleParam)
}
