// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/sites/napp/deployment/upgrade_coordinator/VersionsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockVersionsClient is a mock of VersionsClient interface.
type MockVersionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockVersionsClientMockRecorder
}

// MockVersionsClientMockRecorder is the mock recorder for MockVersionsClient.
type MockVersionsClientMockRecorder struct {
	mock *MockVersionsClient
}

// NewMockVersionsClient creates a new mock instance.
func NewMockVersionsClient(ctrl *gomock.Controller) *MockVersionsClient {
	mock := &MockVersionsClient{ctrl: ctrl}
	mock.recorder = &MockVersionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionsClient) EXPECT() *MockVersionsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVersionsClient) Get(siteIdParam string) (model.DeploymentVersions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", siteIdParam)
	ret0, _ := ret[0].(model.DeploymentVersions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVersionsClientMockRecorder) Get(siteIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVersionsClient)(nil).Get), siteIdParam)
}
