// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/GatewayFirewallClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockGatewayFirewallClient is a mock of GatewayFirewallClient interface.
type MockGatewayFirewallClient struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayFirewallClientMockRecorder
}

// MockGatewayFirewallClientMockRecorder is the mock recorder for MockGatewayFirewallClient.
type MockGatewayFirewallClientMockRecorder struct {
	mock *MockGatewayFirewallClient
}

// NewMockGatewayFirewallClient creates a new mock instance.
func NewMockGatewayFirewallClient(ctrl *gomock.Controller) *MockGatewayFirewallClient {
	mock := &MockGatewayFirewallClient{ctrl: ctrl}
	mock.recorder = &MockGatewayFirewallClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayFirewallClient) EXPECT() *MockGatewayFirewallClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockGatewayFirewallClient) List(tier1IdParam string) (model.GatewayPolicyListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier1IdParam)
	ret0, _ := ret[0].(model.GatewayPolicyListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGatewayFirewallClientMockRecorder) List(tier1IdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGatewayFirewallClient)(nil).List), tier1IdParam)
}
