// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/SegmentsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockSegmentsClient is a mock of SegmentsClient interface.
type MockSegmentsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentsClientMockRecorder
}

// MockSegmentsClientMockRecorder is the mock recorder for MockSegmentsClient.
type MockSegmentsClientMockRecorder struct {
	mock *MockSegmentsClient
}

// NewMockSegmentsClient creates a new mock instance.
func NewMockSegmentsClient(ctrl *gomock.Controller) *MockSegmentsClient {
	mock := &MockSegmentsClient{ctrl: ctrl}
	mock.recorder = &MockSegmentsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentsClient) EXPECT() *MockSegmentsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSegmentsClient) Delete(tier1IdParam, segmentIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tier1IdParam, segmentIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSegmentsClientMockRecorder) Delete(tier1IdParam, segmentIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSegmentsClient)(nil).Delete), tier1IdParam, segmentIdParam)
}

// Delete0 mocks base method.
func (m *MockSegmentsClient) Delete0(tier1IdParam, segmentIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete0", tier1IdParam, segmentIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete0 indicates an expected call of Delete0.
func (mr *MockSegmentsClientMockRecorder) Delete0(tier1IdParam, segmentIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete0", reflect.TypeOf((*MockSegmentsClient)(nil).Delete0), tier1IdParam, segmentIdParam)
}

// Deletedhcpleases mocks base method.
func (m *MockSegmentsClient) Deletedhcpleases(tier1IdParam, segmentIdParam string, dhcpDeleteLeasesParam model.DhcpDeleteLeases, enforcementPointPathParam *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deletedhcpleases", tier1IdParam, segmentIdParam, dhcpDeleteLeasesParam, enforcementPointPathParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deletedhcpleases indicates an expected call of Deletedhcpleases.
func (mr *MockSegmentsClientMockRecorder) Deletedhcpleases(tier1IdParam, segmentIdParam, dhcpDeleteLeasesParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deletedhcpleases", reflect.TypeOf((*MockSegmentsClient)(nil).Deletedhcpleases), tier1IdParam, segmentIdParam, dhcpDeleteLeasesParam, enforcementPointPathParam)
}

// Get mocks base method.
func (m *MockSegmentsClient) Get(tier1IdParam, segmentIdParam string) (model.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier1IdParam, segmentIdParam)
	ret0, _ := ret[0].(model.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSegmentsClientMockRecorder) Get(tier1IdParam, segmentIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSegmentsClient)(nil).Get), tier1IdParam, segmentIdParam)
}

// List mocks base method.
func (m *MockSegmentsClient) List(tier1IdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, segmentTypeParam *string, sortAscendingParam *bool, sortByParam *string) (model.SegmentListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier1IdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, segmentTypeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.SegmentListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSegmentsClientMockRecorder) List(tier1IdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, segmentTypeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSegmentsClient)(nil).List), tier1IdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, segmentTypeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockSegmentsClient) Patch(tier1IdParam, segmentIdParam string, segmentParam model.Segment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier1IdParam, segmentIdParam, segmentParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockSegmentsClientMockRecorder) Patch(tier1IdParam, segmentIdParam, segmentParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockSegmentsClient)(nil).Patch), tier1IdParam, segmentIdParam, segmentParam)
}

// Update mocks base method.
func (m *MockSegmentsClient) Update(tier1IdParam, segmentIdParam string, segmentParam model.Segment) (model.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier1IdParam, segmentIdParam, segmentParam)
	ret0, _ := ret[0].(model.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSegmentsClientMockRecorder) Update(tier1IdParam, segmentIdParam, segmentParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSegmentsClient)(nil).Update), tier1IdParam, segmentIdParam, segmentParam)
}
