// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/dhcp_server_configs/LeasesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockLeasesClient is a mock of LeasesClient interface.
type MockLeasesClient struct {
	ctrl     *gomock.Controller
	recorder *MockLeasesClientMockRecorder
}

// MockLeasesClientMockRecorder is the mock recorder for MockLeasesClient.
type MockLeasesClientMockRecorder struct {
	mock *MockLeasesClient
}

// NewMockLeasesClient creates a new mock instance.
func NewMockLeasesClient(ctrl *gomock.Controller) *MockLeasesClient {
	mock := &MockLeasesClient{ctrl: ctrl}
	mock.recorder = &MockLeasesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeasesClient) EXPECT() *MockLeasesClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockLeasesClient) List(configIdParam, connectivityPathParam string, addressParam, cursorParam, enforcementPointPathParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, segmentPathParam *string, sortAscendingParam *bool, sortByParam, sourceParam *string) (model.DhcpLeasesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", configIdParam, connectivityPathParam, addressParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, segmentPathParam, sortAscendingParam, sortByParam, sourceParam)
	ret0, _ := ret[0].(model.DhcpLeasesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLeasesClientMockRecorder) List(configIdParam, connectivityPathParam, addressParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, segmentPathParam, sortAscendingParam, sortByParam, sourceParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLeasesClient)(nil).List), configIdParam, connectivityPathParam, addressParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, segmentPathParam, sortAscendingParam, sortByParam, sourceParam)
}
