// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/locale_services/InterfacesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockInterfacesClient is a mock of InterfacesClient interface.
type MockInterfacesClient struct {
	ctrl     *gomock.Controller
	recorder *MockInterfacesClientMockRecorder
}

// MockInterfacesClientMockRecorder is the mock recorder for MockInterfacesClient.
type MockInterfacesClientMockRecorder struct {
	mock *MockInterfacesClient
}

// NewMockInterfacesClient creates a new mock instance.
func NewMockInterfacesClient(ctrl *gomock.Controller) *MockInterfacesClient {
	mock := &MockInterfacesClient{ctrl: ctrl}
	mock.recorder = &MockInterfacesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterfacesClient) EXPECT() *MockInterfacesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockInterfacesClient) Delete(tier1IdParam, localeServicesIdParam, interfaceIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tier1IdParam, localeServicesIdParam, interfaceIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInterfacesClientMockRecorder) Delete(tier1IdParam, localeServicesIdParam, interfaceIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInterfacesClient)(nil).Delete), tier1IdParam, localeServicesIdParam, interfaceIdParam)
}

// Get mocks base method.
func (m *MockInterfacesClient) Get(tier1IdParam, localeServicesIdParam, interfaceIdParam string) (model.Tier1Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier1IdParam, localeServicesIdParam, interfaceIdParam)
	ret0, _ := ret[0].(model.Tier1Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInterfacesClientMockRecorder) Get(tier1IdParam, localeServicesIdParam, interfaceIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInterfacesClient)(nil).Get), tier1IdParam, localeServicesIdParam, interfaceIdParam)
}

// List mocks base method.
func (m *MockInterfacesClient) List(tier1IdParam, localeServicesIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.Tier1InterfaceListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier1IdParam, localeServicesIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.Tier1InterfaceListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInterfacesClientMockRecorder) List(tier1IdParam, localeServicesIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInterfacesClient)(nil).List), tier1IdParam, localeServicesIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockInterfacesClient) Patch(tier1IdParam, localeServicesIdParam, interfaceIdParam string, tier1InterfaceParam model.Tier1Interface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier1IdParam, localeServicesIdParam, interfaceIdParam, tier1InterfaceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockInterfacesClientMockRecorder) Patch(tier1IdParam, localeServicesIdParam, interfaceIdParam, tier1InterfaceParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockInterfacesClient)(nil).Patch), tier1IdParam, localeServicesIdParam, interfaceIdParam, tier1InterfaceParam)
}

// Update mocks base method.
func (m *MockInterfacesClient) Update(tier1IdParam, localeServicesIdParam, interfaceIdParam string, tier1InterfaceParam model.Tier1Interface) (model.Tier1Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier1IdParam, localeServicesIdParam, interfaceIdParam, tier1InterfaceParam)
	ret0, _ := ret[0].(model.Tier1Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInterfacesClientMockRecorder) Update(tier1IdParam, localeServicesIdParam, interfaceIdParam, tier1InterfaceParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInterfacesClient)(nil).Update), tier1IdParam, localeServicesIdParam, interfaceIdParam, tier1InterfaceParam)
}
