// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/tier_1s/locale_services/IpsecVpnServicesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/tier_1s/locale_services/IpsecVpnServicesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/tier_1s/locale_services/IpsecVpnServicesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIpsecVpnServicesClient is a mock of IpsecVpnServicesClient interface.
type MockIpsecVpnServicesClient struct {
	ctrl     *gomock.Controller
	recorder *MockIpsecVpnServicesClientMockRecorder
	isgomock struct{}
}

// MockIpsecVpnServicesClientMockRecorder is the mock recorder for MockIpsecVpnServicesClient.
type MockIpsecVpnServicesClientMockRecorder struct {
	mock *MockIpsecVpnServicesClient
}

// NewMockIpsecVpnServicesClient creates a new mock instance.
func NewMockIpsecVpnServicesClient(ctrl *gomock.Controller) *MockIpsecVpnServicesClient {
	mock := &MockIpsecVpnServicesClient{ctrl: ctrl}
	mock.recorder = &MockIpsecVpnServicesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpsecVpnServicesClient) EXPECT() *MockIpsecVpnServicesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIpsecVpnServicesClient) Delete(tier1IdParam, localeServiceIdParam, serviceIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tier1IdParam, localeServiceIdParam, serviceIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIpsecVpnServicesClientMockRecorder) Delete(tier1IdParam, localeServiceIdParam, serviceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIpsecVpnServicesClient)(nil).Delete), tier1IdParam, localeServiceIdParam, serviceIdParam)
}

// Get mocks base method.
func (m *MockIpsecVpnServicesClient) Get(tier1IdParam, localeServiceIdParam, serviceIdParam string) (model.IPSecVpnService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier1IdParam, localeServiceIdParam, serviceIdParam)
	ret0, _ := ret[0].(model.IPSecVpnService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIpsecVpnServicesClientMockRecorder) Get(tier1IdParam, localeServiceIdParam, serviceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIpsecVpnServicesClient)(nil).Get), tier1IdParam, localeServiceIdParam, serviceIdParam)
}

// List mocks base method.
func (m *MockIpsecVpnServicesClient) List(tier1IdParam, localeServiceIdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.IPSecVpnServiceListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier1IdParam, localeServiceIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.IPSecVpnServiceListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIpsecVpnServicesClientMockRecorder) List(tier1IdParam, localeServiceIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIpsecVpnServicesClient)(nil).List), tier1IdParam, localeServiceIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockIpsecVpnServicesClient) Patch(tier1IdParam, localeServiceIdParam, serviceIdParam string, ipSecVpnServiceParam model.IPSecVpnService) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier1IdParam, localeServiceIdParam, serviceIdParam, ipSecVpnServiceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockIpsecVpnServicesClientMockRecorder) Patch(tier1IdParam, localeServiceIdParam, serviceIdParam, ipSecVpnServiceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockIpsecVpnServicesClient)(nil).Patch), tier1IdParam, localeServiceIdParam, serviceIdParam, ipSecVpnServiceParam)
}

// Update mocks base method.
func (m *MockIpsecVpnServicesClient) Update(tier1IdParam, localeServiceIdParam, serviceIdParam string, ipSecVpnServiceParam model.IPSecVpnService) (model.IPSecVpnService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier1IdParam, localeServiceIdParam, serviceIdParam, ipSecVpnServiceParam)
	ret0, _ := ret[0].(model.IPSecVpnService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIpsecVpnServicesClientMockRecorder) Update(tier1IdParam, localeServiceIdParam, serviceIdParam, ipSecVpnServiceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIpsecVpnServicesClient)(nil).Update), tier1IdParam, localeServiceIdParam, serviceIdParam, ipSecVpnServiceParam)
}
