// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/tier_1s/locale_services/ServiceInterfacesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/tier_1s/locale_services/ServiceInterfacesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/tier_1s/locale_services/ServiceInterfacesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterfacesClient is a mock of ServiceInterfacesClient interface.
type MockServiceInterfacesClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfacesClientMockRecorder
	isgomock struct{}
}

// MockServiceInterfacesClientMockRecorder is the mock recorder for MockServiceInterfacesClient.
type MockServiceInterfacesClientMockRecorder struct {
	mock *MockServiceInterfacesClient
}

// NewMockServiceInterfacesClient creates a new mock instance.
func NewMockServiceInterfacesClient(ctrl *gomock.Controller) *MockServiceInterfacesClient {
	mock := &MockServiceInterfacesClient{ctrl: ctrl}
	mock.recorder = &MockServiceInterfacesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterfacesClient) EXPECT() *MockServiceInterfacesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockServiceInterfacesClient) Delete(tier1IdParam, localeServiceIdParam, interfaceIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tier1IdParam, localeServiceIdParam, interfaceIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceInterfacesClientMockRecorder) Delete(tier1IdParam, localeServiceIdParam, interfaceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceInterfacesClient)(nil).Delete), tier1IdParam, localeServiceIdParam, interfaceIdParam)
}

// Get mocks base method.
func (m *MockServiceInterfacesClient) Get(tier1IdParam, localeServiceIdParam, interfaceIdParam string) (model.ServiceInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier1IdParam, localeServiceIdParam, interfaceIdParam)
	ret0, _ := ret[0].(model.ServiceInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceInterfacesClientMockRecorder) Get(tier1IdParam, localeServiceIdParam, interfaceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceInterfacesClient)(nil).Get), tier1IdParam, localeServiceIdParam, interfaceIdParam)
}

// List mocks base method.
func (m *MockServiceInterfacesClient) List(tier1IdParam, localeServiceIdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.ServiceInterfaceListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier1IdParam, localeServiceIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.ServiceInterfaceListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceInterfacesClientMockRecorder) List(tier1IdParam, localeServiceIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceInterfacesClient)(nil).List), tier1IdParam, localeServiceIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockServiceInterfacesClient) Patch(tier1IdParam, localeServiceIdParam, interfaceIdParam string, serviceInterfaceParam model.ServiceInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier1IdParam, localeServiceIdParam, interfaceIdParam, serviceInterfaceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockServiceInterfacesClientMockRecorder) Patch(tier1IdParam, localeServiceIdParam, interfaceIdParam, serviceInterfaceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockServiceInterfacesClient)(nil).Patch), tier1IdParam, localeServiceIdParam, interfaceIdParam, serviceInterfaceParam)
}

// Update mocks base method.
func (m *MockServiceInterfacesClient) Update(tier1IdParam, localeServiceIdParam, interfaceIdParam string, serviceInterfaceParam model.ServiceInterface) (model.ServiceInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier1IdParam, localeServiceIdParam, interfaceIdParam, serviceInterfaceParam)
	ret0, _ := ret[0].(model.ServiceInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceInterfacesClientMockRecorder) Update(tier1IdParam, localeServiceIdParam, interfaceIdParam, serviceInterfaceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceInterfacesClient)(nil).Update), tier1IdParam, localeServiceIdParam, interfaceIdParam, serviceInterfaceParam)
}
