// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects/transit_gateways (interfaces: CommunityListsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockCommunityListsClient is a mock of CommunityListsClient interface.
type MockCommunityListsClient struct {
	ctrl     *gomock.Controller
	recorder *MockCommunityListsClientMockRecorder
}

// MockCommunityListsClientMockRecorder is the mock recorder for MockCommunityListsClient.
type MockCommunityListsClientMockRecorder struct {
	mock *MockCommunityListsClient
}

// NewMockCommunityListsClient creates a new mock instance.
func NewMockCommunityListsClient(ctrl *gomock.Controller) *MockCommunityListsClient {
	mock := &MockCommunityListsClient{ctrl: ctrl}
	mock.recorder = &MockCommunityListsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommunityListsClient) EXPECT() *MockCommunityListsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCommunityListsClient) Delete(orgIdParam string, projectIdParam string, transitGatewayIdParam string, communityListIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommunityListsClientMockRecorder) Delete(orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommunityListsClient)(nil).Delete), orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam)
}

// Get mocks base method.
func (m *MockCommunityListsClient) Get(orgIdParam string, projectIdParam string, transitGatewayIdParam string, communityListIdParam string) (model.CommunityList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam)
	ret0, _ := ret[0].(model.CommunityList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCommunityListsClientMockRecorder) Get(orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommunityListsClient)(nil).Get), orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam)
}

// List mocks base method.
func (m *MockCommunityListsClient) List(orgIdParam string, projectIdParam string, transitGatewayIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.TgwCommunityListListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", orgIdParam, projectIdParam, transitGatewayIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.TgwCommunityListListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCommunityListsClientMockRecorder) List(orgIdParam, projectIdParam, transitGatewayIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommunityListsClient)(nil).List), orgIdParam, projectIdParam, transitGatewayIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockCommunityListsClient) Patch(orgIdParam string, projectIdParam string, transitGatewayIdParam string, communityListIdParam string, communityListParam model.CommunityList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam, communityListParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockCommunityListsClientMockRecorder) Patch(orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam, communityListParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockCommunityListsClient)(nil).Patch), orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam, communityListParam)
}

// Update mocks base method.
func (m *MockCommunityListsClient) Update(orgIdParam string, projectIdParam string, transitGatewayIdParam string, communityListIdParam string, communityListParam model.CommunityList) (model.CommunityList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam, communityListParam)
	ret0, _ := ret[0].(model.CommunityList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommunityListsClientMockRecorder) Update(orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam, communityListParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommunityListsClient)(nil).Update), orgIdParam, projectIdParam, transitGatewayIdParam, communityListIdParam, communityListParam)
}
