// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects/transit_gateways (interfaces: PrefixListsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockPrefixListsClient is a mock of PrefixListsClient interface.
type MockPrefixListsClient struct {
	ctrl     *gomock.Controller
	recorder *MockPrefixListsClientMockRecorder
}

// MockPrefixListsClientMockRecorder is the mock recorder for MockPrefixListsClient.
type MockPrefixListsClientMockRecorder struct {
	mock *MockPrefixListsClient
}

// NewMockPrefixListsClient creates a new mock instance.
func NewMockPrefixListsClient(ctrl *gomock.Controller) *MockPrefixListsClient {
	mock := &MockPrefixListsClient{ctrl: ctrl}
	mock.recorder = &MockPrefixListsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrefixListsClient) EXPECT() *MockPrefixListsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPrefixListsClient) Delete(orgIdParam string, projectIdParam string, transitGatewayIdParam string, prefixListIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPrefixListsClientMockRecorder) Delete(orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPrefixListsClient)(nil).Delete), orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam)
}

// Get mocks base method.
func (m *MockPrefixListsClient) Get(orgIdParam string, projectIdParam string, transitGatewayIdParam string, prefixListIdParam string) (model.PrefixList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam)
	ret0, _ := ret[0].(model.PrefixList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPrefixListsClientMockRecorder) Get(orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPrefixListsClient)(nil).Get), orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam)
}

// List mocks base method.
func (m *MockPrefixListsClient) List(orgIdParam string, projectIdParam string, transitGatewayIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.TgwPrefixListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", orgIdParam, projectIdParam, transitGatewayIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.TgwPrefixListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPrefixListsClientMockRecorder) List(orgIdParam, projectIdParam, transitGatewayIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPrefixListsClient)(nil).List), orgIdParam, projectIdParam, transitGatewayIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockPrefixListsClient) Patch(orgIdParam string, projectIdParam string, transitGatewayIdParam string, prefixListIdParam string, prefixListParam model.PrefixList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam, prefixListParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockPrefixListsClientMockRecorder) Patch(orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam, prefixListParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockPrefixListsClient)(nil).Patch), orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam, prefixListParam)
}

// Update mocks base method.
func (m *MockPrefixListsClient) Update(orgIdParam string, projectIdParam string, transitGatewayIdParam string, prefixListIdParam string, prefixListParam model.PrefixList) (model.PrefixList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam, prefixListParam)
	ret0, _ := ret[0].(model.PrefixList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPrefixListsClientMockRecorder) Update(orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam, prefixListParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPrefixListsClient)(nil).Update), orgIdParam, projectIdParam, transitGatewayIdParam, prefixListIdParam, prefixListParam)
}
