// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects/transit_gateways (interfaces: RoutingClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockRoutingClient is a mock of RoutingClient interface.
type MockRoutingClient struct {
	ctrl     *gomock.Controller
	recorder *MockRoutingClientMockRecorder
}

// MockRoutingClientMockRecorder is the mock recorder for MockRoutingClient.
type MockRoutingClientMockRecorder struct {
	mock *MockRoutingClient
}

// NewMockRoutingClient creates a new mock instance.
func NewMockRoutingClient(ctrl *gomock.Controller) *MockRoutingClient {
	mock := &MockRoutingClient{ctrl: ctrl}
	mock.recorder = &MockRoutingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoutingClient) EXPECT() *MockRoutingClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRoutingClient) Delete(orgIdParam string, projectIdParam string, transitGatewayIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", orgIdParam, projectIdParam, transitGatewayIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoutingClientMockRecorder) Delete(orgIdParam, projectIdParam, transitGatewayIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoutingClient)(nil).Delete), orgIdParam, projectIdParam, transitGatewayIdParam)
}

// Get mocks base method.
func (m *MockRoutingClient) Get(orgIdParam string, projectIdParam string, transitGatewayIdParam string) (model.TransitGatewayRoutingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orgIdParam, projectIdParam, transitGatewayIdParam)
	ret0, _ := ret[0].(model.TransitGatewayRoutingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoutingClientMockRecorder) Get(orgIdParam, projectIdParam, transitGatewayIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoutingClient)(nil).Get), orgIdParam, projectIdParam, transitGatewayIdParam)
}

// Patch mocks base method.
func (m *MockRoutingClient) Patch(orgIdParam string, projectIdParam string, transitGatewayIdParam string, transitGatewayRoutingConfigParam model.TransitGatewayRoutingConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", orgIdParam, projectIdParam, transitGatewayIdParam, transitGatewayRoutingConfigParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockRoutingClientMockRecorder) Patch(orgIdParam, projectIdParam, transitGatewayIdParam, transitGatewayRoutingConfigParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockRoutingClient)(nil).Patch), orgIdParam, projectIdParam, transitGatewayIdParam, transitGatewayRoutingConfigParam)
}

// Update mocks base method.
func (m *MockRoutingClient) Update(orgIdParam string, projectIdParam string, transitGatewayIdParam string, transitGatewayRoutingConfigParam model.TransitGatewayRoutingConfig) (model.TransitGatewayRoutingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", orgIdParam, projectIdParam, transitGatewayIdParam, transitGatewayRoutingConfigParam)
	ret0, _ := ret[0].(model.TransitGatewayRoutingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRoutingClientMockRecorder) Update(orgIdParam, projectIdParam, transitGatewayIdParam, transitGatewayRoutingConfigParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoutingClient)(nil).Update), orgIdParam, projectIdParam, transitGatewayIdParam, transitGatewayRoutingConfigParam)
}
