// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/static_routes/BfdPeersClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockBfdPeersClient is a mock of BfdPeersClient interface.
type MockBfdPeersClient struct {
	ctrl     *gomock.Controller
	recorder *MockBfdPeersClientMockRecorder
}

// MockBfdPeersClientMockRecorder is the mock recorder for MockBfdPeersClient.
type MockBfdPeersClientMockRecorder struct {
	mock *MockBfdPeersClient
}

// NewMockBfdPeersClient creates a new mock instance.
func NewMockBfdPeersClient(ctrl *gomock.Controller) *MockBfdPeersClient {
	mock := &MockBfdPeersClient{ctrl: ctrl}
	mock.recorder = &MockBfdPeersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBfdPeersClient) EXPECT() *MockBfdPeersClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBfdPeersClient) Delete(tier0IdParam, bfdPeerIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tier0IdParam, bfdPeerIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBfdPeersClientMockRecorder) Delete(tier0IdParam, bfdPeerIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBfdPeersClient)(nil).Delete), tier0IdParam, bfdPeerIdParam)
}

// Get mocks base method.
func (m *MockBfdPeersClient) Get(tier0IdParam, bfdPeerIdParam string) (model.StaticRouteBfdPeer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier0IdParam, bfdPeerIdParam)
	ret0, _ := ret[0].(model.StaticRouteBfdPeer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBfdPeersClientMockRecorder) Get(tier0IdParam, bfdPeerIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBfdPeersClient)(nil).Get), tier0IdParam, bfdPeerIdParam)
}

// List mocks base method.
func (m *MockBfdPeersClient) List(tier0IdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.StaticRouteBfdPeerListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier0IdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.StaticRouteBfdPeerListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBfdPeersClientMockRecorder) List(tier0IdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBfdPeersClient)(nil).List), tier0IdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockBfdPeersClient) Patch(tier0IdParam, bfdPeerIdParam string, staticRouteBfdPeerParam model.StaticRouteBfdPeer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier0IdParam, bfdPeerIdParam, staticRouteBfdPeerParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockBfdPeersClientMockRecorder) Patch(tier0IdParam, bfdPeerIdParam, staticRouteBfdPeerParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockBfdPeersClient)(nil).Patch), tier0IdParam, bfdPeerIdParam, staticRouteBfdPeerParam)
}

// Update mocks base method.
func (m *MockBfdPeersClient) Update(tier0IdParam, bfdPeerIdParam string, staticRouteBfdPeerParam model.StaticRouteBfdPeer) (model.StaticRouteBfdPeer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier0IdParam, bfdPeerIdParam, staticRouteBfdPeerParam)
	ret0, _ := ret[0].(model.StaticRouteBfdPeer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBfdPeersClientMockRecorder) Update(tier0IdParam, bfdPeerIdParam, staticRouteBfdPeerParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBfdPeersClient)(nil).Update), tier0IdParam, bfdPeerIdParam, staticRouteBfdPeerParam)
}
