// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects (interfaces: CentralizedNetworkAttachmentsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockCentralizedNetworkAttachmentsClient is a mock of CentralizedNetworkAttachmentsClient interface.
type MockCentralizedNetworkAttachmentsClient struct {
	ctrl     *gomock.Controller
	recorder *MockCentralizedNetworkAttachmentsClientMockRecorder
}

// MockCentralizedNetworkAttachmentsClientMockRecorder is the mock recorder for MockCentralizedNetworkAttachmentsClient.
type MockCentralizedNetworkAttachmentsClientMockRecorder struct {
	mock *MockCentralizedNetworkAttachmentsClient
}

// NewMockCentralizedNetworkAttachmentsClient creates a new mock instance.
func NewMockCentralizedNetworkAttachmentsClient(ctrl *gomock.Controller) *MockCentralizedNetworkAttachmentsClient {
	mock := &MockCentralizedNetworkAttachmentsClient{ctrl: ctrl}
	mock.recorder = &MockCentralizedNetworkAttachmentsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCentralizedNetworkAttachmentsClient) EXPECT() *MockCentralizedNetworkAttachmentsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCentralizedNetworkAttachmentsClient) Delete(orgIdParam string, projectIdParam string, cnaIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", orgIdParam, projectIdParam, cnaIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCentralizedNetworkAttachmentsClientMockRecorder) Delete(orgIdParam, projectIdParam, cnaIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCentralizedNetworkAttachmentsClient)(nil).Delete), orgIdParam, projectIdParam, cnaIdParam)
}

// Get mocks base method.
func (m *MockCentralizedNetworkAttachmentsClient) Get(orgIdParam string, projectIdParam string, cnaIdParam string) (model.CentralizedNetworkAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orgIdParam, projectIdParam, cnaIdParam)
	ret0, _ := ret[0].(model.CentralizedNetworkAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCentralizedNetworkAttachmentsClientMockRecorder) Get(orgIdParam, projectIdParam, cnaIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCentralizedNetworkAttachmentsClient)(nil).Get), orgIdParam, projectIdParam, cnaIdParam)
}

// List mocks base method.
func (m *MockCentralizedNetworkAttachmentsClient) List(orgIdParam string, projectIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.CentralizedNetworkAttachmentListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.CentralizedNetworkAttachmentListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCentralizedNetworkAttachmentsClientMockRecorder) List(orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCentralizedNetworkAttachmentsClient)(nil).List), orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockCentralizedNetworkAttachmentsClient) Patch(orgIdParam string, projectIdParam string, cnaIdParam string, centralizedNetworkAttachmentParam model.CentralizedNetworkAttachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", orgIdParam, projectIdParam, cnaIdParam, centralizedNetworkAttachmentParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockCentralizedNetworkAttachmentsClientMockRecorder) Patch(orgIdParam, projectIdParam, cnaIdParam, centralizedNetworkAttachmentParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockCentralizedNetworkAttachmentsClient)(nil).Patch), orgIdParam, projectIdParam, cnaIdParam, centralizedNetworkAttachmentParam)
}

// Update mocks base method.
func (m *MockCentralizedNetworkAttachmentsClient) Update(orgIdParam string, projectIdParam string, cnaIdParam string, centralizedNetworkAttachmentParam model.CentralizedNetworkAttachment) (model.CentralizedNetworkAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", orgIdParam, projectIdParam, cnaIdParam, centralizedNetworkAttachmentParam)
	ret0, _ := ret[0].(model.CentralizedNetworkAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCentralizedNetworkAttachmentsClientMockRecorder) Update(orgIdParam, projectIdParam, cnaIdParam, centralizedNetworkAttachmentParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCentralizedNetworkAttachmentsClient)(nil).Update), orgIdParam, projectIdParam, cnaIdParam, centralizedNetworkAttachmentParam)
}
