// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects (interfaces: DnsServicesClient)
//
// Generated by this command:
//
//	mockgen -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/orgs/projects/DnsServicesClient.go -package mocks github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects DnsServicesClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDnsServicesClient is a mock of DnsServicesClient interface.
type MockDnsServicesClient struct {
	ctrl     *gomock.Controller
	recorder *MockDnsServicesClientMockRecorder
	isgomock struct{}
}

// MockDnsServicesClientMockRecorder is the mock recorder for MockDnsServicesClient.
type MockDnsServicesClientMockRecorder struct {
	mock *MockDnsServicesClient
}

// NewMockDnsServicesClient creates a new mock instance.
func NewMockDnsServicesClient(ctrl *gomock.Controller) *MockDnsServicesClient {
	mock := &MockDnsServicesClient{ctrl: ctrl}
	mock.recorder = &MockDnsServicesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDnsServicesClient) EXPECT() *MockDnsServicesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDnsServicesClient) Delete(orgIdParam, projectIdParam, dnsServiceIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", orgIdParam, projectIdParam, dnsServiceIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDnsServicesClientMockRecorder) Delete(orgIdParam, projectIdParam, dnsServiceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDnsServicesClient)(nil).Delete), orgIdParam, projectIdParam, dnsServiceIdParam)
}

// Get mocks base method.
func (m *MockDnsServicesClient) Get(orgIdParam, projectIdParam, dnsServiceIdParam string) (model.DnsService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orgIdParam, projectIdParam, dnsServiceIdParam)
	ret0, _ := ret[0].(model.DnsService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDnsServicesClientMockRecorder) Get(orgIdParam, projectIdParam, dnsServiceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDnsServicesClient)(nil).Get), orgIdParam, projectIdParam, dnsServiceIdParam)
}

// List mocks base method.
func (m *MockDnsServicesClient) List(orgIdParam, projectIdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.DnsServiceListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", orgIdParam, projectIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.DnsServiceListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDnsServicesClientMockRecorder) List(orgIdParam, projectIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDnsServicesClient)(nil).List), orgIdParam, projectIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockDnsServicesClient) Patch(orgIdParam, projectIdParam, dnsServiceIdParam string, dnsServiceParam model.DnsService) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", orgIdParam, projectIdParam, dnsServiceIdParam, dnsServiceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockDnsServicesClientMockRecorder) Patch(orgIdParam, projectIdParam, dnsServiceIdParam, dnsServiceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockDnsServicesClient)(nil).Patch), orgIdParam, projectIdParam, dnsServiceIdParam, dnsServiceParam)
}

// Update mocks base method.
func (m *MockDnsServicesClient) Update(orgIdParam, projectIdParam, dnsServiceIdParam string, dnsServiceParam model.DnsService) (model.DnsService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", orgIdParam, projectIdParam, dnsServiceIdParam, dnsServiceParam)
	ret0, _ := ret[0].(model.DnsService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDnsServicesClientMockRecorder) Update(orgIdParam, projectIdParam, dnsServiceIdParam, dnsServiceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDnsServicesClient)(nil).Update), orgIdParam, projectIdParam, dnsServiceIdParam, dnsServiceParam)
}
