// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects (interfaces: VpcConnectivityProfilesClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockVpcConnectivityProfilesClient is a mock of VpcConnectivityProfilesClient interface.
type MockVpcConnectivityProfilesClient struct {
	ctrl     *gomock.Controller
	recorder *MockVpcConnectivityProfilesClientMockRecorder
}

// MockVpcConnectivityProfilesClientMockRecorder is the mock recorder for MockVpcConnectivityProfilesClient.
type MockVpcConnectivityProfilesClientMockRecorder struct {
	mock *MockVpcConnectivityProfilesClient
}

// NewMockVpcConnectivityProfilesClient creates a new mock instance.
func NewMockVpcConnectivityProfilesClient(ctrl *gomock.Controller) *MockVpcConnectivityProfilesClient {
	mock := &MockVpcConnectivityProfilesClient{ctrl: ctrl}
	mock.recorder = &MockVpcConnectivityProfilesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVpcConnectivityProfilesClient) EXPECT() *MockVpcConnectivityProfilesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockVpcConnectivityProfilesClient) Delete(orgIdParam string, projectIdParam string, vpcConnectivityProfileIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", orgIdParam, projectIdParam, vpcConnectivityProfileIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVpcConnectivityProfilesClientMockRecorder) Delete(orgIdParam, projectIdParam, vpcConnectivityProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVpcConnectivityProfilesClient)(nil).Delete), orgIdParam, projectIdParam, vpcConnectivityProfileIdParam)
}

// Get mocks base method.
func (m *MockVpcConnectivityProfilesClient) Get(orgIdParam string, projectIdParam string, vpcConnectivityProfileIdParam string) (model.VpcConnectivityProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orgIdParam, projectIdParam, vpcConnectivityProfileIdParam)
	ret0, _ := ret[0].(model.VpcConnectivityProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVpcConnectivityProfilesClientMockRecorder) Get(orgIdParam, projectIdParam, vpcConnectivityProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVpcConnectivityProfilesClient)(nil).Get), orgIdParam, projectIdParam, vpcConnectivityProfileIdParam)
}

// List mocks base method.
func (m *MockVpcConnectivityProfilesClient) List(orgIdParam string, projectIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.VpcConnectivityProfileListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.VpcConnectivityProfileListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVpcConnectivityProfilesClientMockRecorder) List(orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVpcConnectivityProfilesClient)(nil).List), orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockVpcConnectivityProfilesClient) Patch(orgIdParam string, projectIdParam string, vpcConnectivityProfileIdParam string, vpcConnectivityProfileParam model.VpcConnectivityProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", orgIdParam, projectIdParam, vpcConnectivityProfileIdParam, vpcConnectivityProfileParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockVpcConnectivityProfilesClientMockRecorder) Patch(orgIdParam, projectIdParam, vpcConnectivityProfileIdParam, vpcConnectivityProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockVpcConnectivityProfilesClient)(nil).Patch), orgIdParam, projectIdParam, vpcConnectivityProfileIdParam, vpcConnectivityProfileParam)
}

// Update mocks base method.
func (m *MockVpcConnectivityProfilesClient) Update(orgIdParam string, projectIdParam string, vpcConnectivityProfileIdParam string, vpcConnectivityProfileParam model.VpcConnectivityProfile) (model.VpcConnectivityProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", orgIdParam, projectIdParam, vpcConnectivityProfileIdParam, vpcConnectivityProfileParam)
	ret0, _ := ret[0].(model.VpcConnectivityProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVpcConnectivityProfilesClientMockRecorder) Update(orgIdParam, projectIdParam, vpcConnectivityProfileIdParam, vpcConnectivityProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVpcConnectivityProfilesClient)(nil).Update), orgIdParam, projectIdParam, vpcConnectivityProfileIdParam, vpcConnectivityProfileParam)
}
