// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects (interfaces: VpcSecurityProfilesClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockVpcSecurityProfilesClient is a mock of VpcSecurityProfilesClient interface.
type MockVpcSecurityProfilesClient struct {
	ctrl     *gomock.Controller
	recorder *MockVpcSecurityProfilesClientMockRecorder
}

// MockVpcSecurityProfilesClientMockRecorder is the mock recorder for MockVpcSecurityProfilesClient.
type MockVpcSecurityProfilesClientMockRecorder struct {
	mock *MockVpcSecurityProfilesClient
}

// NewMockVpcSecurityProfilesClient creates a new mock instance.
func NewMockVpcSecurityProfilesClient(ctrl *gomock.Controller) *MockVpcSecurityProfilesClient {
	mock := &MockVpcSecurityProfilesClient{ctrl: ctrl}
	mock.recorder = &MockVpcSecurityProfilesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVpcSecurityProfilesClient) EXPECT() *MockVpcSecurityProfilesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVpcSecurityProfilesClient) Get(orgIdParam string, projectIdParam string, vpcSecurityProfileIdParam string) (model.VpcSecurityProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orgIdParam, projectIdParam, vpcSecurityProfileIdParam)
	ret0, _ := ret[0].(model.VpcSecurityProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVpcSecurityProfilesClientMockRecorder) Get(orgIdParam, projectIdParam, vpcSecurityProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVpcSecurityProfilesClient)(nil).Get), orgIdParam, projectIdParam, vpcSecurityProfileIdParam)
}

// List mocks base method.
func (m *MockVpcSecurityProfilesClient) List(orgIdParam string, projectIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.VpcSecurityProfileListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.VpcSecurityProfileListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVpcSecurityProfilesClientMockRecorder) List(orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVpcSecurityProfilesClient)(nil).List), orgIdParam, projectIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockVpcSecurityProfilesClient) Patch(orgIdParam string, projectIdParam string, vpcSecurityProfileIdParam string, vpcSecurityProfileParam model.VpcSecurityProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", orgIdParam, projectIdParam, vpcSecurityProfileIdParam, vpcSecurityProfileParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockVpcSecurityProfilesClientMockRecorder) Patch(orgIdParam, projectIdParam, vpcSecurityProfileIdParam, vpcSecurityProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockVpcSecurityProfilesClient)(nil).Patch), orgIdParam, projectIdParam, vpcSecurityProfileIdParam, vpcSecurityProfileParam)
}
