// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/locale_services/bgp/neighbors/AdvertisedRoutesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockAdvertisedRoutesClient is a mock of AdvertisedRoutesClient interface.
type MockAdvertisedRoutesClient struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertisedRoutesClientMockRecorder
}

// MockAdvertisedRoutesClientMockRecorder is the mock recorder for MockAdvertisedRoutesClient.
type MockAdvertisedRoutesClientMockRecorder struct {
	mock *MockAdvertisedRoutesClient
}

// NewMockAdvertisedRoutesClient creates a new mock instance.
func NewMockAdvertisedRoutesClient(ctrl *gomock.Controller) *MockAdvertisedRoutesClient {
	mock := &MockAdvertisedRoutesClient{ctrl: ctrl}
	mock.recorder = &MockAdvertisedRoutesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvertisedRoutesClient) EXPECT() *MockAdvertisedRoutesClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAdvertisedRoutesClient) List(tier0IdParam, localeServiceIdParam, neighborIdParam string, countParam *int64, cursorParam, enforcementPointPathParam, includedFieldsParam, neighborAddressParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.BgpNeighborRoutesListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier0IdParam, localeServiceIdParam, neighborIdParam, countParam, cursorParam, enforcementPointPathParam, includedFieldsParam, neighborAddressParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.BgpNeighborRoutesListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAdvertisedRoutesClientMockRecorder) List(tier0IdParam, localeServiceIdParam, neighborIdParam, countParam, cursorParam, enforcementPointPathParam, includedFieldsParam, neighborAddressParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdvertisedRoutesClient)(nil).List), tier0IdParam, localeServiceIdParam, neighborIdParam, countParam, cursorParam, enforcementPointPathParam, includedFieldsParam, neighborAddressParam, pageSizeParam, sortAscendingParam, sortByParam)
}
