// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/sites/enforcement_points/BmCcpnStatusClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/sites/enforcement_points/BmCcpnStatusClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/sites/enforcement_points/BmCcpnStatusClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockBmCcpnStatusClient is a mock of BmCcpnStatusClient interface.
type MockBmCcpnStatusClient struct {
	ctrl     *gomock.Controller
	recorder *MockBmCcpnStatusClientMockRecorder
	isgomock struct{}
}

// MockBmCcpnStatusClientMockRecorder is the mock recorder for MockBmCcpnStatusClient.
type MockBmCcpnStatusClientMockRecorder struct {
	mock *MockBmCcpnStatusClient
}

// NewMockBmCcpnStatusClient creates a new mock instance.
func NewMockBmCcpnStatusClient(ctrl *gomock.Controller) *MockBmCcpnStatusClient {
	mock := &MockBmCcpnStatusClient{ctrl: ctrl}
	mock.recorder = &MockBmCcpnStatusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBmCcpnStatusClient) EXPECT() *MockBmCcpnStatusClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockBmCcpnStatusClient) List(siteIdParam, enforcementpointIdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.BMCClusterListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", siteIdParam, enforcementpointIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.BMCClusterListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBmCcpnStatusClientMockRecorder) List(siteIdParam, enforcementpointIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBmCcpnStatusClient)(nil).List), siteIdParam, enforcementpointIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
