// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/sites/enforcement_points/ClusterControlPlanesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/sites/enforcement_points/ClusterControlPlanesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/sites/enforcement_points/ClusterControlPlanesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockClusterControlPlanesClient is a mock of ClusterControlPlanesClient interface.
type MockClusterControlPlanesClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterControlPlanesClientMockRecorder
	isgomock struct{}
}

// MockClusterControlPlanesClientMockRecorder is the mock recorder for MockClusterControlPlanesClient.
type MockClusterControlPlanesClientMockRecorder struct {
	mock *MockClusterControlPlanesClient
}

// NewMockClusterControlPlanesClient creates a new mock instance.
func NewMockClusterControlPlanesClient(ctrl *gomock.Controller) *MockClusterControlPlanesClient {
	mock := &MockClusterControlPlanesClient{ctrl: ctrl}
	mock.recorder = &MockClusterControlPlanesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterControlPlanesClient) EXPECT() *MockClusterControlPlanesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockClusterControlPlanesClient) Delete(siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam string, cascadeParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam, cascadeParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClusterControlPlanesClientMockRecorder) Delete(siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam, cascadeParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClusterControlPlanesClient)(nil).Delete), siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam, cascadeParam)
}

// Get mocks base method.
func (m *MockClusterControlPlanesClient) Get(siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam string) (model.ClusterControlPlane, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam)
	ret0, _ := ret[0].(model.ClusterControlPlane)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterControlPlanesClientMockRecorder) Get(siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterControlPlanesClient)(nil).Get), siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam)
}

// List mocks base method.
func (m *MockClusterControlPlanesClient) List(siteIdParam, enforcementpointIdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.ClusterControlPlaneListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", siteIdParam, enforcementpointIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.ClusterControlPlaneListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterControlPlanesClientMockRecorder) List(siteIdParam, enforcementpointIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterControlPlanesClient)(nil).List), siteIdParam, enforcementpointIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Update mocks base method.
func (m *MockClusterControlPlanesClient) Update(siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam string, clusterControlPlaneParam model.ClusterControlPlane) (model.ClusterControlPlane, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam, clusterControlPlaneParam)
	ret0, _ := ret[0].(model.ClusterControlPlane)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClusterControlPlanesClientMockRecorder) Update(siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam, clusterControlPlaneParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClusterControlPlanesClient)(nil).Update), siteIdParam, enforcementpointIdParam, clusterControlPlaneIdParam, clusterControlPlaneParam)
}
