// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points/ClusterControlPlanesStatusClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockClusterControlPlanesStatusClient is a mock of ClusterControlPlanesStatusClient interface.
type MockClusterControlPlanesStatusClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterControlPlanesStatusClientMockRecorder
}

// MockClusterControlPlanesStatusClientMockRecorder is the mock recorder for MockClusterControlPlanesStatusClient.
type MockClusterControlPlanesStatusClientMockRecorder struct {
	mock *MockClusterControlPlanesStatusClient
}

// NewMockClusterControlPlanesStatusClient creates a new mock instance.
func NewMockClusterControlPlanesStatusClient(ctrl *gomock.Controller) *MockClusterControlPlanesStatusClient {
	mock := &MockClusterControlPlanesStatusClient{ctrl: ctrl}
	mock.recorder = &MockClusterControlPlanesStatusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterControlPlanesStatusClient) EXPECT() *MockClusterControlPlanesStatusClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockClusterControlPlanesStatusClient) List(siteIdParam, enforcementpointIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.AntreaClusterListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", siteIdParam, enforcementpointIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.AntreaClusterListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterControlPlanesStatusClientMockRecorder) List(siteIdParam, enforcementpointIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterControlPlanesStatusClient)(nil).List), siteIdParam, enforcementpointIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
