// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points/HostTransportNodesAggstatusClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockHostTransportNodesAggstatusClient is a mock of HostTransportNodesAggstatusClient interface.
type MockHostTransportNodesAggstatusClient struct {
	ctrl     *gomock.Controller
	recorder *MockHostTransportNodesAggstatusClientMockRecorder
}

// MockHostTransportNodesAggstatusClientMockRecorder is the mock recorder for MockHostTransportNodesAggstatusClient.
type MockHostTransportNodesAggstatusClientMockRecorder struct {
	mock *MockHostTransportNodesAggstatusClient
}

// NewMockHostTransportNodesAggstatusClient creates a new mock instance.
func NewMockHostTransportNodesAggstatusClient(ctrl *gomock.Controller) *MockHostTransportNodesAggstatusClient {
	mock := &MockHostTransportNodesAggstatusClient{ctrl: ctrl}
	mock.recorder = &MockHostTransportNodesAggstatusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostTransportNodesAggstatusClient) EXPECT() *MockHostTransportNodesAggstatusClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHostTransportNodesAggstatusClient) Get(siteIdParam, enforcementPointIdParam string, nodeTypeParam *string) (model.HeatMapTransportZoneStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", siteIdParam, enforcementPointIdParam, nodeTypeParam)
	ret0, _ := ret[0].(model.HeatMapTransportZoneStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHostTransportNodesAggstatusClientMockRecorder) Get(siteIdParam, enforcementPointIdParam, nodeTypeParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHostTransportNodesAggstatusClient)(nil).Get), siteIdParam, enforcementPointIdParam, nodeTypeParam)
}
