// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points/virtual_network_appliance_clusters (interfaces: StateClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	"go.uber.org/mock/gomock"
)

// MockVirtualNetworkApplianceClusterStateClient is a mock of StateClient interface.
type MockVirtualNetworkApplianceClusterStateClient struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualNetworkApplianceClusterStateClientMockRecorder
}

// MockVirtualNetworkApplianceClusterStateClientMockRecorder is the mock recorder for MockVirtualNetworkApplianceClusterStateClient.
type MockVirtualNetworkApplianceClusterStateClientMockRecorder struct {
	mock *MockVirtualNetworkApplianceClusterStateClient
}

// NewMockVirtualNetworkApplianceClusterStateClient creates a new mock instance.
func NewMockVirtualNetworkApplianceClusterStateClient(ctrl *gomock.Controller) *MockVirtualNetworkApplianceClusterStateClient {
	mock := &MockVirtualNetworkApplianceClusterStateClient{ctrl: ctrl}
	mock.recorder = &MockVirtualNetworkApplianceClusterStateClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualNetworkApplianceClusterStateClient) EXPECT() *MockVirtualNetworkApplianceClusterStateClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVirtualNetworkApplianceClusterStateClient) Get(siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam string) (model.VirtualNetworkApplianceClusterState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam)
	ret0, _ := ret[0].(model.VirtualNetworkApplianceClusterState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVirtualNetworkApplianceClusterStateClientMockRecorder) Get(siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVirtualNetworkApplianceClusterStateClient)(nil).Get), siteIdParam, enforcementpointIdParam, virtualNetworkApplianceClusterIdParam)
}
