// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/route_controllers/InterfacesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/route_controllers/InterfacesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/route_controllers/InterfacesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockInterfacesClient is a mock of InterfacesClient interface.
type MockInterfacesClient struct {
	ctrl     *gomock.Controller
	recorder *MockInterfacesClientMockRecorder
	isgomock struct{}
}

// MockInterfacesClientMockRecorder is the mock recorder for MockInterfacesClient.
type MockInterfacesClientMockRecorder struct {
	mock *MockInterfacesClient
}

// NewMockInterfacesClient creates a new mock instance.
func NewMockInterfacesClient(ctrl *gomock.Controller) *MockInterfacesClient {
	mock := &MockInterfacesClient{ctrl: ctrl}
	mock.recorder = &MockInterfacesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterfacesClient) EXPECT() *MockInterfacesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockInterfacesClient) Delete(routerControllerIdParam, interfaceIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", routerControllerIdParam, interfaceIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInterfacesClientMockRecorder) Delete(routerControllerIdParam, interfaceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInterfacesClient)(nil).Delete), routerControllerIdParam, interfaceIdParam)
}

// Get mocks base method.
func (m *MockInterfacesClient) Get(routerControllerIdParam, interfaceIdParam string) (model.RouteControllerInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", routerControllerIdParam, interfaceIdParam)
	ret0, _ := ret[0].(model.RouteControllerInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInterfacesClientMockRecorder) Get(routerControllerIdParam, interfaceIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInterfacesClient)(nil).Get), routerControllerIdParam, interfaceIdParam)
}

// List mocks base method.
func (m *MockInterfacesClient) List(routerControllerIdParam string, cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.RouteControllerInterfaceListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", routerControllerIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.RouteControllerInterfaceListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInterfacesClientMockRecorder) List(routerControllerIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInterfacesClient)(nil).List), routerControllerIdParam, cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockInterfacesClient) Patch(routerControllerIdParam, interfaceIdParam string, routeControllerInterfaceParam model.RouteControllerInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", routerControllerIdParam, interfaceIdParam, routeControllerInterfaceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockInterfacesClientMockRecorder) Patch(routerControllerIdParam, interfaceIdParam, routeControllerInterfaceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockInterfacesClient)(nil).Patch), routerControllerIdParam, interfaceIdParam, routeControllerInterfaceParam)
}

// Update mocks base method.
func (m *MockInterfacesClient) Update(routerControllerIdParam, interfaceIdParam string, routeControllerInterfaceParam model.RouteControllerInterface) (model.RouteControllerInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", routerControllerIdParam, interfaceIdParam, routeControllerInterfaceParam)
	ret0, _ := ret[0].(model.RouteControllerInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInterfacesClientMockRecorder) Update(routerControllerIdParam, interfaceIdParam, routeControllerInterfaceParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInterfacesClient)(nil).Update), routerControllerIdParam, interfaceIdParam, routeControllerInterfaceParam)
}
