// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/identity_firewall_stores/EventLogServersClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockEventLogServersClient is a mock of EventLogServersClient interface.
type MockEventLogServersClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventLogServersClientMockRecorder
}

// MockEventLogServersClientMockRecorder is the mock recorder for MockEventLogServersClient.
type MockEventLogServersClientMockRecorder struct {
	mock *MockEventLogServersClient
}

// NewMockEventLogServersClient creates a new mock instance.
func NewMockEventLogServersClient(ctrl *gomock.Controller) *MockEventLogServersClient {
	mock := &MockEventLogServersClient{ctrl: ctrl}
	mock.recorder = &MockEventLogServersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventLogServersClient) EXPECT() *MockEventLogServersClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockEventLogServersClient) Delete(identityFirewallStoreIdParam, eventLogServerIdParam string, enforcementPointPathParam *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", identityFirewallStoreIdParam, eventLogServerIdParam, enforcementPointPathParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventLogServersClientMockRecorder) Delete(identityFirewallStoreIdParam, eventLogServerIdParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventLogServersClient)(nil).Delete), identityFirewallStoreIdParam, eventLogServerIdParam, enforcementPointPathParam)
}

// Get mocks base method.
func (m *MockEventLogServersClient) Get(identityFirewallStoreIdParam, eventLogServerIdParam string, enforcementPointPathParam *string) (model.IdentityFirewallStoreEventLogServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", identityFirewallStoreIdParam, eventLogServerIdParam, enforcementPointPathParam)
	ret0, _ := ret[0].(model.IdentityFirewallStoreEventLogServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEventLogServersClientMockRecorder) Get(identityFirewallStoreIdParam, eventLogServerIdParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEventLogServersClient)(nil).Get), identityFirewallStoreIdParam, eventLogServerIdParam, enforcementPointPathParam)
}

// Patch mocks base method.
func (m *MockEventLogServersClient) Patch(identityFirewallStoreIdParam, eventLogServerIdParam string, identityFirewallStoreEventLogServerParam model.IdentityFirewallStoreEventLogServer, enforcementPointPathParam *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", identityFirewallStoreIdParam, eventLogServerIdParam, identityFirewallStoreEventLogServerParam, enforcementPointPathParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockEventLogServersClientMockRecorder) Patch(identityFirewallStoreIdParam, eventLogServerIdParam, identityFirewallStoreEventLogServerParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockEventLogServersClient)(nil).Patch), identityFirewallStoreIdParam, eventLogServerIdParam, identityFirewallStoreEventLogServerParam, enforcementPointPathParam)
}

// Update mocks base method.
func (m *MockEventLogServersClient) Update(identityFirewallStoreIdParam, eventLogServerIdParam string, identityFirewallStoreEventLogServerParam model.IdentityFirewallStoreEventLogServer, enforcementPointPathParam *string) (model.IdentityFirewallStoreEventLogServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", identityFirewallStoreIdParam, eventLogServerIdParam, identityFirewallStoreEventLogServerParam, enforcementPointPathParam)
	ret0, _ := ret[0].(model.IdentityFirewallStoreEventLogServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEventLogServersClientMockRecorder) Update(identityFirewallStoreIdParam, eventLogServerIdParam, identityFirewallStoreEventLogServerParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventLogServersClient)(nil).Update), identityFirewallStoreIdParam, eventLogServerIdParam, identityFirewallStoreEventLogServerParam, enforcementPointPathParam)
}
