// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/identity_firewall_stores/LdapServersClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockLdapServersClient is a mock of LdapServersClient interface.
type MockLdapServersClient struct {
	ctrl     *gomock.Controller
	recorder *MockLdapServersClientMockRecorder
}

// MockLdapServersClientMockRecorder is the mock recorder for MockLdapServersClient.
type MockLdapServersClientMockRecorder struct {
	mock *MockLdapServersClient
}

// NewMockLdapServersClient creates a new mock instance.
func NewMockLdapServersClient(ctrl *gomock.Controller) *MockLdapServersClient {
	mock := &MockLdapServersClient{ctrl: ctrl}
	mock.recorder = &MockLdapServersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLdapServersClient) EXPECT() *MockLdapServersClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLdapServersClient) Delete(identityFirewallStoreIdParam, ldapServerIdParam string, enforcementPointPathParam *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", identityFirewallStoreIdParam, ldapServerIdParam, enforcementPointPathParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLdapServersClientMockRecorder) Delete(identityFirewallStoreIdParam, ldapServerIdParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLdapServersClient)(nil).Delete), identityFirewallStoreIdParam, ldapServerIdParam, enforcementPointPathParam)
}

// Get mocks base method.
func (m *MockLdapServersClient) Get(identityFirewallStoreIdParam, ldapServerIdParam string, enforcementPointPathParam *string) (model.IdentityFirewallStoreLdapServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", identityFirewallStoreIdParam, ldapServerIdParam, enforcementPointPathParam)
	ret0, _ := ret[0].(model.IdentityFirewallStoreLdapServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLdapServersClientMockRecorder) Get(identityFirewallStoreIdParam, ldapServerIdParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLdapServersClient)(nil).Get), identityFirewallStoreIdParam, ldapServerIdParam, enforcementPointPathParam)
}

// List mocks base method.
func (m *MockLdapServersClient) List(identityFirewallStoreIdParam string, cursorParam, enforcementPointPathParam, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.IdentityFirewallStoreLdapServerListResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", identityFirewallStoreIdParam, cursorParam, enforcementPointPathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.IdentityFirewallStoreLdapServerListResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLdapServersClientMockRecorder) List(identityFirewallStoreIdParam, cursorParam, enforcementPointPathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLdapServersClient)(nil).List), identityFirewallStoreIdParam, cursorParam, enforcementPointPathParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockLdapServersClient) Patch(identityFirewallStoreIdParam, ldapServerIdParam string, identityFirewallStoreLdapServerParam model.IdentityFirewallStoreLdapServer, enforcementPointPathParam *string) (model.IdentityFirewallStoreLdapServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", identityFirewallStoreIdParam, ldapServerIdParam, identityFirewallStoreLdapServerParam, enforcementPointPathParam)
	ret0, _ := ret[0].(model.IdentityFirewallStoreLdapServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockLdapServersClientMockRecorder) Patch(identityFirewallStoreIdParam, ldapServerIdParam, identityFirewallStoreLdapServerParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockLdapServersClient)(nil).Patch), identityFirewallStoreIdParam, ldapServerIdParam, identityFirewallStoreLdapServerParam, enforcementPointPathParam)
}

// Update mocks base method.
func (m *MockLdapServersClient) Update(identityFirewallStoreIdParam, ldapServerIdParam string, identityFirewallStoreLdapServerParam model.IdentityFirewallStoreLdapServer, enforcementPointPathParam *string) (model.IdentityFirewallStoreLdapServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", identityFirewallStoreIdParam, ldapServerIdParam, identityFirewallStoreLdapServerParam, enforcementPointPathParam)
	ret0, _ := ret[0].(model.IdentityFirewallStoreLdapServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLdapServersClientMockRecorder) Update(identityFirewallStoreIdParam, ldapServerIdParam, identityFirewallStoreLdapServerParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLdapServersClient)(nil).Update), identityFirewallStoreIdParam, ldapServerIdParam, identityFirewallStoreLdapServerParam, enforcementPointPathParam)
}
