// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/locale_services/bgp/NeighborsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockNeighborsClient is a mock of NeighborsClient interface.
type MockNeighborsClient struct {
	ctrl     *gomock.Controller
	recorder *MockNeighborsClientMockRecorder
}

// MockNeighborsClientMockRecorder is the mock recorder for MockNeighborsClient.
type MockNeighborsClientMockRecorder struct {
	mock *MockNeighborsClient
}

// NewMockNeighborsClient creates a new mock instance.
func NewMockNeighborsClient(ctrl *gomock.Controller) *MockNeighborsClient {
	mock := &MockNeighborsClient{ctrl: ctrl}
	mock.recorder = &MockNeighborsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNeighborsClient) EXPECT() *MockNeighborsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockNeighborsClient) Delete(tier0IdParam, localeServiceIdParam, neighborIdParam string, overrideParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tier0IdParam, localeServiceIdParam, neighborIdParam, overrideParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNeighborsClientMockRecorder) Delete(tier0IdParam, localeServiceIdParam, neighborIdParam, overrideParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNeighborsClient)(nil).Delete), tier0IdParam, localeServiceIdParam, neighborIdParam, overrideParam)
}

// Get mocks base method.
func (m *MockNeighborsClient) Get(tier0IdParam, localeServiceIdParam, neighborIdParam string) (model.BgpNeighborConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tier0IdParam, localeServiceIdParam, neighborIdParam)
	ret0, _ := ret[0].(model.BgpNeighborConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNeighborsClientMockRecorder) Get(tier0IdParam, localeServiceIdParam, neighborIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNeighborsClient)(nil).Get), tier0IdParam, localeServiceIdParam, neighborIdParam)
}

// List mocks base method.
func (m *MockNeighborsClient) List(tier0IdParam, localeServiceIdParam string, cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.BgpNeighborConfigListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier0IdParam, localeServiceIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.BgpNeighborConfigListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNeighborsClientMockRecorder) List(tier0IdParam, localeServiceIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNeighborsClient)(nil).List), tier0IdParam, localeServiceIdParam, cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockNeighborsClient) Patch(tier0IdParam, localeServiceIdParam, neighborIdParam string, bgpNeighborConfigParam model.BgpNeighborConfig, overrideParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", tier0IdParam, localeServiceIdParam, neighborIdParam, bgpNeighborConfigParam, overrideParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockNeighborsClientMockRecorder) Patch(tier0IdParam, localeServiceIdParam, neighborIdParam, bgpNeighborConfigParam, overrideParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockNeighborsClient)(nil).Patch), tier0IdParam, localeServiceIdParam, neighborIdParam, bgpNeighborConfigParam, overrideParam)
}

// Update mocks base method.
func (m *MockNeighborsClient) Update(tier0IdParam, localeServiceIdParam, neighborIdParam string, bgpNeighborConfigParam model.BgpNeighborConfig, overrideParam *bool) (model.BgpNeighborConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tier0IdParam, localeServiceIdParam, neighborIdParam, bgpNeighborConfigParam, overrideParam)
	ret0, _ := ret[0].(model.BgpNeighborConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNeighborsClientMockRecorder) Update(tier0IdParam, localeServiceIdParam, neighborIdParam, bgpNeighborConfigParam, overrideParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNeighborsClient)(nil).Update), tier0IdParam, localeServiceIdParam, neighborIdParam, bgpNeighborConfigParam, overrideParam)
}
