//nolint:revive
package ports

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client1 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/global_infra/tier_1s/segments/ports"
	model1 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-gm/model"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/tier_1s/segments/ports"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	client2 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects/infra/tier_1s/segments/ports"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type PortQosProfileBindingMapClientContext utl.ClientContext

func NewPortQosProfileBindingMapsClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *PortQosProfileBindingMapClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewPortQosProfileBindingMapsClient(connector)

	case utl.Global:
		client = client1.NewPortQosProfileBindingMapsClient(connector)

	case utl.Multitenancy:
		client = client2.NewPortQosProfileBindingMapsClient(connector)

	default:
		return nil
	}
	return &PortQosProfileBindingMapClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c PortQosProfileBindingMapClientContext) Delete(tier1IdParam string, segmentIdParam string, portIdParam string, portQosProfileBindingMapIdParam string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.PortQosProfileBindingMapsClient)
		err = client.Delete(tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam)

	case utl.Multitenancy:
		client := c.Client.(client2.PortQosProfileBindingMapsClient)
		err = client.Delete(utl.DefaultOrgID, c.ProjectID, tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c PortQosProfileBindingMapClientContext) Get(tier1IdParam string, segmentIdParam string, portIdParam string, portQosProfileBindingMapIdParam string) (model0.PortQosProfileBindingMap, error) {
	var obj model0.PortQosProfileBindingMap
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.PortQosProfileBindingMapsClient)
		obj, err = client.Get(tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam)
		if err != nil {
			return obj, err
		}

	case utl.Global:
		client := c.Client.(client1.PortQosProfileBindingMapsClient)
		gmObj, err1 := client.Get(tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam)
		if err1 != nil {
			return obj, err1
		}
		var rawObj interface{}
		rawObj, err = utl.ConvertModelBindingType(gmObj, model1.PortQosProfileBindingMapBindingType(), model0.PortQosProfileBindingMapBindingType())
		obj = rawObj.(model0.PortQosProfileBindingMap)

	case utl.Multitenancy:
		client := c.Client.(client2.PortQosProfileBindingMapsClient)
		obj, err = client.Get(utl.DefaultOrgID, c.ProjectID, tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c PortQosProfileBindingMapClientContext) List(tier1IdParam string, segmentIdParam string, portIdParam string, cursorParam *string, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.PortQosProfileBindingMapListResult, error) {
	var err error
	var obj model0.PortQosProfileBindingMapListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.PortQosProfileBindingMapsClient)
		obj, err = client.List(tier1IdParam, segmentIdParam, portIdParam, cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	case utl.Global:
		client := c.Client.(client1.PortQosProfileBindingMapsClient)
		gmObj, err := client.List(tier1IdParam, segmentIdParam, portIdParam, cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
		if err != nil {
			return obj, err
		}
		obj1, err1 := utl.ConvertModelBindingType(gmObj, model1.PortQosProfileBindingMapListResultBindingType(), model0.PortQosProfileBindingMapListResultBindingType())
		if err1 != nil {
			return obj, err1
		}
		obj = obj1.(model0.PortQosProfileBindingMapListResult)

	case utl.Multitenancy:
		client := c.Client.(client2.PortQosProfileBindingMapsClient)
		obj, err = client.List(utl.DefaultOrgID, c.ProjectID, tier1IdParam, segmentIdParam, portIdParam, cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c PortQosProfileBindingMapClientContext) Patch(tier1IdParam string, segmentIdParam string, portIdParam string, portQosProfileBindingMapIdParam string, portQosProfileBindingMapParam model0.PortQosProfileBindingMap) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.PortQosProfileBindingMapsClient)
		err = client.Patch(tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam, portQosProfileBindingMapParam)

	case utl.Multitenancy:
		client := c.Client.(client2.PortQosProfileBindingMapsClient)
		err = client.Patch(utl.DefaultOrgID, c.ProjectID, tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam, portQosProfileBindingMapParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c PortQosProfileBindingMapClientContext) Update(tier1IdParam string, segmentIdParam string, portIdParam string, portQosProfileBindingMapIdParam string, portQosProfileBindingMapParam model0.PortQosProfileBindingMap) (model0.PortQosProfileBindingMap, error) {
	var err error
	var obj model0.PortQosProfileBindingMap

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.PortQosProfileBindingMapsClient)
		obj, err = client.Update(tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam, portQosProfileBindingMapParam)

	case utl.Multitenancy:
		client := c.Client.(client2.PortQosProfileBindingMapsClient)
		obj, err = client.Update(utl.DefaultOrgID, c.ProjectID, tier1IdParam, segmentIdParam, portIdParam, portQosProfileBindingMapIdParam, portQosProfileBindingMapParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
