// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/realized_state/enforcement_points/groups/SecuritygroupsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockSecuritygroupsClient is a mock of SecuritygroupsClient interface.
type MockSecuritygroupsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSecuritygroupsClientMockRecorder
}

// MockSecuritygroupsClientMockRecorder is the mock recorder for MockSecuritygroupsClient.
type MockSecuritygroupsClientMockRecorder struct {
	mock *MockSecuritygroupsClient
}

// NewMockSecuritygroupsClient creates a new mock instance.
func NewMockSecuritygroupsClient(ctrl *gomock.Controller) *MockSecuritygroupsClient {
	mock := &MockSecuritygroupsClient{ctrl: ctrl}
	mock.recorder = &MockSecuritygroupsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecuritygroupsClient) EXPECT() *MockSecuritygroupsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSecuritygroupsClient) Get(enforcementPointNameParam, securitygroupNameParam string) (model.RealizedSecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", enforcementPointNameParam, securitygroupNameParam)
	ret0, _ := ret[0].(model.RealizedSecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecuritygroupsClientMockRecorder) Get(enforcementPointNameParam, securitygroupNameParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSecuritygroupsClient)(nil).Get), enforcementPointNameParam, securitygroupNameParam)
}

// List mocks base method.
func (m *MockSecuritygroupsClient) List(enforcementPointNameParam string, cursorParam, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.RealizedSecurityGroupListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", enforcementPointNameParam, cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.RealizedSecurityGroupListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecuritygroupsClientMockRecorder) List(enforcementPointNameParam, cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecuritygroupsClient)(nil).List), enforcementPointNameParam, cursorParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
