// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/AlbAuthTokenClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockAlbAuthTokenClient is a mock of AlbAuthTokenClient interface.
type MockAlbAuthTokenClient struct {
	ctrl     *gomock.Controller
	recorder *MockAlbAuthTokenClientMockRecorder
}

// MockAlbAuthTokenClientMockRecorder is the mock recorder for MockAlbAuthTokenClient.
type MockAlbAuthTokenClientMockRecorder struct {
	mock *MockAlbAuthTokenClient
}

// NewMockAlbAuthTokenClient creates a new mock instance.
func NewMockAlbAuthTokenClient(ctrl *gomock.Controller) *MockAlbAuthTokenClient {
	mock := &MockAlbAuthTokenClient{ctrl: ctrl}
	mock.recorder = &MockAlbAuthTokenClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbAuthTokenClient) EXPECT() *MockAlbAuthTokenClientMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockAlbAuthTokenClient) Update(aLBAuthTokenParam model.ALBAuthToken) (model.ALBAuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", aLBAuthTokenParam)
	ret0, _ := ret[0].(model.ALBAuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAlbAuthTokenClientMockRecorder) Update(aLBAuthTokenParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlbAuthTokenClient)(nil).Update), aLBAuthTokenParam)
}
