// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/AutoHealthChecksClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockAutoHealthChecksClient is a mock of AutoHealthChecksClient interface.
type MockAutoHealthChecksClient struct {
	ctrl     *gomock.Controller
	recorder *MockAutoHealthChecksClientMockRecorder
}

// MockAutoHealthChecksClientMockRecorder is the mock recorder for MockAutoHealthChecksClient.
type MockAutoHealthChecksClientMockRecorder struct {
	mock *MockAutoHealthChecksClient
}

// NewMockAutoHealthChecksClient creates a new mock instance.
func NewMockAutoHealthChecksClient(ctrl *gomock.Controller) *MockAutoHealthChecksClient {
	mock := &MockAutoHealthChecksClient{ctrl: ctrl}
	mock.recorder = &MockAutoHealthChecksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoHealthChecksClient) EXPECT() *MockAutoHealthChecksClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAutoHealthChecksClient) List(transportZonePathParam *string) (model.PolicyAutomaticHealthCheckListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", transportZonePathParam)
	ret0, _ := ret[0].(model.PolicyAutomaticHealthCheckListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAutoHealthChecksClientMockRecorder) List(transportZonePathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAutoHealthChecksClient)(nil).List), transportZonePathParam)
}
