// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/CategoriesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockCategoriesClient is a mock of CategoriesClient interface.
type MockCategoriesClient struct {
	ctrl     *gomock.Controller
	recorder *MockCategoriesClientMockRecorder
}

// MockCategoriesClientMockRecorder is the mock recorder for MockCategoriesClient.
type MockCategoriesClientMockRecorder struct {
	mock *MockCategoriesClient
}

// NewMockCategoriesClient creates a new mock instance.
func NewMockCategoriesClient(ctrl *gomock.Controller) *MockCategoriesClient {
	mock := &MockCategoriesClient{ctrl: ctrl}
	mock.recorder = &MockCategoriesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoriesClient) EXPECT() *MockCategoriesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCategoriesClient) Get(categoryIdParam string) (model.TagCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", categoryIdParam)
	ret0, _ := ret[0].(model.TagCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCategoriesClientMockRecorder) Get(categoryIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCategoriesClient)(nil).Get), categoryIdParam)
}

// List mocks base method.
func (m *MockCategoriesClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.CategoryListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.CategoryListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCategoriesClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCategoriesClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
