// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/CertificatesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockCertificatesClient is a mock of CertificatesClient interface.
type MockCertificatesClient struct {
	ctrl     *gomock.Controller
	recorder *MockCertificatesClientMockRecorder
}

// MockCertificatesClientMockRecorder is the mock recorder for MockCertificatesClient.
type MockCertificatesClientMockRecorder struct {
	mock *MockCertificatesClient
}

// NewMockCertificatesClient creates a new mock instance.
func NewMockCertificatesClient(ctrl *gomock.Controller) *MockCertificatesClient {
	mock := &MockCertificatesClient{ctrl: ctrl}
	mock.recorder = &MockCertificatesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificatesClient) EXPECT() *MockCertificatesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCertificatesClient) Delete(certificateIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", certificateIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCertificatesClientMockRecorder) Delete(certificateIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCertificatesClient)(nil).Delete), certificateIdParam)
}

// Get mocks base method.
func (m *MockCertificatesClient) Get(certificateIdParam string, detailsParam *bool, fmtParam *string) (model.TlsCertificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", certificateIdParam, detailsParam, fmtParam)
	ret0, _ := ret[0].(model.TlsCertificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCertificatesClientMockRecorder) Get(certificateIdParam, detailsParam, fmtParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCertificatesClient)(nil).Get), certificateIdParam, detailsParam, fmtParam)
}

// List mocks base method.
func (m *MockCertificatesClient) List(cursorParam *string, detailsParam *bool, fmtParam, includedFieldsParam, nodeIdParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam, type_Param *string) (model.TlsCertificateList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, detailsParam, fmtParam, includedFieldsParam, nodeIdParam, pageSizeParam, sortAscendingParam, sortByParam, type_Param)
	ret0, _ := ret[0].(model.TlsCertificateList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCertificatesClientMockRecorder) List(cursorParam, detailsParam, fmtParam, includedFieldsParam, nodeIdParam, pageSizeParam, sortAscendingParam, sortByParam, type_Param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCertificatesClient)(nil).List), cursorParam, detailsParam, fmtParam, includedFieldsParam, nodeIdParam, pageSizeParam, sortAscendingParam, sortByParam, type_Param)
}

// Patch mocks base method.
func (m *MockCertificatesClient) Patch(certificateIdParam string, tlsTrustDataParam model.TlsTrustData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", certificateIdParam, tlsTrustDataParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockCertificatesClientMockRecorder) Patch(certificateIdParam, tlsTrustDataParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockCertificatesClient)(nil).Patch), certificateIdParam, tlsTrustDataParam)
}

// Update mocks base method.
func (m *MockCertificatesClient) Update(certificateIdParam string, tlsTrustDataParam model.TlsTrustData) (model.TlsCertificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", certificateIdParam, tlsTrustDataParam)
	ret0, _ := ret[0].(model.TlsCertificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCertificatesClientMockRecorder) Update(certificateIdParam, tlsTrustDataParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCertificatesClient)(nil).Update), certificateIdParam, tlsTrustDataParam)
}
