// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/DistributedVlanConnectionsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockDistributedVlanConnectionsClient is a mock of DistributedVlanConnectionsClient interface.
type MockDistributedVlanConnectionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockDistributedVlanConnectionsClientMockRecorder
}

// MockDistributedVlanConnectionsClientMockRecorder is the mock recorder for MockDistributedVlanConnectionsClient.
type MockDistributedVlanConnectionsClientMockRecorder struct {
	mock *MockDistributedVlanConnectionsClient
}

// NewMockDistributedVlanConnectionsClient creates a new mock instance.
func NewMockDistributedVlanConnectionsClient(ctrl *gomock.Controller) *MockDistributedVlanConnectionsClient {
	mock := &MockDistributedVlanConnectionsClient{ctrl: ctrl}
	mock.recorder = &MockDistributedVlanConnectionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistributedVlanConnectionsClient) EXPECT() *MockDistributedVlanConnectionsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDistributedVlanConnectionsClient) Delete(distributedVlanConnectionIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", distributedVlanConnectionIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDistributedVlanConnectionsClientMockRecorder) Delete(distributedVlanConnectionIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDistributedVlanConnectionsClient)(nil).Delete), distributedVlanConnectionIdParam)
}

// Get mocks base method.
func (m *MockDistributedVlanConnectionsClient) Get(distributedVlanConnectionIdParam string) (model.DistributedVlanConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", distributedVlanConnectionIdParam)
	ret0, _ := ret[0].(model.DistributedVlanConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDistributedVlanConnectionsClientMockRecorder) Get(distributedVlanConnectionIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDistributedVlanConnectionsClient)(nil).Get), distributedVlanConnectionIdParam)
}

// List mocks base method.
func (m *MockDistributedVlanConnectionsClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.DistributedVlanConnectionListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.DistributedVlanConnectionListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDistributedVlanConnectionsClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDistributedVlanConnectionsClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockDistributedVlanConnectionsClient) Patch(distributedVlanConnectionIdParam string, distributedVlanConnectionParam model.DistributedVlanConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", distributedVlanConnectionIdParam, distributedVlanConnectionParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockDistributedVlanConnectionsClientMockRecorder) Patch(distributedVlanConnectionIdParam, distributedVlanConnectionParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockDistributedVlanConnectionsClient)(nil).Patch), distributedVlanConnectionIdParam, distributedVlanConnectionParam)
}

// Update mocks base method.
func (m *MockDistributedVlanConnectionsClient) Update(distributedVlanConnectionIdParam string, distributedVlanConnectionParam model.DistributedVlanConnection) (model.DistributedVlanConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", distributedVlanConnectionIdParam, distributedVlanConnectionParam)
	ret0, _ := ret[0].(model.DistributedVlanConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDistributedVlanConnectionsClientMockRecorder) Update(distributedVlanConnectionIdParam, distributedVlanConnectionParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDistributedVlanConnectionsClient)(nil).Update), distributedVlanConnectionIdParam, distributedVlanConnectionParam)
}
