// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/DistributedVxlanConnectionsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockDistributedVxlanConnectionsClient is a mock of DistributedVxlanConnectionsClient interface.
type MockDistributedVxlanConnectionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockDistributedVxlanConnectionsClientMockRecorder
}

// MockDistributedVxlanConnectionsClientMockRecorder is the mock recorder for MockDistributedVxlanConnectionsClient.
type MockDistributedVxlanConnectionsClientMockRecorder struct {
	mock *MockDistributedVxlanConnectionsClient
}

// NewMockDistributedVxlanConnectionsClient creates a new mock instance.
func NewMockDistributedVxlanConnectionsClient(ctrl *gomock.Controller) *MockDistributedVxlanConnectionsClient {
	mock := &MockDistributedVxlanConnectionsClient{ctrl: ctrl}
	mock.recorder = &MockDistributedVxlanConnectionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistributedVxlanConnectionsClient) EXPECT() *MockDistributedVxlanConnectionsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDistributedVxlanConnectionsClient) Delete(distributedVxlanConnectionIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", distributedVxlanConnectionIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDistributedVxlanConnectionsClientMockRecorder) Delete(distributedVxlanConnectionIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDistributedVxlanConnectionsClient)(nil).Delete), distributedVxlanConnectionIdParam)
}

// Get mocks base method.
func (m *MockDistributedVxlanConnectionsClient) Get(distributedVxlanConnectionIdParam string) (model.DistributedVxlanConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", distributedVxlanConnectionIdParam)
	ret0, _ := ret[0].(model.DistributedVxlanConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDistributedVxlanConnectionsClientMockRecorder) Get(distributedVxlanConnectionIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDistributedVxlanConnectionsClient)(nil).Get), distributedVxlanConnectionIdParam)
}

// List mocks base method.
func (m *MockDistributedVxlanConnectionsClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.DistributedVxlanConnectionListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.DistributedVxlanConnectionListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDistributedVxlanConnectionsClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDistributedVxlanConnectionsClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockDistributedVxlanConnectionsClient) Patch(distributedVxlanConnectionIdParam string, distributedVxlanConnectionParam model.DistributedVxlanConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", distributedVxlanConnectionIdParam, distributedVxlanConnectionParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockDistributedVxlanConnectionsClientMockRecorder) Patch(distributedVxlanConnectionIdParam, distributedVxlanConnectionParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockDistributedVxlanConnectionsClient)(nil).Patch), distributedVxlanConnectionIdParam, distributedVxlanConnectionParam)
}

// Update mocks base method.
func (m *MockDistributedVxlanConnectionsClient) Update(distributedVxlanConnectionIdParam string, distributedVxlanConnectionParam model.DistributedVxlanConnection) (model.DistributedVxlanConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", distributedVxlanConnectionIdParam, distributedVxlanConnectionParam)
	ret0, _ := ret[0].(model.DistributedVxlanConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDistributedVxlanConnectionsClientMockRecorder) Update(distributedVxlanConnectionIdParam, distributedVxlanConnectionParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDistributedVxlanConnectionsClient)(nil).Update), distributedVxlanConnectionIdParam, distributedVxlanConnectionParam)
}
