// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/DistributedTlsBypassProfilesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockDistributedTlsBypassProfilesClient is a mock of DistributedTlsBypassProfilesClient interface.
type MockDistributedTlsBypassProfilesClient struct {
	ctrl     *gomock.Controller
	recorder *MockDistributedTlsBypassProfilesClientMockRecorder
}

// MockDistributedTlsBypassProfilesClientMockRecorder is the mock recorder for MockDistributedTlsBypassProfilesClient.
type MockDistributedTlsBypassProfilesClientMockRecorder struct {
	mock *MockDistributedTlsBypassProfilesClient
}

// NewMockDistributedTlsBypassProfilesClient creates a new mock instance.
func NewMockDistributedTlsBypassProfilesClient(ctrl *gomock.Controller) *MockDistributedTlsBypassProfilesClient {
	mock := &MockDistributedTlsBypassProfilesClient{ctrl: ctrl}
	mock.recorder = &MockDistributedTlsBypassProfilesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistributedTlsBypassProfilesClient) EXPECT() *MockDistributedTlsBypassProfilesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDistributedTlsBypassProfilesClient) Delete(distributedTlsBypassProfileIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", distributedTlsBypassProfileIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDistributedTlsBypassProfilesClientMockRecorder) Delete(distributedTlsBypassProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDistributedTlsBypassProfilesClient)(nil).Delete), distributedTlsBypassProfileIdParam)
}

// Get mocks base method.
func (m *MockDistributedTlsBypassProfilesClient) Get(distributedTlsBypassProfileIdParam string) (model.DistributedTlsBypassProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", distributedTlsBypassProfileIdParam)
	ret0, _ := ret[0].(model.DistributedTlsBypassProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDistributedTlsBypassProfilesClientMockRecorder) Get(distributedTlsBypassProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDistributedTlsBypassProfilesClient)(nil).Get), distributedTlsBypassProfileIdParam)
}

// List mocks base method.
func (m *MockDistributedTlsBypassProfilesClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.DistributedTlsBypassProfileListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.DistributedTlsBypassProfileListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDistributedTlsBypassProfilesClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDistributedTlsBypassProfilesClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockDistributedTlsBypassProfilesClient) Patch(distributedTlsBypassProfileIdParam string, distributedTlsBypassProfileParam model.DistributedTlsBypassProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", distributedTlsBypassProfileIdParam, distributedTlsBypassProfileParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockDistributedTlsBypassProfilesClientMockRecorder) Patch(distributedTlsBypassProfileIdParam, distributedTlsBypassProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockDistributedTlsBypassProfilesClient)(nil).Patch), distributedTlsBypassProfileIdParam, distributedTlsBypassProfileParam)
}

// Update mocks base method.
func (m *MockDistributedTlsBypassProfilesClient) Update(distributedTlsBypassProfileIdParam string, distributedTlsBypassProfileParam model.DistributedTlsBypassProfile) (model.DistributedTlsBypassProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", distributedTlsBypassProfileIdParam, distributedTlsBypassProfileParam)
	ret0, _ := ret[0].(model.DistributedTlsBypassProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDistributedTlsBypassProfilesClientMockRecorder) Update(distributedTlsBypassProfileIdParam, distributedTlsBypassProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDistributedTlsBypassProfilesClient)(nil).Update), distributedTlsBypassProfileIdParam, distributedTlsBypassProfileParam)
}
