// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/DnsSecurityProfilesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockDnsSecurityProfilesClient is a mock of DnsSecurityProfilesClient interface.
type MockDnsSecurityProfilesClient struct {
	ctrl     *gomock.Controller
	recorder *MockDnsSecurityProfilesClientMockRecorder
}

// MockDnsSecurityProfilesClientMockRecorder is the mock recorder for MockDnsSecurityProfilesClient.
type MockDnsSecurityProfilesClientMockRecorder struct {
	mock *MockDnsSecurityProfilesClient
}

// NewMockDnsSecurityProfilesClient creates a new mock instance.
func NewMockDnsSecurityProfilesClient(ctrl *gomock.Controller) *MockDnsSecurityProfilesClient {
	mock := &MockDnsSecurityProfilesClient{ctrl: ctrl}
	mock.recorder = &MockDnsSecurityProfilesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDnsSecurityProfilesClient) EXPECT() *MockDnsSecurityProfilesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDnsSecurityProfilesClient) Delete(profileIdParam string, overrideParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", profileIdParam, overrideParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDnsSecurityProfilesClientMockRecorder) Delete(profileIdParam, overrideParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDnsSecurityProfilesClient)(nil).Delete), profileIdParam, overrideParam)
}

// Get mocks base method.
func (m *MockDnsSecurityProfilesClient) Get(profileIdParam string) (model.DnsSecurityProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", profileIdParam)
	ret0, _ := ret[0].(model.DnsSecurityProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDnsSecurityProfilesClientMockRecorder) Get(profileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDnsSecurityProfilesClient)(nil).Get), profileIdParam)
}

// List mocks base method.
func (m *MockDnsSecurityProfilesClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.DnsSecurityProfileListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.DnsSecurityProfileListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDnsSecurityProfilesClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDnsSecurityProfilesClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockDnsSecurityProfilesClient) Patch(profileIdParam string, dnsSecurityProfileParam model.DnsSecurityProfile, overrideParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", profileIdParam, dnsSecurityProfileParam, overrideParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockDnsSecurityProfilesClientMockRecorder) Patch(profileIdParam, dnsSecurityProfileParam, overrideParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockDnsSecurityProfilesClient)(nil).Patch), profileIdParam, dnsSecurityProfileParam, overrideParam)
}

// Update mocks base method.
func (m *MockDnsSecurityProfilesClient) Update(profileIdParam string, dnsSecurityProfileParam model.DnsSecurityProfile, overrideParam *bool) (model.DnsSecurityProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", profileIdParam, dnsSecurityProfileParam, overrideParam)
	ret0, _ := ret[0].(model.DnsSecurityProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDnsSecurityProfilesClientMockRecorder) Update(profileIdParam, dnsSecurityProfileParam, overrideParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDnsSecurityProfilesClient)(nil).Update), profileIdParam, dnsSecurityProfileParam, overrideParam)
}
