// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/FeaturesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockFeaturesClient is a mock of FeaturesClient interface.
type MockFeaturesClient struct {
	ctrl     *gomock.Controller
	recorder *MockFeaturesClientMockRecorder
}

// MockFeaturesClientMockRecorder is the mock recorder for MockFeaturesClient.
type MockFeaturesClientMockRecorder struct {
	mock *MockFeaturesClient
}

// NewMockFeaturesClient creates a new mock instance.
func NewMockFeaturesClient(ctrl *gomock.Controller) *MockFeaturesClient {
	mock := &MockFeaturesClient{ctrl: ctrl}
	mock.recorder = &MockFeaturesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeaturesClient) EXPECT() *MockFeaturesClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockFeaturesClient) List(sitePathParam *string) (model.AggregatedFeatureListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", sitePathParam)
	ret0, _ := ret[0].(model.AggregatedFeatureListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFeaturesClientMockRecorder) List(sitePathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeaturesClient)(nil).List), sitePathParam)
}
