// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/FirewallIpReputationFeedClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockFirewallIpReputationFeedClient is a mock of FirewallIpReputationFeedClient interface.
type MockFirewallIpReputationFeedClient struct {
	ctrl     *gomock.Controller
	recorder *MockFirewallIpReputationFeedClientMockRecorder
}

// MockFirewallIpReputationFeedClientMockRecorder is the mock recorder for MockFirewallIpReputationFeedClient.
type MockFirewallIpReputationFeedClientMockRecorder struct {
	mock *MockFirewallIpReputationFeedClient
}

// NewMockFirewallIpReputationFeedClient creates a new mock instance.
func NewMockFirewallIpReputationFeedClient(ctrl *gomock.Controller) *MockFirewallIpReputationFeedClient {
	mock := &MockFirewallIpReputationFeedClient{ctrl: ctrl}
	mock.recorder = &MockFirewallIpReputationFeedClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirewallIpReputationFeedClient) EXPECT() *MockFirewallIpReputationFeedClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFirewallIpReputationFeedClient) Create(operationParam string, enforcementPointPathParam *string) (model.PolicyFirewallIpReputationConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", operationParam, enforcementPointPathParam)
	ret0, _ := ret[0].(model.PolicyFirewallIpReputationConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFirewallIpReputationFeedClientMockRecorder) Create(operationParam, enforcementPointPathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFirewallIpReputationFeedClient)(nil).Create), operationParam, enforcementPointPathParam)
}

// Get mocks base method.
func (m *MockFirewallIpReputationFeedClient) Get() (model.PolicyFirewallIpReputationConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(model.PolicyFirewallIpReputationConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFirewallIpReputationFeedClientMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFirewallIpReputationFeedClient)(nil).Get))
}
