// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/FullSyncStatesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/FullSyncStatesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/FullSyncStatesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFullSyncStatesClient is a mock of FullSyncStatesClient interface.
type MockFullSyncStatesClient struct {
	ctrl     *gomock.Controller
	recorder *MockFullSyncStatesClientMockRecorder
	isgomock struct{}
}

// MockFullSyncStatesClientMockRecorder is the mock recorder for MockFullSyncStatesClient.
type MockFullSyncStatesClientMockRecorder struct {
	mock *MockFullSyncStatesClient
}

// NewMockFullSyncStatesClient creates a new mock instance.
func NewMockFullSyncStatesClient(ctrl *gomock.Controller) *MockFullSyncStatesClient {
	mock := &MockFullSyncStatesClient{ctrl: ctrl}
	mock.recorder = &MockFullSyncStatesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFullSyncStatesClient) EXPECT() *MockFullSyncStatesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFullSyncStatesClient) Get(fullSyncIdParam string) (model.FullSyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", fullSyncIdParam)
	ret0, _ := ret[0].(model.FullSyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFullSyncStatesClientMockRecorder) Get(fullSyncIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFullSyncStatesClient)(nil).Get), fullSyncIdParam)
}

// List mocks base method.
func (m *MockFullSyncStatesClient) List(cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.FullSyncStateListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.FullSyncStateListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFullSyncStatesClientMockRecorder) List(cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFullSyncStatesClient)(nil).List), cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
