// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/IpReputationExclusionListClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/IpReputationExclusionListClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/IpReputationExclusionListClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIpReputationExclusionListClient is a mock of IpReputationExclusionListClient interface.
type MockIpReputationExclusionListClient struct {
	ctrl     *gomock.Controller
	recorder *MockIpReputationExclusionListClientMockRecorder
	isgomock struct{}
}

// MockIpReputationExclusionListClientMockRecorder is the mock recorder for MockIpReputationExclusionListClient.
type MockIpReputationExclusionListClientMockRecorder struct {
	mock *MockIpReputationExclusionListClient
}

// NewMockIpReputationExclusionListClient creates a new mock instance.
func NewMockIpReputationExclusionListClient(ctrl *gomock.Controller) *MockIpReputationExclusionListClient {
	mock := &MockIpReputationExclusionListClient{ctrl: ctrl}
	mock.recorder = &MockIpReputationExclusionListClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpReputationExclusionListClient) EXPECT() *MockIpReputationExclusionListClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIpReputationExclusionListClient) Get(cursorParam, enforcementPointPathParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.IPReputationExclusionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", cursorParam, enforcementPointPathParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.IPReputationExclusionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIpReputationExclusionListClientMockRecorder) Get(cursorParam, enforcementPointPathParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIpReputationExclusionListClient)(nil).Get), cursorParam, enforcementPointPathParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
