// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/IpsecVpnIkeProfilesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockIpsecVpnIkeProfilesClient is a mock of IpsecVpnIkeProfilesClient interface.
type MockIpsecVpnIkeProfilesClient struct {
	ctrl     *gomock.Controller
	recorder *MockIpsecVpnIkeProfilesClientMockRecorder
}

// MockIpsecVpnIkeProfilesClientMockRecorder is the mock recorder for MockIpsecVpnIkeProfilesClient.
type MockIpsecVpnIkeProfilesClientMockRecorder struct {
	mock *MockIpsecVpnIkeProfilesClient
}

// NewMockIpsecVpnIkeProfilesClient creates a new mock instance.
func NewMockIpsecVpnIkeProfilesClient(ctrl *gomock.Controller) *MockIpsecVpnIkeProfilesClient {
	mock := &MockIpsecVpnIkeProfilesClient{ctrl: ctrl}
	mock.recorder = &MockIpsecVpnIkeProfilesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpsecVpnIkeProfilesClient) EXPECT() *MockIpsecVpnIkeProfilesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIpsecVpnIkeProfilesClient) Delete(ikeProfileIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ikeProfileIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIpsecVpnIkeProfilesClientMockRecorder) Delete(ikeProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIpsecVpnIkeProfilesClient)(nil).Delete), ikeProfileIdParam)
}

// Get mocks base method.
func (m *MockIpsecVpnIkeProfilesClient) Get(ikeProfileIdParam string) (model.IPSecVpnIkeProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ikeProfileIdParam)
	ret0, _ := ret[0].(model.IPSecVpnIkeProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIpsecVpnIkeProfilesClientMockRecorder) Get(ikeProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIpsecVpnIkeProfilesClient)(nil).Get), ikeProfileIdParam)
}

// List mocks base method.
func (m *MockIpsecVpnIkeProfilesClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.IPSecVpnIkeProfileListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.IPSecVpnIkeProfileListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIpsecVpnIkeProfilesClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIpsecVpnIkeProfilesClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockIpsecVpnIkeProfilesClient) Patch(ikeProfileIdParam string, ipSecVpnIkeProfileParam model.IPSecVpnIkeProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ikeProfileIdParam, ipSecVpnIkeProfileParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockIpsecVpnIkeProfilesClientMockRecorder) Patch(ikeProfileIdParam, ipSecVpnIkeProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockIpsecVpnIkeProfilesClient)(nil).Patch), ikeProfileIdParam, ipSecVpnIkeProfileParam)
}

// Update mocks base method.
func (m *MockIpsecVpnIkeProfilesClient) Update(ikeProfileIdParam string, ipSecVpnIkeProfileParam model.IPSecVpnIkeProfile) (model.IPSecVpnIkeProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ikeProfileIdParam, ipSecVpnIkeProfileParam)
	ret0, _ := ret[0].(model.IPSecVpnIkeProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIpsecVpnIkeProfilesClientMockRecorder) Update(ikeProfileIdParam, ipSecVpnIkeProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIpsecVpnIkeProfilesClient)(nil).Update), ikeProfileIdParam, ipSecVpnIkeProfileParam)
}
