// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/L7AccessProfilesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/L7AccessProfilesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/L7AccessProfilesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockL7AccessProfilesClient is a mock of L7AccessProfilesClient interface.
type MockL7AccessProfilesClient struct {
	ctrl     *gomock.Controller
	recorder *MockL7AccessProfilesClientMockRecorder
	isgomock struct{}
}

// MockL7AccessProfilesClientMockRecorder is the mock recorder for MockL7AccessProfilesClient.
type MockL7AccessProfilesClientMockRecorder struct {
	mock *MockL7AccessProfilesClient
}

// NewMockL7AccessProfilesClient creates a new mock instance.
func NewMockL7AccessProfilesClient(ctrl *gomock.Controller) *MockL7AccessProfilesClient {
	mock := &MockL7AccessProfilesClient{ctrl: ctrl}
	mock.recorder = &MockL7AccessProfilesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockL7AccessProfilesClient) EXPECT() *MockL7AccessProfilesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockL7AccessProfilesClient) Delete(l7AccessProfileIdParam string, overrideParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", l7AccessProfileIdParam, overrideParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockL7AccessProfilesClientMockRecorder) Delete(l7AccessProfileIdParam, overrideParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockL7AccessProfilesClient)(nil).Delete), l7AccessProfileIdParam, overrideParam)
}

// Get mocks base method.
func (m *MockL7AccessProfilesClient) Get(l7AccessProfileIdParam string) (model.L7AccessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", l7AccessProfileIdParam)
	ret0, _ := ret[0].(model.L7AccessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockL7AccessProfilesClientMockRecorder) Get(l7AccessProfileIdParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockL7AccessProfilesClient)(nil).Get), l7AccessProfileIdParam)
}

// List mocks base method.
func (m *MockL7AccessProfilesClient) List(cursorParam *string, hasUnsupportedAppIdsParam, includeConflictsParam, includeEntryCountParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.L7AccessProfileListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, hasUnsupportedAppIdsParam, includeConflictsParam, includeEntryCountParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.L7AccessProfileListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockL7AccessProfilesClientMockRecorder) List(cursorParam, hasUnsupportedAppIdsParam, includeConflictsParam, includeEntryCountParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockL7AccessProfilesClient)(nil).List), cursorParam, hasUnsupportedAppIdsParam, includeConflictsParam, includeEntryCountParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockL7AccessProfilesClient) Patch(l7AccessProfileIdParam string, l7AccessProfileParam model.L7AccessProfile, overrideParam *bool) (model.L7AccessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", l7AccessProfileIdParam, l7AccessProfileParam, overrideParam)
	ret0, _ := ret[0].(model.L7AccessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockL7AccessProfilesClientMockRecorder) Patch(l7AccessProfileIdParam, l7AccessProfileParam, overrideParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockL7AccessProfilesClient)(nil).Patch), l7AccessProfileIdParam, l7AccessProfileParam, overrideParam)
}

// Update mocks base method.
func (m *MockL7AccessProfilesClient) Update(l7AccessProfileIdParam string, l7AccessProfileParam model.L7AccessProfile, overrideParam *bool) (model.L7AccessProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", l7AccessProfileIdParam, l7AccessProfileParam, overrideParam)
	ret0, _ := ret[0].(model.L7AccessProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockL7AccessProfilesClientMockRecorder) Update(l7AccessProfileIdParam, l7AccessProfileParam, overrideParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockL7AccessProfilesClient)(nil).Update), l7AccessProfileIdParam, l7AccessProfileParam, overrideParam)
}
