// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/LbNodeUsageSummaryClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/LbNodeUsageSummaryClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/LbNodeUsageSummaryClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLbNodeUsageSummaryClient is a mock of LbNodeUsageSummaryClient interface.
type MockLbNodeUsageSummaryClient struct {
	ctrl     *gomock.Controller
	recorder *MockLbNodeUsageSummaryClientMockRecorder
	isgomock struct{}
}

// MockLbNodeUsageSummaryClientMockRecorder is the mock recorder for MockLbNodeUsageSummaryClient.
type MockLbNodeUsageSummaryClientMockRecorder struct {
	mock *MockLbNodeUsageSummaryClient
}

// NewMockLbNodeUsageSummaryClient creates a new mock instance.
func NewMockLbNodeUsageSummaryClient(ctrl *gomock.Controller) *MockLbNodeUsageSummaryClient {
	mock := &MockLbNodeUsageSummaryClient{ctrl: ctrl}
	mock.recorder = &MockLbNodeUsageSummaryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLbNodeUsageSummaryClient) EXPECT() *MockLbNodeUsageSummaryClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLbNodeUsageSummaryClient) Get(enforcementPointPathParam *string, includeUsagesParam *bool, nodeTypeParam *string) (model.AggregateLBNodeUsageSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", enforcementPointPathParam, includeUsagesParam, nodeTypeParam)
	ret0, _ := ret[0].(model.AggregateLBNodeUsageSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLbNodeUsageSummaryClientMockRecorder) Get(enforcementPointPathParam, includeUsagesParam, nodeTypeParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLbNodeUsageSummaryClient)(nil).Get), enforcementPointPathParam, includeUsagesParam, nodeTypeParam)
}
