// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/LbPoolsClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockLbPoolsClient is a mock of LbPoolsClient interface.
type MockLbPoolsClient struct {
	ctrl     *gomock.Controller
	recorder *MockLbPoolsClientMockRecorder
}

// MockLbPoolsClientMockRecorder is the mock recorder for MockLbPoolsClient.
type MockLbPoolsClientMockRecorder struct {
	mock *MockLbPoolsClient
}

// NewMockLbPoolsClient creates a new mock instance.
func NewMockLbPoolsClient(ctrl *gomock.Controller) *MockLbPoolsClient {
	mock := &MockLbPoolsClient{ctrl: ctrl}
	mock.recorder = &MockLbPoolsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLbPoolsClient) EXPECT() *MockLbPoolsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLbPoolsClient) Delete(lbPoolIdParam string, forceParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", lbPoolIdParam, forceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLbPoolsClientMockRecorder) Delete(lbPoolIdParam, forceParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLbPoolsClient)(nil).Delete), lbPoolIdParam, forceParam)
}

// Get mocks base method.
func (m *MockLbPoolsClient) Get(lbPoolIdParam string) (model.LBPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", lbPoolIdParam)
	ret0, _ := ret[0].(model.LBPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLbPoolsClientMockRecorder) Get(lbPoolIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLbPoolsClient)(nil).Get), lbPoolIdParam)
}

// List mocks base method.
func (m *MockLbPoolsClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.LBPoolListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.LBPoolListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLbPoolsClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLbPoolsClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockLbPoolsClient) Patch(lbPoolIdParam string, lbPoolParam model.LBPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", lbPoolIdParam, lbPoolParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockLbPoolsClientMockRecorder) Patch(lbPoolIdParam, lbPoolParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockLbPoolsClient)(nil).Patch), lbPoolIdParam, lbPoolParam)
}

// Update mocks base method.
func (m *MockLbPoolsClient) Update(lbPoolIdParam string, lbPoolParam model.LBPool) (model.LBPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", lbPoolIdParam, lbPoolParam)
	ret0, _ := ret[0].(model.LBPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLbPoolsClientMockRecorder) Update(lbPoolIdParam, lbPoolParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLbPoolsClient)(nil).Update), lbPoolIdParam, lbPoolParam)
}
