// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/ManualHealthChecksClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockManualHealthChecksClient is a mock of ManualHealthChecksClient interface.
type MockManualHealthChecksClient struct {
	ctrl     *gomock.Controller
	recorder *MockManualHealthChecksClientMockRecorder
}

// MockManualHealthChecksClientMockRecorder is the mock recorder for MockManualHealthChecksClient.
type MockManualHealthChecksClientMockRecorder struct {
	mock *MockManualHealthChecksClient
}

// NewMockManualHealthChecksClient creates a new mock instance.
func NewMockManualHealthChecksClient(ctrl *gomock.Controller) *MockManualHealthChecksClient {
	mock := &MockManualHealthChecksClient{ctrl: ctrl}
	mock.recorder = &MockManualHealthChecksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManualHealthChecksClient) EXPECT() *MockManualHealthChecksClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockManualHealthChecksClient) Create(manualHealthCheckIdParam string, policyManualHealthCheckParam model.PolicyManualHealthCheck) (model.PolicyManualHealthCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", manualHealthCheckIdParam, policyManualHealthCheckParam)
	ret0, _ := ret[0].(model.PolicyManualHealthCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockManualHealthChecksClientMockRecorder) Create(manualHealthCheckIdParam, policyManualHealthCheckParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockManualHealthChecksClient)(nil).Create), manualHealthCheckIdParam, policyManualHealthCheckParam)
}

// Delete mocks base method.
func (m *MockManualHealthChecksClient) Delete(manualHealthCheckIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", manualHealthCheckIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManualHealthChecksClientMockRecorder) Delete(manualHealthCheckIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManualHealthChecksClient)(nil).Delete), manualHealthCheckIdParam)
}

// Get mocks base method.
func (m *MockManualHealthChecksClient) Get(manualHealthCheckIdParam string) (model.PolicyManualHealthCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", manualHealthCheckIdParam)
	ret0, _ := ret[0].(model.PolicyManualHealthCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockManualHealthChecksClientMockRecorder) Get(manualHealthCheckIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockManualHealthChecksClient)(nil).Get), manualHealthCheckIdParam)
}

// List mocks base method.
func (m *MockManualHealthChecksClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyManualHealthCheckList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyManualHealthCheckList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockManualHealthChecksClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockManualHealthChecksClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
