// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/PartnerServicesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockPartnerServicesClient is a mock of PartnerServicesClient interface.
type MockPartnerServicesClient struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerServicesClientMockRecorder
}

// MockPartnerServicesClientMockRecorder is the mock recorder for MockPartnerServicesClient.
type MockPartnerServicesClientMockRecorder struct {
	mock *MockPartnerServicesClient
}

// NewMockPartnerServicesClient creates a new mock instance.
func NewMockPartnerServicesClient(ctrl *gomock.Controller) *MockPartnerServicesClient {
	mock := &MockPartnerServicesClient{ctrl: ctrl}
	mock.recorder = &MockPartnerServicesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerServicesClient) EXPECT() *MockPartnerServicesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPartnerServicesClient) Get(serviceNameParam string) (model.ServiceDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", serviceNameParam)
	ret0, _ := ret[0].(model.ServiceDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPartnerServicesClientMockRecorder) Get(serviceNameParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPartnerServicesClient)(nil).Get), serviceNameParam)
}

// List mocks base method.
func (m *MockPartnerServicesClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.ServiceInsertionServiceListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.ServiceInsertionServiceListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPartnerServicesClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPartnerServicesClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
