// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/SitesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockSitesClient is a mock of SitesClient interface.
type MockSitesClient struct {
	ctrl     *gomock.Controller
	recorder *MockSitesClientMockRecorder
}

// MockSitesClientMockRecorder is the mock recorder for MockSitesClient.
type MockSitesClientMockRecorder struct {
	mock *MockSitesClient
}

// NewMockSitesClient creates a new mock instance.
func NewMockSitesClient(ctrl *gomock.Controller) *MockSitesClient {
	mock := &MockSitesClient{ctrl: ctrl}
	mock.recorder = &MockSitesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSitesClient) EXPECT() *MockSitesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSitesClient) Delete(siteIdParam string, forceParam *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", siteIdParam, forceParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSitesClientMockRecorder) Delete(siteIdParam, forceParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSitesClient)(nil).Delete), siteIdParam, forceParam)
}

// Get mocks base method.
func (m *MockSitesClient) Get(siteIdParam string) (model.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", siteIdParam)
	ret0, _ := ret[0].(model.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSitesClientMockRecorder) Get(siteIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSitesClient)(nil).Get), siteIdParam)
}

// List mocks base method.
func (m *MockSitesClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.SiteListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.SiteListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSitesClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSitesClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockSitesClient) Patch(siteIdParam string, siteParam model.Site) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", siteIdParam, siteParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockSitesClientMockRecorder) Patch(siteIdParam, siteParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockSitesClient)(nil).Patch), siteIdParam, siteParam)
}

// Update mocks base method.
func (m *MockSitesClient) Update(siteIdParam string, siteParam model.Site) (model.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", siteIdParam, siteParam)
	ret0, _ := ret[0].(model.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSitesClientMockRecorder) Update(siteIdParam, siteParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSitesClient)(nil).Update), siteIdParam, siteParam)
}
