// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/SpanClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockSpanClient is a mock of SpanClient interface.
type MockSpanClient struct {
	ctrl     *gomock.Controller
	recorder *MockSpanClientMockRecorder
}

// MockSpanClientMockRecorder is the mock recorder for MockSpanClient.
type MockSpanClientMockRecorder struct {
	mock *MockSpanClient
}

// NewMockSpanClient creates a new mock instance.
func NewMockSpanClient(ctrl *gomock.Controller) *MockSpanClient {
	mock := &MockSpanClient{ctrl: ctrl}
	mock.recorder = &MockSpanClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpanClient) EXPECT() *MockSpanClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSpanClient) Get(intentPathParam string, sitePathParam *string) (model.Span, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", intentPathParam, sitePathParam)
	ret0, _ := ret[0].(model.Span)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSpanClientMockRecorder) Get(intentPathParam, sitePathParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSpanClient)(nil).Get), intentPathParam, sitePathParam)
}
