// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/TlsInspectionActionProfilesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/vmware/vsphere-automation-sdk-go/runtime/data"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockTlsInspectionActionProfilesClient is a mock of TlsInspectionActionProfilesClient interface.
type MockTlsInspectionActionProfilesClient struct {
	ctrl     *gomock.Controller
	recorder *MockTlsInspectionActionProfilesClientMockRecorder
}

// MockTlsInspectionActionProfilesClientMockRecorder is the mock recorder for MockTlsInspectionActionProfilesClient.
type MockTlsInspectionActionProfilesClientMockRecorder struct {
	mock *MockTlsInspectionActionProfilesClient
}

// NewMockTlsInspectionActionProfilesClient creates a new mock instance.
func NewMockTlsInspectionActionProfilesClient(ctrl *gomock.Controller) *MockTlsInspectionActionProfilesClient {
	mock := &MockTlsInspectionActionProfilesClient{ctrl: ctrl}
	mock.recorder = &MockTlsInspectionActionProfilesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTlsInspectionActionProfilesClient) EXPECT() *MockTlsInspectionActionProfilesClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTlsInspectionActionProfilesClient) Delete(actionProfileIdParam string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", actionProfileIdParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTlsInspectionActionProfilesClientMockRecorder) Delete(actionProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTlsInspectionActionProfilesClient)(nil).Delete), actionProfileIdParam)
}

// Get mocks base method.
func (m *MockTlsInspectionActionProfilesClient) Get(actionProfileIdParam string) (*data.StructValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", actionProfileIdParam)
	ret0, _ := ret[0].(*data.StructValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTlsInspectionActionProfilesClientMockRecorder) Get(actionProfileIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTlsInspectionActionProfilesClient)(nil).Get), actionProfileIdParam)
}

// List mocks base method.
func (m *MockTlsInspectionActionProfilesClient) List(cursorParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.TlsProfileListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.TlsProfileListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTlsInspectionActionProfilesClientMockRecorder) List(cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTlsInspectionActionProfilesClient)(nil).List), cursorParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}

// Patch mocks base method.
func (m *MockTlsInspectionActionProfilesClient) Patch(actionProfileIdParam string, tlsProfileParam *data.StructValue) (*data.StructValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", actionProfileIdParam, tlsProfileParam)
	ret0, _ := ret[0].(*data.StructValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockTlsInspectionActionProfilesClientMockRecorder) Patch(actionProfileIdParam, tlsProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockTlsInspectionActionProfilesClient)(nil).Patch), actionProfileIdParam, tlsProfileParam)
}

// Update mocks base method.
func (m *MockTlsInspectionActionProfilesClient) Update(actionProfileIdParam string, tlsProfileParam *data.StructValue) (*data.StructValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", actionProfileIdParam, tlsProfileParam)
	ret0, _ := ret[0].(*data.StructValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTlsInspectionActionProfilesClientMockRecorder) Update(actionProfileIdParam, tlsProfileParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTlsInspectionActionProfilesClient)(nil).Update), actionProfileIdParam, tlsProfileParam)
}
