// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/UrlReputationSeveritiesClient.go
//
// Generated by this command:
//
//	mockgen -source /Users/ks028943/go/pkg/mod/github.com/vmware/vsphere-automation-sdk-go/services/nsxt@v0.12.1-0.20260902054918-9a4e0ebc788a/infra/UrlReputationSeveritiesClient.go -destination /Users/ks028943/go/src/terraform-provider-nsxt/mocks/infra/UrlReputationSeveritiesClient.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUrlReputationSeveritiesClient is a mock of UrlReputationSeveritiesClient interface.
type MockUrlReputationSeveritiesClient struct {
	ctrl     *gomock.Controller
	recorder *MockUrlReputationSeveritiesClientMockRecorder
	isgomock struct{}
}

// MockUrlReputationSeveritiesClientMockRecorder is the mock recorder for MockUrlReputationSeveritiesClient.
type MockUrlReputationSeveritiesClientMockRecorder struct {
	mock *MockUrlReputationSeveritiesClient
}

// NewMockUrlReputationSeveritiesClient creates a new mock instance.
func NewMockUrlReputationSeveritiesClient(ctrl *gomock.Controller) *MockUrlReputationSeveritiesClient {
	mock := &MockUrlReputationSeveritiesClient{ctrl: ctrl}
	mock.recorder = &MockUrlReputationSeveritiesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlReputationSeveritiesClient) EXPECT() *MockUrlReputationSeveritiesClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockUrlReputationSeveritiesClient) List(cursorParam *string, includeConflictsParam, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyUrlReputationSeverityListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyUrlReputationSeverityListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUrlReputationSeveritiesClientMockRecorder) List(cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUrlReputationSeveritiesClient)(nil).List), cursorParam, includeConflictsParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
