// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/tier_0s/groups/members/IpAddressesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockIpAddressesClient is a mock of IpAddressesClient interface.
type MockIpAddressesClient struct {
	ctrl     *gomock.Controller
	recorder *MockIpAddressesClientMockRecorder
}

// MockIpAddressesClientMockRecorder is the mock recorder for MockIpAddressesClient.
type MockIpAddressesClientMockRecorder struct {
	mock *MockIpAddressesClient
}

// NewMockIpAddressesClient creates a new mock instance.
func NewMockIpAddressesClient(ctrl *gomock.Controller) *MockIpAddressesClient {
	mock := &MockIpAddressesClient{ctrl: ctrl}
	mock.recorder = &MockIpAddressesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpAddressesClient) EXPECT() *MockIpAddressesClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockIpAddressesClient) List(tier0IdParam, groupIdParam string, cursorParam, enforcementPointPathParam *string, includeMarkForDeleteObjectsParam *bool, includedFieldsParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model.PolicyGroupIPMembersListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tier0IdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
	ret0, _ := ret[0].(model.PolicyGroupIPMembersListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIpAddressesClientMockRecorder) List(tier0IdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIpAddressesClient)(nil).List), tier0IdParam, groupIdParam, cursorParam, enforcementPointPathParam, includeMarkForDeleteObjectsParam, includedFieldsParam, pageSizeParam, sortAscendingParam, sortByParam)
}
