// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points/edge_clusters/edge_nodes/remote_tep_connectivity/bgp/neighbors/AdvertisedRoutesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockAdvertisedRoutesClient is a mock of AdvertisedRoutesClient interface.
type MockAdvertisedRoutesClient struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertisedRoutesClientMockRecorder
}

// MockAdvertisedRoutesClientMockRecorder is the mock recorder for MockAdvertisedRoutesClient.
type MockAdvertisedRoutesClientMockRecorder struct {
	mock *MockAdvertisedRoutesClient
}

// NewMockAdvertisedRoutesClient creates a new mock instance.
func NewMockAdvertisedRoutesClient(ctrl *gomock.Controller) *MockAdvertisedRoutesClient {
	mock := &MockAdvertisedRoutesClient{ctrl: ctrl}
	mock.recorder = &MockAdvertisedRoutesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvertisedRoutesClient) EXPECT() *MockAdvertisedRoutesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAdvertisedRoutesClient) Get(siteIdParam, enforcementpointIdParam, edgeClusterIdParam, policyEdgeNodeIdParam, neighborIdParam string) (model.PolicyEdgeNodeBgpNeighborAdvertisedRoutes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", siteIdParam, enforcementpointIdParam, edgeClusterIdParam, policyEdgeNodeIdParam, neighborIdParam)
	ret0, _ := ret[0].(model.PolicyEdgeNodeBgpNeighborAdvertisedRoutes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdvertisedRoutesClientMockRecorder) Get(siteIdParam, enforcementpointIdParam, edgeClusterIdParam, policyEdgeNodeIdParam, neighborIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdvertisedRoutesClient)(nil).Get), siteIdParam, enforcementpointIdParam, edgeClusterIdParam, policyEdgeNodeIdParam, neighborIdParam)
}
