// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aruntony/Desktop/playground/vcf/vsphere-automation-sdk-go/services/nsxt/infra/sites/enforcement_points/edge_clusters/edge_nodes/remote_tep_connectivity/bgp/neighbors/RoutesClient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
)

// MockRoutesClient is a mock of RoutesClient interface.
type MockRoutesClient struct {
	ctrl     *gomock.Controller
	recorder *MockRoutesClientMockRecorder
}

// MockRoutesClientMockRecorder is the mock recorder for MockRoutesClient.
type MockRoutesClientMockRecorder struct {
	mock *MockRoutesClient
}

// NewMockRoutesClient creates a new mock instance.
func NewMockRoutesClient(ctrl *gomock.Controller) *MockRoutesClient {
	mock := &MockRoutesClient{ctrl: ctrl}
	mock.recorder = &MockRoutesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoutesClient) EXPECT() *MockRoutesClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRoutesClient) Get(siteIdParam, enforcementpointIdParam, edgeClusterIdParam, policyEdgeNodeIdParam, neighborIdParam string) (model.PolicyEdgeNodeBgpNeighborRouteDetailList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", siteIdParam, enforcementpointIdParam, edgeClusterIdParam, policyEdgeNodeIdParam, neighborIdParam)
	ret0, _ := ret[0].(model.PolicyEdgeNodeBgpNeighborRouteDetailList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoutesClientMockRecorder) Get(siteIdParam, enforcementpointIdParam, edgeClusterIdParam, policyEdgeNodeIdParam, neighborIdParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoutesClient)(nil).Get), siteIdParam, enforcementpointIdParam, edgeClusterIdParam, policyEdgeNodeIdParam, neighborIdParam)
}
