//nolint:revive
package fabric

// The following file has been autogenerated. Please avoid any changes!
import (
	"errors"

	vapiProtocolClient_ "github.com/vmware/vsphere-automation-sdk-go/runtime/protocol/client"
	client0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/fabric"
	model0 "github.com/vmware/vsphere-automation-sdk-go/services/nsxt-mp/nsx/model"

	utl "github.com/vmware/terraform-provider-nsxt/api/utl"
)

type ComputeCollectionClientContext utl.ClientContext

func NewComputeCollectionsClient(sessionContext utl.SessionContext, connector vapiProtocolClient_.Connector) *ComputeCollectionClientContext {
	var client interface{}

	switch sessionContext.ClientType {

	case utl.Local:
		client = client0.NewComputeCollectionsClient(connector)

	default:
		return nil
	}
	return &ComputeCollectionClientContext{Client: client, ClientType: sessionContext.ClientType, ProjectID: sessionContext.ProjectID, VPCID: sessionContext.VPCID}
}

func (c ComputeCollectionClientContext) Create(ccExtIdParam string, actionParam *string) error {
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.ComputeCollectionsClient)
		err = client.Create(ccExtIdParam, actionParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return err
}

func (c ComputeCollectionClientContext) Get(ccExtIdParam string) (model0.ComputeCollection, error) {
	var obj model0.ComputeCollection
	var err error

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.ComputeCollectionsClient)
		obj, err = client.Get(ccExtIdParam)
		if err != nil {
			return obj, err
		}

	default:
		return obj, errors.New("invalid infrastructure for model")
	}
	return obj, err
}

func (c ComputeCollectionClientContext) List(cmLocalIdParam *string, cursorParam *string, discoveredNodeIdParam *string, displayNameParam *string, externalIdParam *string, includedFieldsParam *string, nodeIdParam *string, originIdParam *string, originTypeParam *string, ownerIdParam *string, pageSizeParam *int64, sortAscendingParam *bool, sortByParam *string) (model0.ComputeCollectionListResult, error) {
	var err error
	var obj model0.ComputeCollectionListResult

	switch c.ClientType {

	case utl.Local:
		client := c.Client.(client0.ComputeCollectionsClient)
		obj, err = client.List(cmLocalIdParam, cursorParam, discoveredNodeIdParam, displayNameParam, externalIdParam, includedFieldsParam, nodeIdParam, originIdParam, originTypeParam, ownerIdParam, pageSizeParam, sortAscendingParam, sortByParam)

	default:
		err = errors.New("invalid infrastructure for model")
	}
	return obj, err
}
