---
name: docs-lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Install Tools
        run: make tools
      - name: Docs HCL Lint
        run: make docs-lint
      - name: Docs Lint
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          config: '.markdownlint.jsonc'
          globs: |
            docs/*.md
            docs/data-sources/*.md
            docs/guides/*.md
            docs/resources/*.md
