---
name: Formatting check (nsxt)

on:
  pull_request:
    paths:
      - 'nsxt/**'
      - '.github/workflows/fmt-check.yml'
  push:
    branches:
      - master
      - 'branch_*'
      - 'release-*'
    paths:
      - 'nsxt/**'
      - '.github/workflows/fmt-check.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  fmt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Run formatting tests
        run: make fmtcheck
