---
name: Formatting check (nsxt)

on:
  push:
    paths:
      - 'nsxt/**'
      - '.github/workflows/fmt-check.yml'
  pull_request:
    paths:
      - 'nsxt/**'
      - '.github/workflows/fmt-check.yml'

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Run unit tests
        run: make fmtcheck