---
name: Formatting check (nsxt)

on:
  push:
    paths:
      - 'nsxt/**'
      - '.github/workflows/fmt-check.yml'
  pull_request:
    paths:
      - 'nsxt/**'
      - '.github/workflows/fmt-check.yml'

permissions:
  contents: read

jobs:
  fmt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Run formatting tests
        run: make fmtcheck
