---
name: go-security

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    paths-ignore:
      - README.md
  schedule:
    - cron: 0 0 * * 0

permissions:
  contents: read

jobs:
  security:
    name: Go security checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Download Go Modules
        run: go mod download
      - name: Build
        run: go build -v .
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck ./...
