---
name: Tests

on:
  pull_request:
    paths:
      - 'nsxt/metadata/**.go'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./nsxt/metadata/...  -coverpkg=./nsxt/metadata/...
