---
name: Tests

on:
  pull_request:
    paths:
      - 'nsxt/metadata/**.go'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./nsxt/metadata/...  -coverpkg=./nsxt/metadata/...
